htmlTags = {
    "name" : "character_name",
    "race" : "race",
    "raceStr" : "str_race",
    "raceDex" : "dex_race",
    "raceCon" : "con_race",
    "raceInt" : "int_race",
    "raceWis" : "wis_race",
    "raceCha" : "cha_race",
    "theme" : "theme",
    "themeStr" : "str_theme",
    "themeDex" : "dex_theme",
    "themeCon" : "con_theme",
    "themeInt" : "int_theme",
    "themeWis" : "wis_theme",
    "themeCha" : "cha_theme",
    "attrStr" : "str_score",
    "attrDex" : "dex_score",
    "attrCon" : "con_score",
    "attrInt" : "int_score",
    "attrWis" : "wis_score",
    "attrCha" : "cha_score",
    "attrStrMod" : "str_mod",
    "attrDexMod" : "dex_mod",
    "attrConMod" : "con_mod",
    "attrIntMod" : "int_mod",
    "attrWisMod" : "wis_mod",
    "attrChaMod" : "cha_mod",
    "attrStrPoint" : "str_point",
    "attrDexPoint" : "dex_point",
    "attrConPoint" : "con_point",
    "attrIntPoint" : "int_point",
    "attrWisPoint" : "wis_point",
    "attrChaPoint" : "cha_point",
    "abilityStr" : "str_ability",
    "abilityDex" : "dex_ability",
    "abilityCon" : "con_ability",
    "abilityInt" : "int_ability",
    "abilityWis" : "wis_ability",
    "abilityCha" : "cha_ability",


    "className" : "class_level",
    "init_total" : "init_total",
    "init_dex" : "init_dex",
    "init_misc" : "init_misc",

    "eac" : "ac_eac_total",
    "eac_armor" : "ac_eac_abonus",
    "eac_dex" : "ac_eac_dexmod",
    "eac_misc" : "ac_eac_miscmod",
    "kac" : "ac_kac_total",
    "kac_armor" : "ac_kac_abonus",
    "kac_dex" : "ac_kac_dexmod",
    "kac_misc" : "ac_kac_miscmod",
    "vsCombat" : "ac_acvs_total",

    "sp" : "total_stamina",
    "hp" : "total_hp",
    "rp" : "total_resolve",

    "fortSave" : "save_fort_total",
    "reflexSave" : "save_refl_total",
    "willSave" : "save_will_total",

    "fortSaveBase" : "save_fort_base",
    "reflexSaveBase" : "save_refl_base",
    "willSaveBase" : "save_will_base",

    "fortSaveAbility" : "save_fort_ability",
    "reflexSaveAbility" : "save_refl_ability",
    "willSaveAbility" : "save_will_ability",

    "fortSaveMisc" : "save_fort_misc",
    "reflexSaveMisc" : "save_refl_misc",
    "willSaveMisc" : "save_will_misc",

    "melee" : "attack_melee_total",
    "melee_bab" : "attack_melee_bab",
    "melee_ability" : "attack_melee_ability",
    "melee_misc" : "attack_melee_misc",
    "range" : "attack_range_total",
    "range_bab" : "attack_range_bab",
    "range_ability" : "attack_range_ability",
    "range_misc" : "attack_range_misc",
    "throw" : "attack_throw_total",
    "throw_bab" : "attack_throw_bab",
    "throw_ability" : "attack_throw_ability",
    "throw_misc" : "attack_throw_misc",

    "acrobatics"      : "skills_acrobatics_total",
    "athletics"       : "skills_athletics_total",
    "bluff"           : "skills_bluff_total",
    "computers"       : "skills_computers_total",
    "culture"         : "skills_culture_total",
    "diplomacy"       : "skills_diplomacy_total",
    "disguise"        : "skills_disguise_total",
    "engineering"     : "skills_engineering_total",
    "intimidate"      : "skills_intimidate_total",
    "life science"    : "skills_life_science_total",
    "medicine"        : "skills_medicine_total",
    "mysticism"       : "skills_mysticism_total",
    "perception"      : "skills_perception_total",
    "physical science": "skills_physical_science_total",
    "piloting"        : "skills_piloting_total",
    "profession"      : "skills_profession_total",
    "profession2"     : "skills_profession2_total",
    "sense motive"    : "skills_sense_motive_total",
    "sleight of hand" : "skills_sleight_of_hand_total",
    "stealth"         : "skills_stealth_total",
    "survival"        : "skills_survival_total",

    "acrobaticsRank"      : "skills_acrobatics_ranks",
    "athleticsRank"       : "skills_athletics_ranks",
    "bluffRank"           : "skills_bluff_ranks",
    "computersRank"       : "skills_computers_ranks",
    "cultureRank"         : "skills_culture_ranks",
    "diplomacyRank"       : "skills_diplomacy_ranks",
    "disguiseRank"        : "skills_disguise_ranks",
    "engineeringRank"     : "skills_engineering_ranks",
    "intimidateRank"      : "skills_intimidate_ranks",
    "life scienceRank"    : "skills_life_science_ranks",
    "medicineRank"        : "skills_medicine_ranks",
    "mysticismRank"       : "skills_mysticism_ranks",
    "perceptionRank"      : "skills_perception_ranks",
    "physical scienceRank": "skills_physical_science_ranks",
    "pilotingRank"        : "skills_piloting_ranks",
    "professionRank"      : "skills_profession_ranks",
    "profession2Rank"     : "skills_profession2_ranks",
    "sense motiveRank"    : "skills_sense_motive_ranks",
    "sleight of handRank" : "skills_sleight_of_hand_ranks",
    "stealthRank"         : "skills_stealth_ranks",
    "survivalRank"        : "skills_survival_ranks",

    "acrobaticsMod"      : "skills_acrobatics_ability",
    "athleticsMod"       : "skills_athletics_ability",
    "bluffMod"           : "skills_bluff_ability",
    "computersMod"       : "skills_computers_ability",
    "cultureMod"         : "skills_culture_ability",
    "diplomacyMod"       : "skills_diplomacy_ability",
    "disguiseMod"        : "skills_disguise_ability",
    "engineeringMod"     : "skills_engineering_ability",
    "intimidateMod"      : "skills_intimidate_ability",
    "life scienceMod"    : "skills_life_science_ability",
    "medicineMod"        : "skills_medicine_ability",
    "mysticismMod"       : "skills_mysticism_ability",
    "perceptionMod"      : "skills_perception_ability",
    "physical scienceMod": "skills_physical_science_ability",
    "pilotingMod"        : "skills_piloting_ability",
    "professionMod"      : "skills_profession_ability",
    "profession2Mod"     : "skills_profession2_ability",
    "sense motiveMod"    : "skills_sense_motive_ability",
    "sleight of handMod" : "skills_sleight_of_hand_ability",
    "stealthMod"         : "skills_stealth_ability",
    "survivalMod"        : "skills_survival_ability",

    "acrobaticsClass"      : "skills_acrobatics_class",
    "athleticsClass"       : "skills_athletics_class",
    "bluffClass"           : "skills_bluff_class",
    "computersClass"       : "skills_computers_class",
    "cultureClass"         : "skills_culture_class",
    "diplomacyClass"       : "skills_diplomacy_class",
    "disguiseClass"        : "skills_disguise_class",
    "engineeringClass"     : "skills_engineering_class",
    "intimidateClass"      : "skills_intimidate_class",
    "life scienceClass"    : "skills_life_science_class",
    "medicineClass"        : "skills_medicine_class",
    "mysticismClass"       : "skills_mysticism_class",
    "perceptionClass"      : "skills_perception_class",
    "physical scienceClass": "skills_physical_science_class",
    "pilotingClass"        : "skills_piloting_class",
    "professionClass"      : "skills_profession_class",
    "profession2Class"     : "skills_profession2_class",
    "sense motiveClass"    : "skills_sense_motive_class",
    "sleight of handClass" : "skills_sleight_of_hand_class",
    "stealthClass"         : "skills_stealth_class",
    "survivalClass"        : "skills_survival_class",

    "acrobaticsMisc"      : "skills_acrobatics_misc",
    "athleticsMisc"       : "skills_athletics_misc",
    "bluffMisc"           : "skills_bluff_misc",
    "computersMisc"       : "skills_computers_misc",
    "cultureMisc"         : "skills_culture_misc",
    "diplomacyMisc"       : "skills_diplomacy_misc",
    "disguiseMisc"        : "skills_disguise_misc",
    "engineeringMisc"     : "skills_engineering_misc",
    "intimidateMisc"      : "skills_intimidate_misc",
    "life scienceMisc"    : "skills_life_science_misc",
    "medicineMisc"        : "skills_medicine_misc",
    "mysticismMisc"       : "skills_mysticism_misc",
    "perceptionMisc"      : "skills_perception_misc",
    "physical scienceMisc": "skills_physical_science_misc",
    "pilotingMisc"        : "skills_piloting_misc",
    "professionMisc"      : "skills_profession_misc",
    "profession2Misc"     : "skills_profession2_misc",
    "sense motiveMisc"    : "skills_sense_motive_misc",
    "sleight of handMisc" : "skills_sleight_of_hand_misc",
    "stealthMisc"         : "skills_stealth_misc",
    "survivalMisc"        : "skills_survival_misc",

    "spendablePoints" : "skills_spendable",
    "perLevelPoints"  : "skills_per_level",

    "raceAbility1" : "c_abilities_51",
    "raceAbility2" : "c_abilities_52",
    "raceAbility3" : "c_abilities_53",
    "raceAbility4" : "c_abilities_54",

    "themeAbility1" : "c_abilities_41",
    "themeAbility2" : "c_abilities_42",
    "themeAbility3" : "c_abilities_43",
    "themeAbility4" : "c_abilities_44",

    "classAbility1" : "c_abilities_01",
    "classAbility2" : "c_abilities_02",
    "classAbility3" : "c_abilities_03",
    "classAbility4" : "c_abilities_04",
    "classAbility5" : "c_abilities_05",
    "classAbility6" : "c_abilities_06",
    "classAbility7" : "c_abilities_07",
    "classAbility8" : "c_abilities_08",
    "classAbility9" : "c_abilities_09",
    "classAbility10" : "c_abilities_10",
    "classAbility11" : "c_abilities_11",
    "classAbility12" : "c_abilities_12",
    "classAbility13" : "c_abilities_13",
    "classAbility14" : "c_abilities_14",
    "classAbility15" : "c_abilities_15",
    "classAbility16" : "c_abilities_16",
    "classAbility17" : "c_abilities_17",
    "classAbility18" : "c_abilities_18",
    "classAbility19" : "c_abilities_19",
    "classAbility20" : "c_abilities_20",
    "classAbility21" : "c_abilities_21",
    "classAbility22" : "c_abilities_22",
    "classAbility23" : "c_abilities_23",
    "classAbility24" : "c_abilities_24",
    "classAbility25" : "c_abilities_25",
    "classAbility26" : "c_abilities_26",
    "classAbility27" : "c_abilities_27",
    "classAbility28" : "c_abilities_28",

    "otherAbility1" : "c_abilities_61",
    "otherAbility2" : "c_abilities_62",
    "otherAbility3" : "c_abilities_63",
    "otherAbility4" : "c_abilities_64",
    "otherAbility5" : "c_abilities_65",
    "otherAbility6" : "c_abilities_66",
    "otherAbility7" : "c_abilities_67",
    "otherAbility8" : "c_abilities_68",
    "otherAbility9" : "c_abilities_69",
    "otherAbility10" : "c_abilities_70",
    "otherAbility11" : "c_abilities_71",
    "otherAbility12" : "c_abilities_72",
    "otherAbility13" : "c_abilities_73",
    "otherAbility14" : "c_abilities_74",
    "otherAbility15" : "c_abilities_75",
    "otherAbility16" : "c_abilities_76",

    "feat1" : "feats_01",
    "feat2" : "feats_02",
    "feat3" : "feats_03",
    "feat4" : "feats_04",
    "feat5" : "feats_05",
    "feat6" : "feats_06",
    "feat7" : "feats_07",
    "feat8" : "feats_08",
    "feat9" : "feats_09",
    "feat10" : "feats_10",
    "feat11" : "feats_11",
    "feat12" : "feats_12",
    "feat13" : "feats_13",
    "feat14" : "feats_14",
    "feat15" : "feats_15",
    "feat16" : "feats_16",
    "feat17" : "feats_17",
    "feat18" : "feats_18",
    "feat19" : "feats_19",
    "feat20" : "feats_20",
    "feat21" : "feats_21",
    "feat22" : "feats_22",
    "feat23" : "feats_23",
    "feat24" : "feats_24",
    "feat25" : "feats_25",
    "feat26" : "feats_26",
    "feat27" : "feats_27",
    "feat28" : "feats_28",

    "spell0known" : "spells_03",
    "spell001"    : "spells_04",
    "spell002"    : "spells_05",
    "spell003"    : "spells_06",
    "spell004"    : "spells_07",
    "spell005"    : "spells_08",
    "spell006"    : "spells_09",
    "spell007"    : "spells_10",
    "spell008"    : "spells_11",
    "spell009"    : "spells_12",
    "spell010"    : "spells_13",
    "spell011"    : "spells_14",
    "spell012"    : "spells_15",
    "spell013"    : "spells_16",
    "spell014"    : "spells_17",

    "spell1known" : "spells_22",
    "spell1day"   : "spells_23",
    "spell101"    : "spells_24",
    "spell102"    : "spells_25",
    "spell103"    : "spells_26",
    "spell104"    : "spells_27",
    "spell105"    : "spells_28",
    "spell106"    : "spells_29",
    "spell107"    : "spells_30",
    "spell108"    : "spells_31",
    "spell109"    : "spells_32",
    "spell110"    : "spells_33",
    "spell111"    : "spells_34",
    "spell112"    : "spells_35",

    "spell2known" : "spells_42",
    "spell2day"   : "spells_43",
    "spell201"    : "spells_44",
    "spell202"    : "spells_45",
    "spell203"    : "spells_46",
    "spell204"    : "spells_47",
    "spell205"    : "spells_48",
    "spell206"    : "spells_49",
    "spell207"    : "spells_50",
    "spell208"    : "spells_51",
    "spell209"    : "spells_52",
    "spell210"    : "spells_53",
    "spell211"    : "spells_54",
    "spell212"    : "spells_55",

    "spell3known" : "spells_62",
    "spell3day"   : "spells_63",
    "spell301"    : "spells_64",
    "spell302"    : "spells_65",
    "spell303"    : "spells_66",
    "spell304"    : "spells_67",
    "spell305"    : "spells_68",
    "spell306"    : "spells_69",
    "spell307"    : "spells_70",
    "spell308"    : "spells_71",
    "spell309"    : "spells_72",
    "spell310"    : "spells_73",
    "spell311"    : "spells_74",
    "spell312"    : "spells_75",

    "spell4known" : "spells_82",
    "spell4day"   : "spells_83",
    "spell401"    : "spells_84",
    "spell402"    : "spells_85",
    "spell403"    : "spells_86",
    "spell404"    : "spells_87",
    "spell405"    : "spells_88",
    "spell406"    : "spells_89",
    "spell407"    : "spells_90",
    "spell408"    : "spells_91",
    "spell409"    : "spells_92",
    "spell410"    : "spells_93",

    "spell5known" : "spells_102",
    "spell5day"   : "spells_103",
    "spell501"    : "spells_104",
    "spell502"    : "spells_105",
    "spell503"    : "spells_106",
    "spell504"    : "spells_107",
    "spell505"    : "spells_108",
    "spell506"    : "spells_109",
    "spell507"    : "spells_110",
    "spell508"    : "spells_111",

    "spell6known" : "spells_122",
    "spell6day"   : "spells_123",
    "spell601"    : "spells_124",
    "spell602"    : "spells_125",
    "spell603"    : "spells_126",
    "spell604"    : "spells_127",
    "spell605"    : "spells_128",
    "spell606"    : "spells_129",
    "spell607"    : "spells_130",
    "spell608"    : "spells_131",
}
