from PyQt5 import QtCore, QtGui, QtWidgets

from helpers.helper import (initialize_combo, initialize_combo_model,
                            initialize_edit, initialize_frame, initialize_text,
                            initialize_widget)


class SpellForm(QtWidgets.QWidget):
    """UI Class to display the character spells

    Args:
        QtWidgets (???): whatever this is
    """
    def __init__(self, character, parent=None):

        QtWidgets.QWidget.__init__(self, parent)
        self.setGeometry(0,0,1045,785)

        self.centralwidget = QtWidgets.QFrame()
        self.centralwidget.resize(821, 635)

        layout=QtWidgets.QVBoxLayout()
        layout.addWidget(self.centralwidget)
        self.setLayout(layout)
        self.setWindowTitle("Character Spells")

        self.character = character

        self.known_spells_text = QtWidgets.QLabel(self.centralwidget)
        self.known_spells_text.setGeometry(QtCore.QRect(210, 10, 77, 29))
        self.known_spells_text.setObjectName("known_spells_text")
        self.known_spells_text.setText("All Known Spells")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 30, 1001, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.level_0_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box3.setPlainText("")
        self.level_0_box3.setObjectName("level_0_box3")
        self.gridLayout.addWidget(self.level_0_box3, 2, 3, 1, 1)
        self.level_0_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box5.setPlainText("")
        self.level_0_box5.setObjectName("level_0_box5")
        self.gridLayout.addWidget(self.level_0_box5, 2, 5, 1, 1)
        self.level_0_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box1.setPlainText("")
        self.level_0_box1.setObjectName("level_0_box1")
        self.gridLayout.addWidget(self.level_0_box1, 2, 0, 1, 2)
        self.level_0_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box2.setPlainText("")
        self.level_0_box2.setObjectName("level_0_box2")
        self.gridLayout.addWidget(self.level_0_box2, 2, 2, 1, 1)
        self.level_0_known_text = QtWidgets.QLabel(self.gridLayoutWidget)
        self.level_0_known_text.setObjectName("level_0_known_text")
        self.level_0_known_text.setText("0 - Level Spells Known")
        self.gridLayout.addWidget(self.level_0_known_text, 1, 0, 1, 1)
        self.level_0_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_0_known_box.sizePolicy().hasHeightForWidth())
        self.level_0_known_box.setSizePolicy(sizePolicy)
        self.level_0_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_0_known_box.setPlainText("")
        self.level_0_known_box.setObjectName("level_0_known_box")
        self.gridLayout.addWidget(self.level_0_known_box, 1, 1, 1, 1)
        self.level_0_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box4.setPlainText("")
        self.level_0_box4.setObjectName("level_0_box4")
        self.gridLayout.addWidget(self.level_0_box4, 2, 4, 1, 1)
        self.level_0_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box6.setPlainText("")
        self.level_0_box6.setObjectName("level_0_box6")
        self.gridLayout.addWidget(self.level_0_box6, 2, 6, 1, 1)
        self.level_0_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box7.setPlainText("")
        self.level_0_box7.setObjectName("level_0_box7")
        self.gridLayout.addWidget(self.level_0_box7, 3, 0, 1, 2)
        self.level_0_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box8.setPlainText("")
        self.level_0_box8.setObjectName("level_0_box8")
        self.gridLayout.addWidget(self.level_0_box8, 3, 2, 1, 1)
        self.level_0_box9 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box9.setPlainText("")
        self.level_0_box9.setObjectName("level_0_box9")
        self.gridLayout.addWidget(self.level_0_box9, 3, 3, 1, 1)
        self.level_0_box10 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box10.setPlainText("")
        self.level_0_box10.setObjectName("level_0_box10")
        self.gridLayout.addWidget(self.level_0_box10, 3, 4, 1, 1)
        self.level_0_box11 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box11.setPlainText("")
        self.level_0_box11.setObjectName("level_0_box11")
        self.gridLayout.addWidget(self.level_0_box11, 3, 5, 1, 1)
        self.level_0_box12 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box12.setPlainText("")
        self.level_0_box12.setObjectName("level_0_box12")
        self.gridLayout.addWidget(self.level_0_box12, 3, 6, 1, 1)
        self.level_0_box13 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box13.setPlainText("")
        self.level_0_box13.setObjectName("level_0_box13")
        self.gridLayout.addWidget(self.level_0_box13, 4, 0, 1, 2)
        self.level_0_box14 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.level_0_box14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_0_box14.setPlainText("")
        self.level_0_box14.setObjectName("level_0_box14")
        self.gridLayout.addWidget(self.level_0_box14, 4, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 150, 1001, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 991, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.level_1_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box2.setPlainText("")
        self.level_1_box2.setObjectName("level_1_box2")
        self.gridLayout_2.addWidget(self.level_1_box2, 2, 2, 1, 2)
        self.level_1_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box1.setPlainText("")
        self.level_1_box1.setObjectName("level_1_box1")
        self.gridLayout_2.addWidget(self.level_1_box1, 2, 0, 1, 2)
        self.level_1_known_text = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.level_1_known_text.setObjectName("level_1_known_text")
        self.level_1_known_text.setText("1st - Level Spells Known")
        self.gridLayout_2.addWidget(self.level_1_known_text, 1, 0, 1, 1)
        self.level_1_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_1_known_box.sizePolicy().hasHeightForWidth())
        self.level_1_known_box.setSizePolicy(sizePolicy)
        self.level_1_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_1_known_box.setPlainText("")
        self.level_1_known_box.setObjectName("level_1_known_box")
        self.gridLayout_2.addWidget(self.level_1_known_box, 1, 1, 1, 1)
        self.level_1_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box4.setPlainText("")
        self.level_1_box4.setObjectName("level_1_box4")
        self.gridLayout_2.addWidget(self.level_1_box4, 2, 5, 1, 1)
        self.level_1_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box5.setPlainText("")
        self.level_1_box5.setObjectName("level_1_box5")
        self.gridLayout_2.addWidget(self.level_1_box5, 2, 6, 1, 1)
        self.level_1_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box3.setPlainText("")
        self.level_1_box3.setObjectName("level_1_box3")
        self.gridLayout_2.addWidget(self.level_1_box3, 2, 4, 1, 1)
        self.level_1_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_1_per_box.sizePolicy().hasHeightForWidth())
        self.level_1_per_box.setSizePolicy(sizePolicy)
        self.level_1_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_1_per_box.setPlainText("")
        self.level_1_per_box.setObjectName("level_1_per_box")
        self.gridLayout_2.addWidget(self.level_1_per_box, 1, 3, 1, 1)
        self.level_1_per_text = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.level_1_per_text.setObjectName("level_1_per_text")
        self.level_1_per_text.setText("1st - Level Spells Known")
        self.gridLayout_2.addWidget(self.level_1_per_text, 1, 2, 1, 1)
        self.level_1_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box6.setPlainText("")
        self.level_1_box6.setObjectName("level_1_box6")
        self.gridLayout_2.addWidget(self.level_1_box6, 2, 7, 1, 1)
        self.level_1_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box7.setPlainText("")
        self.level_1_box7.setObjectName("level_1_box7")
        self.gridLayout_2.addWidget(self.level_1_box7, 3, 0, 1, 2)
        self.level_1_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box8.setPlainText("")
        self.level_1_box8.setObjectName("level_1_box8")
        self.gridLayout_2.addWidget(self.level_1_box8, 3, 2, 1, 2)
        self.level_1_box9 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box9.setPlainText("")
        self.level_1_box9.setObjectName("level_1_box9")
        self.gridLayout_2.addWidget(self.level_1_box9, 3, 4, 1, 1)
        self.level_1_box10 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box10.setPlainText("")
        self.level_1_box10.setObjectName("level_1_box10")
        self.gridLayout_2.addWidget(self.level_1_box10, 3, 5, 1, 1)
        self.level_1_box11 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box11.setPlainText("")
        self.level_1_box11.setObjectName("level_1_box11")
        self.gridLayout_2.addWidget(self.level_1_box11, 3, 6, 1, 1)
        self.level_1_box12 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.level_1_box12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_1_box12.setPlainText("")
        self.level_1_box12.setObjectName("level_1_box12")
        self.gridLayout_2.addWidget(self.level_1_box12, 3, 7, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 250, 1001, 101))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 991, 101))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.level_2_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box2.setPlainText("")
        self.level_2_box2.setObjectName("level_2_box2")
        self.gridLayout_4.addWidget(self.level_2_box2, 2, 2, 1, 2)
        self.level_2_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box1.setPlainText("")
        self.level_2_box1.setObjectName("level_2_box1")
        self.gridLayout_4.addWidget(self.level_2_box1, 2, 0, 1, 2)
        self.level_2_known_text = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.level_2_known_text.setObjectName("level_2_known_text")
        self.level_2_known_text.setText("2nd - Level Spells Known")
        self.gridLayout_4.addWidget(self.level_2_known_text, 1, 0, 1, 1)
        self.level_2_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_2_known_box.sizePolicy().hasHeightForWidth())
        self.level_2_known_box.setSizePolicy(sizePolicy)
        self.level_2_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_2_known_box.setPlainText("")
        self.level_2_known_box.setObjectName("level_2_known_box")
        self.gridLayout_4.addWidget(self.level_2_known_box, 1, 1, 1, 1)
        self.level_2_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box4.setPlainText("")
        self.level_2_box4.setObjectName("level_2_box4")
        self.gridLayout_4.addWidget(self.level_2_box4, 2, 5, 1, 1)
        self.level_2_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box5.setPlainText("")
        self.level_2_box5.setObjectName("level_2_box5")
        self.gridLayout_4.addWidget(self.level_2_box5, 2, 6, 1, 1)
        self.level_2_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box3.setPlainText("")
        self.level_2_box3.setObjectName("level_2_box3")
        self.gridLayout_4.addWidget(self.level_2_box3, 2, 4, 1, 1)
        self.level_2_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_2_per_box.sizePolicy().hasHeightForWidth())
        self.level_2_per_box.setSizePolicy(sizePolicy)
        self.level_2_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_2_per_box.setPlainText("")
        self.level_2_per_box.setObjectName("level_2_per_box")
        self.gridLayout_4.addWidget(self.level_2_per_box, 1, 3, 1, 1)
        self.level_2_per_text = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.level_2_per_text.setObjectName("level_2_per_text")
        self.level_2_per_text.setText("2nd - Level Spells Known")
        self.gridLayout_4.addWidget(self.level_2_per_text, 1, 2, 1, 1)
        self.level_2_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box6.setPlainText("")
        self.level_2_box6.setObjectName("level_2_box6")
        self.gridLayout_4.addWidget(self.level_2_box6, 2, 7, 1, 1)
        self.level_2_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box7.setPlainText("")
        self.level_2_box7.setObjectName("level_2_box7")
        self.gridLayout_4.addWidget(self.level_2_box7, 3, 0, 1, 2)
        self.level_2_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box8.setPlainText("")
        self.level_2_box8.setObjectName("level_2_box8")
        self.gridLayout_4.addWidget(self.level_2_box8, 3, 2, 1, 2)
        self.level_2_box9 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box9.setPlainText("")
        self.level_2_box9.setObjectName("level_2_box9")
        self.gridLayout_4.addWidget(self.level_2_box9, 3, 4, 1, 1)
        self.level_2_box10 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box10.setPlainText("")
        self.level_2_box10.setObjectName("level_2_box10")
        self.gridLayout_4.addWidget(self.level_2_box10, 3, 5, 1, 1)
        self.level_2_box11 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box11.setPlainText("")
        self.level_2_box11.setObjectName("level_2_box11")
        self.gridLayout_4.addWidget(self.level_2_box11, 3, 6, 1, 1)
        self.level_2_box12 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.level_2_box12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_2_box12.setPlainText("")
        self.level_2_box12.setObjectName("level_2_box12")
        self.gridLayout_4.addWidget(self.level_2_box12, 3, 7, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 350, 991, 101))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 991, 101))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.level_3_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box2.setPlainText("")
        self.level_3_box2.setObjectName("level_3_box2")
        self.gridLayout_5.addWidget(self.level_3_box2, 2, 2, 1, 2)
        self.level_3_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box1.setPlainText("")
        self.level_3_box1.setObjectName("level_3_box1")
        self.gridLayout_5.addWidget(self.level_3_box1, 2, 0, 1, 2)
        self.level_3_known_text = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.level_3_known_text.setObjectName("level_3_known_text")
        self.level_3_known_text.setText("3rd - Level Spells Known")
        self.gridLayout_5.addWidget(self.level_3_known_text, 1, 0, 1, 1)
        self.level_3_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_3_known_box.sizePolicy().hasHeightForWidth())
        self.level_3_known_box.setSizePolicy(sizePolicy)
        self.level_3_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_3_known_box.setPlainText("")
        self.level_3_known_box.setObjectName("level_3_known_box")
        self.gridLayout_5.addWidget(self.level_3_known_box, 1, 1, 1, 1)
        self.level_3_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box4.setPlainText("")
        self.level_3_box4.setObjectName("level_3_box4")
        self.gridLayout_5.addWidget(self.level_3_box4, 2, 5, 1, 1)
        self.level_3_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box5.setPlainText("")
        self.level_3_box5.setObjectName("level_3_box5")
        self.gridLayout_5.addWidget(self.level_3_box5, 2, 6, 1, 1)
        self.level_3_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box3.setPlainText("")
        self.level_3_box3.setObjectName("level_3_box3")
        self.gridLayout_5.addWidget(self.level_3_box3, 2, 4, 1, 1)
        self.level_3_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_3_per_box.sizePolicy().hasHeightForWidth())
        self.level_3_per_box.setSizePolicy(sizePolicy)
        self.level_3_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_3_per_box.setPlainText("")
        self.level_3_per_box.setObjectName("level_3_per_box")
        self.gridLayout_5.addWidget(self.level_3_per_box, 1, 3, 1, 1)
        self.level_3_per_text = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.level_3_per_text.setObjectName("level_3_per_text")
        self.level_3_per_text.setText("3rd - Level Spells Known")
        self.gridLayout_5.addWidget(self.level_3_per_text, 1, 2, 1, 1)
        self.level_3_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box6.setPlainText("")
        self.level_3_box6.setObjectName("level_3_box6")
        self.gridLayout_5.addWidget(self.level_3_box6, 2, 7, 1, 1)
        self.level_3_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box7.setPlainText("")
        self.level_3_box7.setObjectName("level_3_box7")
        self.gridLayout_5.addWidget(self.level_3_box7, 3, 0, 1, 2)
        self.level_3_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box8.setPlainText("")
        self.level_3_box8.setObjectName("level_3_box8")
        self.gridLayout_5.addWidget(self.level_3_box8, 3, 2, 1, 2)
        self.level_3_box9 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box9.setPlainText("")
        self.level_3_box9.setObjectName("level_3_box9")
        self.gridLayout_5.addWidget(self.level_3_box9, 3, 4, 1, 1)
        self.level_3_box10 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box10.setPlainText("")
        self.level_3_box10.setObjectName("level_3_box10")
        self.gridLayout_5.addWidget(self.level_3_box10, 3, 5, 1, 1)
        self.level_3_box11 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box11.setPlainText("")
        self.level_3_box11.setObjectName("level_3_box11")
        self.gridLayout_5.addWidget(self.level_3_box11, 3, 6, 1, 1)
        self.level_3_box12 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.level_3_box12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_3_box12.setPlainText("")
        self.level_3_box12.setObjectName("level_3_box12")
        self.gridLayout_5.addWidget(self.level_3_box12, 3, 7, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 450, 991, 101))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 991, 101))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.level_4_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box2.setPlainText("")
        self.level_4_box2.setObjectName("level_4_box2")
        self.gridLayout_6.addWidget(self.level_4_box2, 2, 2, 1, 2)
        self.level_4_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box1.setPlainText("")
        self.level_4_box1.setObjectName("level_4_box1")
        self.gridLayout_6.addWidget(self.level_4_box1, 2, 0, 1, 2)
        self.level_4_known_text = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.level_4_known_text.setObjectName("level_4_known_text")
        self.level_4_known_text.setText("4th - Level Spells Known")
        self.gridLayout_6.addWidget(self.level_4_known_text, 1, 0, 1, 1)
        self.level_4_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_4_known_box.sizePolicy().hasHeightForWidth())
        self.level_4_known_box.setSizePolicy(sizePolicy)
        self.level_4_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_4_known_box.setPlainText("")
        self.level_4_known_box.setObjectName("level_4_known_box")
        self.gridLayout_6.addWidget(self.level_4_known_box, 1, 1, 1, 1)
        self.level_4_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box5.setPlainText("")
        self.level_4_box5.setObjectName("level_4_box5")
        self.gridLayout_6.addWidget(self.level_4_box5, 2, 6, 1, 1)
        self.level_4_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box4.setPlainText("")
        self.level_4_box4.setObjectName("level_4_box4")
        self.gridLayout_6.addWidget(self.level_4_box4, 2, 5, 1, 1)
        self.level_4_per_text = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.level_4_per_text.setObjectName("level_4_per_text")
        self.level_4_per_text.setText("4th - Level Spells Known")
        self.gridLayout_6.addWidget(self.level_4_per_text, 1, 2, 1, 1)
        self.level_4_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_4_per_box.sizePolicy().hasHeightForWidth())
        self.level_4_per_box.setSizePolicy(sizePolicy)
        self.level_4_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_4_per_box.setPlainText("")
        self.level_4_per_box.setObjectName("level_4_per_box")
        self.gridLayout_6.addWidget(self.level_4_per_box, 1, 3, 1, 1)
        self.level_4_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box3.setPlainText("")
        self.level_4_box3.setObjectName("level_4_box3")
        self.gridLayout_6.addWidget(self.level_4_box3, 2, 4, 1, 1)
        self.level_4_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box8.setPlainText("")
        self.level_4_box8.setObjectName("level_4_box8")
        self.gridLayout_6.addWidget(self.level_4_box8, 3, 2, 1, 2)
        self.level_4_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box6.setPlainText("")
        self.level_4_box6.setObjectName("level_4_box6")
        self.gridLayout_6.addWidget(self.level_4_box6, 2, 7, 1, 1)
        self.level_4_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box7.setPlainText("")
        self.level_4_box7.setObjectName("level_4_box7")
        self.gridLayout_6.addWidget(self.level_4_box7, 3, 0, 1, 2)
        self.level_4_box9 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box9.setPlainText("")
        self.level_4_box9.setObjectName("level_4_box9")
        self.gridLayout_6.addWidget(self.level_4_box9, 3, 4, 1, 1)
        self.level_4_box10 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.level_4_box10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_4_box10.setPlainText("")
        self.level_4_box10.setObjectName("level_4_box10")
        self.gridLayout_6.addWidget(self.level_4_box10, 3, 5, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(10, 550, 491, 121))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_6)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 491, 120))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.level_5_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box4.setPlainText("")
        self.level_5_box4.setObjectName("level_5_box4")
        self.gridLayout_7.addWidget(self.level_5_box4, 3, 0, 1, 2)
        self.level_5_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box6.setPlainText("")
        self.level_5_box6.setObjectName("level_5_box6")
        self.gridLayout_7.addWidget(self.level_5_box6, 3, 4, 1, 1)
        self.level_5_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box5.setPlainText("")
        self.level_5_box5.setObjectName("level_5_box5")
        self.gridLayout_7.addWidget(self.level_5_box5, 3, 2, 1, 2)
        self.level_5_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box2.setPlainText("")
        self.level_5_box2.setObjectName("level_5_box2")
        self.gridLayout_7.addWidget(self.level_5_box2, 2, 2, 1, 2)
        self.level_5_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box1.setPlainText("")
        self.level_5_box1.setObjectName("level_5_box1")
        self.gridLayout_7.addWidget(self.level_5_box1, 2, 0, 1, 2)
        self.level_5_known_text = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.level_5_known_text.setObjectName("level_5_known_text")
        self.level_5_known_text.setText("5th - Level Spells Known")
        self.gridLayout_7.addWidget(self.level_5_known_text, 1, 0, 1, 1)
        self.level_5_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_5_known_box.sizePolicy().hasHeightForWidth())
        self.level_5_known_box.setSizePolicy(sizePolicy)
        self.level_5_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_5_known_box.setPlainText("")
        self.level_5_known_box.setObjectName("level_5_known_box")
        self.gridLayout_7.addWidget(self.level_5_known_box, 1, 1, 1, 1)
        self.level_5_per_text = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.level_5_per_text.setObjectName("level_5_per_text")
        self.level_5_per_text.setText("5th - Level Spells Known")
        self.gridLayout_7.addWidget(self.level_5_per_text, 1, 2, 1, 1)
        self.level_5_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box3.setPlainText("")
        self.level_5_box3.setObjectName("level_5_box3")
        self.gridLayout_7.addWidget(self.level_5_box3, 2, 4, 1, 1)
        self.level_5_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_5_per_box.sizePolicy().hasHeightForWidth())
        self.level_5_per_box.setSizePolicy(sizePolicy)
        self.level_5_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_5_per_box.setPlainText("")
        self.level_5_per_box.setObjectName("level_5_per_box")
        self.gridLayout_7.addWidget(self.level_5_per_box, 1, 3, 1, 1)
        self.level_5_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box7.setPlainText("")
        self.level_5_box7.setObjectName("level_5_box7")
        self.gridLayout_7.addWidget(self.level_5_box7, 4, 0, 1, 2)
        self.level_5_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_7)
        self.level_5_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_5_box8.setPlainText("")
        self.level_5_box8.setObjectName("level_5_box8")
        self.gridLayout_7.addWidget(self.level_5_box8, 4, 2, 1, 2)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(510, 550, 491, 121))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.frame_7)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 491, 120))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.level_6_box4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box4.setPlainText("")
        self.level_6_box4.setObjectName("level_6_box4")
        self.gridLayout_9.addWidget(self.level_6_box4, 3, 0, 1, 2)
        self.level_6_box6 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box6.setPlainText("")
        self.level_6_box6.setObjectName("level_6_box6")
        self.gridLayout_9.addWidget(self.level_6_box6, 3, 4, 1, 1)
        self.level_6_box5 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box5.setPlainText("")
        self.level_6_box5.setObjectName("level_6_box5")
        self.gridLayout_9.addWidget(self.level_6_box5, 3, 2, 1, 2)
        self.level_6_box2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box2.setPlainText("")
        self.level_6_box2.setObjectName("level_6_box2")
        self.gridLayout_9.addWidget(self.level_6_box2, 2, 2, 1, 2)
        self.level_6_box1 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box1.setPlainText("")
        self.level_6_box1.setObjectName("level_6_box1")
        self.gridLayout_9.addWidget(self.level_6_box1, 2, 0, 1, 2)
        self.level_6_known_text = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.level_6_known_text.setObjectName("level_6_known_text")
        self.level_6_known_text.setText("6th - Level Spells Known")
        self.gridLayout_9.addWidget(self.level_6_known_text, 1, 0, 1, 1)
        self.level_6_known_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_6_known_box.sizePolicy().hasHeightForWidth())
        self.level_6_known_box.setSizePolicy(sizePolicy)
        self.level_6_known_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_6_known_box.setPlainText("")
        self.level_6_known_box.setObjectName("level_6_known_box")
        self.gridLayout_9.addWidget(self.level_6_known_box, 1, 1, 1, 1)
        self.level_6_per_text = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.level_6_per_text.setObjectName("level_6_per_text")
        self.level_6_per_text.setText("6th - Level Spells Known")
        self.gridLayout_9.addWidget(self.level_6_per_text, 1, 2, 1, 1)
        self.level_6_box3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box3.setPlainText("")
        self.level_6_box3.setObjectName("level_6_box3")
        self.gridLayout_9.addWidget(self.level_6_box3, 2, 4, 1, 1)
        self.level_6_per_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_6_per_box.sizePolicy().hasHeightForWidth())
        self.level_6_per_box.setSizePolicy(sizePolicy)
        self.level_6_per_box.setMaximumSize(QtCore.QSize(25, 25))
        self.level_6_per_box.setPlainText("")
        self.level_6_per_box.setObjectName("level_6_per_box")
        self.gridLayout_9.addWidget(self.level_6_per_box, 1, 3, 1, 1)
        self.level_6_box7 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box7.setPlainText("")
        self.level_6_box7.setObjectName("level_6_box7")
        self.gridLayout_9.addWidget(self.level_6_box7, 4, 0, 1, 2)
        self.level_6_box8 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_8)
        self.level_6_box8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.level_6_box8.setPlainText("")
        self.level_6_box8.setObjectName("level_6_box8")
        self.gridLayout_9.addWidget(self.level_6_box8, 4, 2, 1, 2)

        QtCore.QMetaObject.connectSlotsByName(self.centralwidget)
