from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint
from character import character

class Ui_Form(QtWidgets.QWidget):
    """
    This "window" is a QWidget. If it has no parent, it
    will appear as a free-floating window as we want.
    """
    def __init__(self, character, parent=None):
        QtWidgets.QWidget.__init__(self, parent)

        self.setGeometry(200,200,840,650)

        self.centralwidget = QtWidgets.QFrame()
        self.centralwidget.resize(821, 635)

        layout=QtWidgets.QVBoxLayout()
        layout.addWidget(self.centralwidget)
        self.setLayout(layout)
        self.setWindowTitle("Character Feats")

        self.Skillframe = QtWidgets.QFrame(self.centralwidget)
        self.Skillframe.setGeometry(QtCore.QRect(20, 10, 781, 221))
        self.Skillframe.setFrameShape(QtWidgets.QFrame.Box)
        self.Skillframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Skillframe.setLineWidth(2)
        self.Skillframe.setObjectName("Skillframe")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Skillframe)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 761, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.SkillsScoreGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.SkillsScoreGrid.setContentsMargins(0, 0, 0, 0)
        self.SkillsScoreGrid.setObjectName("SkillsScoreGrid")

        self.ClassAbilityText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ClassAbilityText.setMaximumSize(QtCore.QSize(70, 25))
        self.ClassAbilityText.setObjectName("ClassAbilityText")
        self.ClassAbilityText.setText("Class Abilities")
        self.SkillsScoreGrid.addWidget(self.ClassAbilityText, 0, 0, 1, 1)
        self.Class1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class1.setMaximumSize(QtCore.QSize(184, 20))
        self.Class1.setReadOnly(True)
        self.Class1.setObjectName("Class1")
        self.SkillsScoreGrid.addWidget(self.Class1, 1, 0, 1, 1)
        self.Class2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class2.setMaximumSize(QtCore.QSize(184, 20))
        self.Class2.setReadOnly(True)
        self.Class2.setObjectName("Class2")
        self.SkillsScoreGrid.addWidget(self.Class2, 1, 1, 1, 1)
        self.Class3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class3.setMaximumSize(QtCore.QSize(184, 20))
        self.Class3.setReadOnly(True)
        self.Class3.setObjectName("Class3")
        self.SkillsScoreGrid.addWidget(self.Class3, 1, 2, 1, 1)
        self.Class4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class4.setMaximumSize(QtCore.QSize(184, 20))
        self.Class4.setReadOnly(True)
        self.Class4.setObjectName("Class4")
        self.SkillsScoreGrid.addWidget(self.Class4, 1, 3, 1, 1)
        self.Class5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class5.setMaximumSize(QtCore.QSize(184, 20))
        self.Class5.setReadOnly(True)
        self.Class5.setObjectName("Class5")
        self.SkillsScoreGrid.addWidget(self.Class5, 2, 0, 1, 1)
        self.Class6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class6.setMaximumSize(QtCore.QSize(184, 20))
        self.Class6.setReadOnly(True)
        self.Class6.setObjectName("Class6")
        self.SkillsScoreGrid.addWidget(self.Class6, 2, 1, 1, 1)
        self.Class7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class7.setMaximumSize(QtCore.QSize(184, 20))
        self.Class7.setReadOnly(True)
        self.Class7.setObjectName("Class7")
        self.SkillsScoreGrid.addWidget(self.Class7, 2, 2, 1, 1)
        self.Class8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class8.setMaximumSize(QtCore.QSize(184, 20))
        self.Class8.setReadOnly(True)
        self.Class8.setObjectName("Class8")
        self.SkillsScoreGrid.addWidget(self.Class8, 2, 3, 1, 1)
        self.Class9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class9.setMaximumSize(QtCore.QSize(184, 20))
        self.Class9.setReadOnly(True)
        self.Class9.setObjectName("Class9")
        self.SkillsScoreGrid.addWidget(self.Class9, 3, 0, 1, 1)
        self.Class10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class10.setMaximumSize(QtCore.QSize(184, 20))
        self.Class10.setReadOnly(True)
        self.Class10.setObjectName("Class10")
        self.SkillsScoreGrid.addWidget(self.Class10, 3, 1, 1, 1)
        self.Class11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class11.setMaximumSize(QtCore.QSize(184, 20))
        self.Class11.setReadOnly(True)
        self.Class11.setObjectName("Class11")
        self.SkillsScoreGrid.addWidget(self.Class11, 3, 2, 1, 1)
        self.Class12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class12.setMaximumSize(QtCore.QSize(184, 20))
        self.Class12.setReadOnly(True)
        self.Class12.setObjectName("Class12")
        self.SkillsScoreGrid.addWidget(self.Class12, 3, 3, 1, 1)
        self.Class13 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class13.setMaximumSize(QtCore.QSize(184, 20))
        self.Class13.setReadOnly(True)
        self.Class13.setObjectName("Class13")
        self.SkillsScoreGrid.addWidget(self.Class13, 4, 0, 1, 1)
        self.Class14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class14.setMaximumSize(QtCore.QSize(184, 20))
        self.Class14.setReadOnly(True)
        self.Class14.setObjectName("Class14")
        self.SkillsScoreGrid.addWidget(self.Class14, 4, 1, 1, 1)
        self.Class15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class15.setMaximumSize(QtCore.QSize(184, 20))
        self.Class15.setReadOnly(True)
        self.Class15.setObjectName("Class15")
        self.SkillsScoreGrid.addWidget(self.Class15, 4, 2, 1, 1)
        self.Class16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class16.setMaximumSize(QtCore.QSize(184, 20))
        self.Class16.setReadOnly(True)
        self.Class16.setObjectName("Class16")
        self.SkillsScoreGrid.addWidget(self.Class16, 4, 3, 1, 1)
        self.Class17 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class17.setMaximumSize(QtCore.QSize(184, 20))
        self.Class17.setReadOnly(True)
        self.Class17.setObjectName("Class17")
        self.SkillsScoreGrid.addWidget(self.Class17, 5, 0, 1, 1)
        self.Class18 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class18.setMaximumSize(QtCore.QSize(184, 20))
        self.Class18.setReadOnly(True)
        self.Class18.setObjectName("Class18")
        self.SkillsScoreGrid.addWidget(self.Class18, 5, 1, 1, 1)
        self.Class19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class19.setMaximumSize(QtCore.QSize(184, 20))
        self.Class19.setReadOnly(True)
        self.Class19.setObjectName("Class19")
        self.SkillsScoreGrid.addWidget(self.Class19, 5, 2, 1, 1)
        self.Class20 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class20.setMaximumSize(QtCore.QSize(184, 20))
        self.Class20.setReadOnly(True)
        self.Class20.setObjectName("Class20")
        self.SkillsScoreGrid.addWidget(self.Class20, 5, 3, 1, 1)
        self.Class21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class21.setMaximumSize(QtCore.QSize(184, 20))
        self.Class21.setReadOnly(True)
        self.Class21.setObjectName("Class21")
        self.SkillsScoreGrid.addWidget(self.Class21, 6, 0, 1, 1)
        self.Class22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class22.setMaximumSize(QtCore.QSize(184, 20))
        self.Class22.setReadOnly(True)
        self.Class22.setObjectName("Class22")
        self.SkillsScoreGrid.addWidget(self.Class22, 6, 1, 1, 1)
        self.Class23 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class23.setMaximumSize(QtCore.QSize(184, 20))
        self.Class23.setReadOnly(True)
        self.Class23.setObjectName("Class23")
        self.SkillsScoreGrid.addWidget(self.Class23, 6, 2, 1, 1)
        self.Class24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class24.setMaximumSize(QtCore.QSize(184, 20))
        self.Class24.setReadOnly(True)
        self.Class24.setObjectName("Class24")
        self.SkillsScoreGrid.addWidget(self.Class24, 6, 3, 1, 1)
        self.Class25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class25.setMaximumSize(QtCore.QSize(184, 20))
        self.Class25.setReadOnly(True)
        self.Class25.setObjectName("Class25")
        self.SkillsScoreGrid.addWidget(self.Class25, 7, 0, 1, 1)
        self.Class26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class26.setMaximumSize(QtCore.QSize(184, 20))
        self.Class26.setReadOnly(True)
        self.Class26.setObjectName("Class26")
        self.SkillsScoreGrid.addWidget(self.Class26, 7, 1, 1, 1)
        self.Class27 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class27.setMaximumSize(QtCore.QSize(184, 20))
        self.Class27.setReadOnly(True)
        self.Class27.setObjectName("Class27")
        self.SkillsScoreGrid.addWidget(self.Class27, 7, 2, 1, 1)
        self.Class28 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.Class28.setMaximumSize(QtCore.QSize(184, 20))
        self.Class28.setReadOnly(True)
        self.Class28.setObjectName("Class28")
        self.SkillsScoreGrid.addWidget(self.Class28, 7, 3, 1, 1)

        self.Skillframe_2 = QtWidgets.QFrame(self.centralwidget)
        self.Skillframe_2.setGeometry(QtCore.QRect(20, 240, 781, 71))
        self.Skillframe_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Skillframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Skillframe_2.setLineWidth(2)
        self.Skillframe_2.setObjectName("Skillframe_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Skillframe_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 761, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.SkillsScoreGrid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.SkillsScoreGrid_2.setContentsMargins(0, 0, 0, 0)
        self.SkillsScoreGrid_2.setObjectName("SkillsScoreGrid_2")

        self.ThemeAbilityText = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ThemeAbilityText.setMaximumSize(QtCore.QSize(70, 25))
        self.ThemeAbilityText.setObjectName("ThemeAbilityText")
        self.ThemeAbilityText.setText("Theme Abilities")
        self.SkillsScoreGrid_2.addWidget(self.ThemeAbilityText, 0, 0, 1, 1)
        self.Theme1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.Theme1.setMaximumSize(QtCore.QSize(184, 20))
        self.Theme1.setReadOnly(True)
        self.Theme1.setObjectName("Theme1")
        self.SkillsScoreGrid_2.addWidget(self.Theme1, 1, 0, 1, 1)
        self.Theme2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.Theme2.setMaximumSize(QtCore.QSize(184, 20))
        self.Theme2.setReadOnly(True)
        self.Theme2.setObjectName("Theme2")
        self.SkillsScoreGrid_2.addWidget(self.Theme2, 1, 1, 1, 1)
        self.Theme3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.Theme3.setMaximumSize(QtCore.QSize(184, 20))
        self.Theme3.setReadOnly(True)
        self.Theme3.setObjectName("Theme3")
        self.SkillsScoreGrid_2.addWidget(self.Theme3, 1, 2, 1, 1)
        self.Theme4 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.Theme4.setMaximumSize(QtCore.QSize(184, 20))
        self.Theme4.setReadOnly(True)
        self.Theme4.setObjectName("Theme4")
        self.SkillsScoreGrid_2.addWidget(self.Theme4, 1, 3, 1, 1)

        self.Skillframe_3 = QtWidgets.QFrame(self.centralwidget)
        self.Skillframe_3.setGeometry(QtCore.QRect(20, 320, 781, 71))
        self.Skillframe_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Skillframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Skillframe_3.setLineWidth(2)
        self.Skillframe_3.setObjectName("Skillframe_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Skillframe_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 761, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.SkillsScoreGrid_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.SkillsScoreGrid_4.setContentsMargins(0, 0, 0, 0)
        self.SkillsScoreGrid_4.setObjectName("SkillsScoreGrid_4")

        self.RaceAbilityText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.RaceAbilityText.setMaximumSize(QtCore.QSize(70, 25))
        self.RaceAbilityText.setObjectName("RaceAbilityText")
        self.RaceAbilityText.setText("Race Abilities")
        self.SkillsScoreGrid_4.addWidget(self.RaceAbilityText, 0, 0, 1, 1)
        self.Race1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Race1.setMaximumSize(QtCore.QSize(184, 20))
        self.Race1.setReadOnly(True)
        self.Race1.setObjectName("Race1")
        self.SkillsScoreGrid_4.addWidget(self.Race1, 1, 0, 1, 1)
        self.Race2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Race2.setMaximumSize(QtCore.QSize(184, 20))
        self.Race2.setReadOnly(True)
        self.Race2.setObjectName("Race2")
        self.SkillsScoreGrid_4.addWidget(self.Race2, 1, 1, 1, 1)
        self.Race3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Race3.setMaximumSize(QtCore.QSize(184, 20))
        self.Race3.setReadOnly(True)
        self.Race3.setObjectName("Race3")
        self.SkillsScoreGrid_4.addWidget(self.Race3, 1, 2, 1, 1)
        self.Race4 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.Race4.setMaximumSize(QtCore.QSize(184, 20))
        self.Race4.setReadOnly(True)
        self.Race4.setObjectName("Race4")
        self.SkillsScoreGrid_4.addWidget(self.Race4, 1, 3, 1, 1)

        self.Skillframe_4 = QtWidgets.QFrame(self.centralwidget)
        self.Skillframe_4.setGeometry(QtCore.QRect(20, 400, 781, 221))
        self.Skillframe_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Skillframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Skillframe_4.setLineWidth(2)
        self.Skillframe_4.setObjectName("Skillframe_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.Skillframe_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 761, 201))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.SkillsScoreGrid_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.SkillsScoreGrid_5.setContentsMargins(0, 0, 0, 0)
        self.SkillsScoreGrid_5.setObjectName("SkillsScoreGrid_5")

        self.FeatsText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.FeatsText.setMaximumSize(QtCore.QSize(113, 25))
        self.FeatsText.setObjectName("FeatsText")
        self.FeatsText.setText("Feats and Proficiencies")
        self.SkillsScoreGrid_5.addWidget(self.FeatsText, 0, 0, 1, 1)
        self.Feats1 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats1.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats1.setReadOnly(True)
        self.Feats1.setObjectName("Feats1")
        self.SkillsScoreGrid_5.addWidget(self.Feats1, 1, 0, 1, 1)
        self.Feats2 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats2.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats2.setReadOnly(True)
        self.Feats2.setObjectName("Feats2")
        self.SkillsScoreGrid_5.addWidget(self.Feats2, 1, 1, 1, 1)
        self.Feats3 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats3.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats3.setReadOnly(True)
        self.Feats3.setObjectName("Feats3")
        self.SkillsScoreGrid_5.addWidget(self.Feats3, 1, 2, 1, 1)
        self.Feats4 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats4.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats4.setReadOnly(True)
        self.Feats4.setObjectName("Feats4")
        self.SkillsScoreGrid_5.addWidget(self.Feats4, 1, 3, 1, 1)
        self.Feats5 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats5.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats5.setReadOnly(True)
        self.Feats5.setObjectName("Feats5")
        self.SkillsScoreGrid_5.addWidget(self.Feats5, 2, 0, 1, 1)
        self.Feats6 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats6.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats6.setReadOnly(True)
        self.Feats6.setObjectName("Feats6")
        self.SkillsScoreGrid_5.addWidget(self.Feats6, 2, 1, 1, 1)
        self.Feats7 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats7.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats7.setReadOnly(True)
        self.Feats7.setObjectName("Feats7")
        self.SkillsScoreGrid_5.addWidget(self.Feats7, 2, 2, 1, 1)
        self.Feats8 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats8.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats8.setReadOnly(True)
        self.Feats8.setObjectName("Feats8")
        self.SkillsScoreGrid_5.addWidget(self.Feats8, 2, 3, 1, 1)
        self.Feats9 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats9.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats9.setReadOnly(True)
        self.Feats9.setObjectName("Feats9")
        self.SkillsScoreGrid_5.addWidget(self.Feats9, 3, 0, 1, 1)
        self.Feats10 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats10.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats10.setReadOnly(True)
        self.Feats10.setObjectName("Feats10")
        self.SkillsScoreGrid_5.addWidget(self.Feats10, 3, 1, 1, 1)
        self.Feats11 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats11.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats11.setReadOnly(True)
        self.Feats11.setObjectName("Feats11")
        self.SkillsScoreGrid_5.addWidget(self.Feats11, 3, 2, 1, 1)
        self.Feats12 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats12.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats12.setReadOnly(True)
        self.Feats12.setObjectName("Feats12")
        self.SkillsScoreGrid_5.addWidget(self.Feats12, 3, 3, 1, 1)
        self.Feats13 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats13.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats13.setReadOnly(True)
        self.Feats13.setObjectName("Feats13")
        self.SkillsScoreGrid_5.addWidget(self.Feats13, 4, 0, 1, 1)
        self.Feats14 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats14.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats14.setReadOnly(True)
        self.Feats14.setObjectName("Feats14")
        self.SkillsScoreGrid_5.addWidget(self.Feats14, 4, 1, 1, 1)
        self.Feats15 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats15.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats15.setReadOnly(True)
        self.Feats15.setObjectName("Feats15")
        self.SkillsScoreGrid_5.addWidget(self.Feats15, 4, 2, 1, 1)
        self.Feats16 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats16.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats16.setReadOnly(True)
        self.Feats16.setObjectName("Feats16")
        self.SkillsScoreGrid_5.addWidget(self.Feats16, 4, 3, 1, 1)
        self.Feats17 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats17.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats17.setReadOnly(True)
        self.Feats17.setObjectName("Feats17")
        self.SkillsScoreGrid_5.addWidget(self.Feats17, 5, 0, 1, 1)
        self.Feats18 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats18.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats18.setReadOnly(True)
        self.Feats18.setObjectName("Feats18")
        self.SkillsScoreGrid_5.addWidget(self.Feats18, 5, 1, 1, 1)
        self.Feats19 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats19.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats19.setReadOnly(True)
        self.Feats19.setObjectName("Feats19")
        self.SkillsScoreGrid_5.addWidget(self.Feats19, 5, 2, 1, 1)
        self.Feats20 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats20.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats20.setReadOnly(True)
        self.Feats20.setObjectName("Feats20")
        self.SkillsScoreGrid_5.addWidget(self.Feats20, 5, 3, 1, 1)
        self.Feats21 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats21.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats21.setReadOnly(True)
        self.Feats21.setObjectName("Feats21")
        self.SkillsScoreGrid_5.addWidget(self.Feats21, 6, 0, 1, 1)
        self.Feats22 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats22.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats22.setReadOnly(True)
        self.Feats22.setObjectName("Feats22")
        self.SkillsScoreGrid_5.addWidget(self.Feats22, 6, 1, 1, 1)
        self.Feats23 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats23.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats23.setReadOnly(True)
        self.Feats23.setObjectName("Feats23")
        self.SkillsScoreGrid_5.addWidget(self.Feats23, 6, 2, 1, 1)
        self.Feats24 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats24.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats24.setReadOnly(True)
        self.Feats24.setObjectName("Feats24")
        self.SkillsScoreGrid_5.addWidget(self.Feats24, 6, 3, 1, 1)
        self.Feats25 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats25.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats25.setReadOnly(True)
        self.Feats25.setObjectName("Feats25")
        self.SkillsScoreGrid_5.addWidget(self.Feats25, 7, 0, 1, 1)
        self.Feats26 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats26.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats26.setReadOnly(True)
        self.Feats26.setObjectName("Feats26")
        self.SkillsScoreGrid_5.addWidget(self.Feats26, 7, 1, 1, 1)
        self.Feats27 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats27.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats27.setReadOnly(True)
        self.Feats27.setObjectName("Feats27")
        self.SkillsScoreGrid_5.addWidget(self.Feats27, 7, 2, 1, 1)
        self.Feats28 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.Feats28.setMaximumSize(QtCore.QSize(184, 20))
        self.Feats28.setReadOnly(True)
        self.Feats28.setObjectName("Feats28")
        self.SkillsScoreGrid_5.addWidget(self.Feats28, 7, 3, 1, 1)

        # self.retranslateUi(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(self.centralwidget)


    def UpdateClasses(self):
        pass
