# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starfinder.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class ComboBox(QtWidgets.QComboBox):
    # https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/widgets/qcombobox.cpp?h=5.15.2#n3173
    def paintEvent(self, event):

        painter = QtWidgets.QStylePainter(self)
        painter.setPen(self.palette().color(QtGui.QPalette.Text))

        # draw the combobox frame, focusrect and selected etc.
        opt = QtWidgets.QStyleOptionComboBox()
        self.initStyleOption(opt)
        painter.drawComplexControl(QtWidgets.QStyle.CC_ComboBox, opt)

        if self.currentIndex() < 0:
            opt.palette.setBrush(
                QtGui.QPalette.ButtonText,
                opt.palette.brush(QtGui.QPalette.ButtonText).color().lighter(),
            )
            if self.placeholderText():
                opt.currentText = self.placeholderText()

        # draw the icon and text
        painter.drawControl(QtWidgets.QStyle.CE_ComboBoxLabel, opt)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 901)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(490, 0, 418, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.AbilityScoreGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.AbilityScoreGrid.setContentsMargins(0, 0, 0, 0)
        self.AbilityScoreGrid.setObjectName("AbilityScoreGrid")
        self.DexScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexScore.setMaximumSize(QtCore.QSize(50, 25))
        self.DexScore.setReadOnly(True)
        self.DexScore.setObjectName("DexScore")
        self.AbilityScoreGrid.addWidget(self.DexScore, 2, 1, 1, 1)
        self.WisScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisScore.setMaximumSize(QtCore.QSize(50, 25))
        self.WisScore.setReadOnly(True)
        self.WisScore.setObjectName("WisScore")
        self.AbilityScoreGrid.addWidget(self.WisScore, 5, 1, 1, 1)
        self.ConScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConScore.setMaximumSize(QtCore.QSize(50, 25))
        self.ConScore.setReadOnly(True)
        self.ConScore.setObjectName("ConScore")
        self.AbilityScoreGrid.addWidget(self.ConScore, 3, 1, 1, 1)
        self.IntScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntScore.setMaximumSize(QtCore.QSize(50, 25))
        self.IntScore.setReadOnly(True)
        self.IntScore.setObjectName("IntScore")
        self.AbilityScoreGrid.addWidget(self.IntScore, 4, 1, 1, 1)
        self.ChaScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaScore.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaScore.setReadOnly(True)
        self.ChaScore.setObjectName("ChaScore")
        self.AbilityScoreGrid.addWidget(self.ChaScore, 6, 1, 1, 1)
        self.StrMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrMod.setMaximumSize(QtCore.QSize(50, 25))
        self.StrMod.setReadOnly(True)
        self.StrMod.setObjectName("StrMod")
        self.AbilityScoreGrid.addWidget(self.StrMod, 1, 2, 1, 1)
        self.StrScore = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrScore.setMaximumSize(QtCore.QSize(50, 25))
        self.StrScore.setReadOnly(True)
        self.StrScore.setObjectName("StrScore")
        self.AbilityScoreGrid.addWidget(self.StrScore, 1, 1, 1, 1)
        self.IntText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.IntText.setMaximumSize(QtCore.QSize(20, 20))
        self.IntText.setObjectName("IntText")
        self.IntText.setText("Int")
        self.AbilityScoreGrid.addWidget(self.IntText, 4, 0, 1, 1)
        self.ConText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ConText.setMaximumSize(QtCore.QSize(20, 20))
        self.ConText.setObjectName("ConText")
        self.ConText.setText("Con")
        self.AbilityScoreGrid.addWidget(self.ConText, 3, 0, 1, 1)
        self.StrText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.StrText.setMaximumSize(QtCore.QSize(20, 20))
        self.StrText.setObjectName("StrText")
        self.StrText.setText("Str")
        self.AbilityScoreGrid.addWidget(self.StrText, 1, 0, 1, 1)
        self.DexText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.DexText.setMaximumSize(QtCore.QSize(20, 20))
        self.DexText.setObjectName("DexText")
        self.DexText.setText("Dex")
        self.AbilityScoreGrid.addWidget(self.DexText, 2, 0, 1, 1)
        self.ChaText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ChaText.setMaximumSize(QtCore.QSize(20, 20))
        self.ChaText.setObjectName("ChaText")
        self.ChaText.setText("Cha")
        self.AbilityScoreGrid.addWidget(self.ChaText, 6, 0, 1, 1)
        self.RacePointText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RacePointText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RacePointText.setObjectName("RacePointText")
        self.RacePointText.setText("Race Points")
        self.AbilityScoreGrid.addWidget(self.RacePointText, 0, 3, 1, 1)
        self.ModifierText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ModifierText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ModifierText.setObjectName("ModifierText")
        self.ModifierText.setText("Modifier")
        self.AbilityScoreGrid.addWidget(self.ModifierText, 0, 2, 1, 1)
        self.ThemePointText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ThemePointText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ThemePointText.setObjectName("ThemePointText")
        self.ThemePointText.setText("Theme Points")
        self.AbilityScoreGrid.addWidget(self.ThemePointText, 0, 4, 1, 1)
        self.StrIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.StrIncrease.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StrIncrease.setObjectName("StrIncrease")
        self.AbilityScoreGrid.addWidget(self.StrIncrease, 1, 6, 1, 1)
        self.ScoreText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ScoreText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ScoreText.setObjectName("ScoreText")
        self.ScoreText.setText("Score")
        self.AbilityScoreGrid.addWidget(self.ScoreText, 0, 1, 1, 1)
        self.WisText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.WisText.setMaximumSize(QtCore.QSize(20, 20))
        self.WisText.setObjectName("WisText")
        self.WisText.setText("Wis")
        self.AbilityScoreGrid.addWidget(self.WisText, 5, 0, 1, 1)
        self.StrTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.StrTheme.setReadOnly(True)
        self.StrTheme.setObjectName("StrTheme")
        self.AbilityScoreGrid.addWidget(self.StrTheme, 1, 4, 1, 1)
        self.StrBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.StrBuy.setObjectName("StrBuy")
        self.AbilityScoreGrid.addWidget(self.StrBuy, 1, 5, 1, 1)
        self.StrRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.StrRace.setMaximumSize(QtCore.QSize(50, 25))
        self.StrRace.setReadOnly(True)
        self.StrRace.setObjectName("StrRace")
        self.AbilityScoreGrid.addWidget(self.StrRace, 1, 3, 1, 1)
        self.PointBuyText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PointBuyText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.PointBuyText.setObjectName("PointBuyText")
        self.PointBuyText.setText("Point Buy")
        self.AbilityScoreGrid.addWidget(self.PointBuyText, 0, 5, 1, 1)
        self.AbilityIncreasesText = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AbilityIncreasesText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.AbilityIncreasesText.setObjectName("AbilityIncreasesText")
        self.AbilityIncreasesText.setText("Ability increases")
        self.AbilityScoreGrid.addWidget(self.AbilityIncreasesText, 0, 6, 1, 1)
        self.DexMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexMod.setMaximumSize(QtCore.QSize(50, 25))
        self.DexMod.setReadOnly(True)
        self.DexMod.setObjectName("DexMod")
        self.AbilityScoreGrid.addWidget(self.DexMod, 2, 2, 1, 1)
        self.DexTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.DexTheme.setReadOnly(True)
        self.DexTheme.setObjectName("DexTheme")
        self.AbilityScoreGrid.addWidget(self.DexTheme, 2, 4, 1, 1)
        self.DexBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.DexBuy.setObjectName("DexBuy")
        self.AbilityScoreGrid.addWidget(self.DexBuy, 2, 5, 1, 1)
        self.DexIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.DexIncrease.setObjectName("DexIncrease")
        self.AbilityScoreGrid.addWidget(self.DexIncrease, 2, 6, 1, 1)
        self.DexRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.DexRace.setMaximumSize(QtCore.QSize(50, 25))
        self.DexRace.setReadOnly(True)
        self.DexRace.setObjectName("DexRace")
        self.AbilityScoreGrid.addWidget(self.DexRace, 2, 3, 1, 1)
        self.ConMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConMod.setMaximumSize(QtCore.QSize(50, 25))
        self.ConMod.setReadOnly(True)
        self.ConMod.setObjectName("ConMod")
        self.AbilityScoreGrid.addWidget(self.ConMod, 3, 2, 1, 1)
        self.ConRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConRace.setMaximumSize(QtCore.QSize(50, 25))
        self.ConRace.setReadOnly(True)
        self.ConRace.setObjectName("ConRace")
        self.AbilityScoreGrid.addWidget(self.ConRace, 3, 3, 1, 1)
        self.ConTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.ConTheme.setReadOnly(True)
        self.ConTheme.setObjectName("ConTheme")
        self.AbilityScoreGrid.addWidget(self.ConTheme, 3, 4, 1, 1)
        self.ConBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.ConBuy.setObjectName("ConBuy")
        self.AbilityScoreGrid.addWidget(self.ConBuy, 3, 5, 1, 1)
        self.ConIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ConIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.ConIncrease.setObjectName("ConIncrease")
        self.AbilityScoreGrid.addWidget(self.ConIncrease, 3, 6, 1, 1)
        self.IntMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntMod.setMaximumSize(QtCore.QSize(50, 25))
        self.IntMod.setReadOnly(True)
        self.IntMod.setObjectName("IntMod")
        self.AbilityScoreGrid.addWidget(self.IntMod, 4, 2, 1, 1)
        self.IntRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntRace.setMaximumSize(QtCore.QSize(50, 25))
        self.IntRace.setReadOnly(True)
        self.IntRace.setObjectName("IntRace")
        self.AbilityScoreGrid.addWidget(self.IntRace, 4, 3, 1, 1)
        self.IntTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.IntTheme.setReadOnly(True)
        self.IntTheme.setObjectName("IntTheme")
        self.AbilityScoreGrid.addWidget(self.IntTheme, 4, 4, 1, 1)
        self.IntBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.IntBuy.setObjectName("IntBuy")
        self.AbilityScoreGrid.addWidget(self.IntBuy, 4, 5, 1, 1)
        self.IntIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.IntIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.IntIncrease.setObjectName("IntIncrease")
        self.AbilityScoreGrid.addWidget(self.IntIncrease, 4, 6, 1, 1)
        self.WisMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisMod.setMaximumSize(QtCore.QSize(50, 25))
        self.WisMod.setReadOnly(True)
        self.WisMod.setObjectName("WisMod")
        self.AbilityScoreGrid.addWidget(self.WisMod, 5, 2, 1, 1)
        self.WisRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisRace.setMaximumSize(QtCore.QSize(50, 25))
        self.WisRace.setReadOnly(True)
        self.WisRace.setObjectName("WisRace")
        self.AbilityScoreGrid.addWidget(self.WisRace, 5, 3, 1, 1)
        self.WisTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.WisTheme.setReadOnly(True)
        self.WisTheme.setObjectName("WisTheme")
        self.AbilityScoreGrid.addWidget(self.WisTheme, 5, 4, 1, 1)
        self.WisBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.WisBuy.setObjectName("WisBuy")
        self.AbilityScoreGrid.addWidget(self.WisBuy, 5, 5, 1, 1)
        self.WisIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.WisIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.WisIncrease.setObjectName("WisIncrease")
        self.AbilityScoreGrid.addWidget(self.WisIncrease, 5, 6, 1, 1)
        self.ChaMod = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaMod.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaMod.setReadOnly(True)
        self.ChaMod.setObjectName("ChaMod")
        self.AbilityScoreGrid.addWidget(self.ChaMod, 6, 2, 1, 1)
        self.ChaRace = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaRace.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaRace.setReadOnly(True)
        self.ChaRace.setObjectName("ChaRace")
        self.AbilityScoreGrid.addWidget(self.ChaRace, 6, 3, 1, 1)
        self.ChaTheme = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaTheme.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaTheme.setReadOnly(True)
        self.ChaTheme.setObjectName("ChaTheme")
        self.AbilityScoreGrid.addWidget(self.ChaTheme, 6, 4, 1, 1)
        self.ChaBuy = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaBuy.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaBuy.setObjectName("ChaBuy")
        self.AbilityScoreGrid.addWidget(self.ChaBuy, 6, 5, 1, 1)
        self.ChaIncrease = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ChaIncrease.setMaximumSize(QtCore.QSize(50, 25))
        self.ChaIncrease.setObjectName("ChaIncrease")
        self.AbilityScoreGrid.addWidget(self.ChaIncrease, 6, 6, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 270, 472, 581))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.SkillsScoreGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.SkillsScoreGrid.setContentsMargins(0, 0, 0, 0)
        self.SkillsScoreGrid.setObjectName("SkillsScoreGrid")
        self.SkillRanksText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SkillRanksText.setObjectName("SkillRanksText")
        self.SkillRanksText.setText("Ranks")
        self.SkillsScoreGrid.addWidget(self.SkillRanksText, 0, 2, 1, 1)
        self.SurvivalText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SurvivalText.setObjectName("SurvivalText")
        self.SurvivalText.setText("Survival (Wis)")
        self.SkillsScoreGrid.addWidget(self.SurvivalText, 18, 0, 1, 1)
        self.SkillClassText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SkillClassText.setObjectName("SkillClassText")
        self.SkillClassText.setText("Class Bonus")
        self.SkillsScoreGrid.addWidget(self.SkillClassText, 0, 3, 1, 1)
        self.SkillTotalText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SkillTotalText.setObjectName("SkillTotalText")
        self.SkillTotalText.setText("Total")
        self.SkillsScoreGrid.addWidget(self.SkillTotalText, 0, 1, 1, 1)
        self.DisguiseText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.DisguiseText.setObjectName("DisguiseText")
        self.DisguiseText.setText("Disguise (Cha)")
        self.SkillsScoreGrid.addWidget(self.DisguiseText, 7, 0, 1, 1)
        self.SlightText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SlightText.setObjectName("SlightText")
        self.SlightText.setText("Slight of Hand (Dex)")
        self.SkillsScoreGrid.addWidget(self.SlightText, 16, 0, 1, 1)
        self.StealthText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.StealthText.setObjectName("StealthText")
        self.StealthText.setText("Stealth (Dex)")
        self.SkillsScoreGrid.addWidget(self.StealthText, 17, 0, 1, 1)
        self.LifeText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LifeText.setObjectName("LifeText")
        self.LifeText.setText("Life Science (Int)")
        self.SkillsScoreGrid.addWidget(self.LifeText, 8, 0, 1, 1)
        self.AcrobaticsText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.AcrobaticsText.setObjectName("AcrobaticsText")
        self.AcrobaticsText.setText("Acrobatics (Dex)")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsText, 1, 0, 1, 1)
        self.CultureText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CultureText.setObjectName("CultureText")
        self.CultureText.setText("Culture (Int)")
        self.SkillsScoreGrid.addWidget(self.CultureText, 5, 0, 1, 1)
        self.BluffText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.BluffText.setObjectName("BluffText")
        self.BluffText.setText("Bluff (Cha)")
        self.SkillsScoreGrid.addWidget(self.BluffText, 3, 0, 1, 1)
        self.AthleticsText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.AthleticsText.setObjectName("AthleticsText")
        self.AthleticsText.setText("Athletics (Str)")
        self.SkillsScoreGrid.addWidget(self.AthleticsText, 2, 0, 1, 1)
        self.ComputersText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ComputersText.setObjectName("ComputersText")
        self.ComputersText.setText("Computers (Int)")
        self.SkillsScoreGrid.addWidget(self.ComputersText, 4, 0, 1, 1)
        self.DiplomacyText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.DiplomacyText.setObjectName("DiplomacyText")
        self.DiplomacyText.setText("Diplomacy (Cha)")
        self.SkillsScoreGrid.addWidget(self.DiplomacyText, 6, 0, 1, 1)
        self.SenseText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SenseText.setObjectName("SenseText")
        self.SenseText.setText("Sense Motive (Wis)")
        self.SkillsScoreGrid.addWidget(self.SenseText, 15, 0, 1, 1)
        self.MysticismText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.MysticismText.setObjectName("MysticismText")
        self.MysticismText.setText("Mysticism (Wis)")
        self.SkillsScoreGrid.addWidget(self.MysticismText, 10, 0, 1, 1)
        self.MedicineText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.MedicineText.setObjectName("MedicineText")
        self.MedicineText.setText("Medicine (Int)")
        self.SkillsScoreGrid.addWidget(self.MedicineText, 9, 0, 1, 1)
        self.PerceptionText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PerceptionText.setObjectName("PerceptionText")
        self.PerceptionText.setText("Perception (Wis)")
        self.SkillsScoreGrid.addWidget(self.PerceptionText, 11, 0, 1, 1)
        self.PhysicalText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PhysicalText.setObjectName("PhysicalText")
        self.PhysicalText.setText("Physical Science (Int)")
        self.SkillsScoreGrid.addWidget(self.PhysicalText, 12, 0, 1, 1)
        self.AcrobaticsTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AcrobaticsTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.AcrobaticsTotal.setReadOnly(True)
        self.AcrobaticsTotal.setObjectName("AcrobaticsTotal")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsTotal, 1, 1, 1, 1)
        self.AcrobaticsRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AcrobaticsRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.AcrobaticsRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AcrobaticsRanks.setObjectName("AcrobaticsRanks")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsRanks, 1, 2, 1, 1)
        self.AcrobaticsClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AcrobaticsClass.setMaximumSize(QtCore.QSize(50, 25))
        self.AcrobaticsClass.setReadOnly(True)
        self.AcrobaticsClass.setObjectName("AcrobaticsClass")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsClass, 1, 3, 1, 1)
        self.AcrobaticsMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AcrobaticsMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.AcrobaticsMisc.setReadOnly(True)
        self.AcrobaticsMisc.setObjectName("AcrobaticsMisc")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsMisc, 1, 5, 1, 1)
        self.AcrobaticsAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AcrobaticsAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.AcrobaticsAbility.setObjectName("AcrobaticsAbility")
        self.SkillsScoreGrid.addWidget(self.AcrobaticsAbility, 1, 4, 1, 1)
        self.SkillMiscText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SkillMiscText.setObjectName("SkillMiscText")
        self.SkillMiscText.setText("Misc Mod")
        self.SkillsScoreGrid.addWidget(self.SkillMiscText, 0, 5, 1, 1)
        self.ProfessionText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ProfessionText.setObjectName("ProfessionText")
        self.ProfessionText.setText("Profession (Cha, Int, Wis)")
        self.SkillsScoreGrid.addWidget(self.ProfessionText, 13, 0, 1, 1)
        self.Profession2Text = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Profession2Text.setObjectName("Profession2Text")
        self.Profession2Text.setText("Profession (Cha, Int, Wis)")
        self.SkillsScoreGrid.addWidget(self.Profession2Text, 14, 0, 1, 1)
        self.SkillAbilityText = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SkillAbilityText.setObjectName("SkillAbilityText")
        self.SkillAbilityText.setText("Ability Mod")
        self.SkillsScoreGrid.addWidget(self.SkillAbilityText, 0, 4, 1, 1)
        self.AthleticsTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AthleticsTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.AthleticsTotal.setReadOnly(True)
        self.AthleticsTotal.setObjectName("AthleticsTotal")
        self.SkillsScoreGrid.addWidget(self.AthleticsTotal, 2, 1, 1, 1)
        self.AthleticsRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AthleticsRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.AthleticsRanks.setReadOnly(True)
        self.AthleticsRanks.setObjectName("AthleticsRanks")
        self.SkillsScoreGrid.addWidget(self.AthleticsRanks, 2, 2, 1, 1)
        self.AthleticsClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AthleticsClass.setMaximumSize(QtCore.QSize(50, 25))
        self.AthleticsClass.setReadOnly(True)
        self.AthleticsClass.setObjectName("AthleticsClass")
        self.SkillsScoreGrid.addWidget(self.AthleticsClass, 2, 3, 1, 1)
        self.AthleticsAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AthleticsAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.AthleticsAbility.setObjectName("AthleticsAbility")
        self.SkillsScoreGrid.addWidget(self.AthleticsAbility, 2, 4, 1, 1)
        self.AthleticsMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.AthleticsMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.AthleticsMisc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AthleticsMisc.setObjectName("AthleticsMisc")
        self.SkillsScoreGrid.addWidget(self.AthleticsMisc, 2, 5, 1, 1)
        self.BluffTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.BluffTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.BluffTotal.setReadOnly(True)
        self.BluffTotal.setObjectName("BluffTotal")
        self.SkillsScoreGrid.addWidget(self.BluffTotal, 3, 1, 1, 1)
        self.BluffRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.BluffRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.BluffRanks.setReadOnly(True)
        self.BluffRanks.setObjectName("BluffRanks")
        self.SkillsScoreGrid.addWidget(self.BluffRanks, 3, 2, 1, 1)
        self.BluffClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.BluffClass.setMaximumSize(QtCore.QSize(50, 25))
        self.BluffClass.setObjectName("BluffClass")
        self.SkillsScoreGrid.addWidget(self.BluffClass, 3, 3, 1, 1)
        self.BluffAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.BluffAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.BluffAbility.setReadOnly(True)
        self.BluffAbility.setObjectName("BluffAbility")
        self.SkillsScoreGrid.addWidget(self.BluffAbility, 3, 4, 1, 1)
        self.BluffMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.BluffMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.BluffMisc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BluffMisc.setObjectName("BluffMisc")
        self.SkillsScoreGrid.addWidget(self.BluffMisc, 3, 5, 1, 1)
        self.ComputersTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ComputersTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.ComputersTotal.setReadOnly(True)
        self.ComputersTotal.setObjectName("ComputersTotal")
        self.SkillsScoreGrid.addWidget(self.ComputersTotal, 4, 1, 1, 1)
        self.ComputersRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ComputersRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.ComputersRanks.setReadOnly(True)
        self.ComputersRanks.setObjectName("ComputersRanks")
        self.SkillsScoreGrid.addWidget(self.ComputersRanks, 4, 2, 1, 1)
        self.ComputersClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ComputersClass.setMaximumSize(QtCore.QSize(50, 25))
        self.ComputersClass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ComputersClass.setObjectName("ComputersClass")
        self.SkillsScoreGrid.addWidget(self.ComputersClass, 4, 3, 1, 1)
        self.ComputersAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ComputersAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.ComputersAbility.setObjectName("ComputersAbility")
        self.SkillsScoreGrid.addWidget(self.ComputersAbility, 4, 4, 1, 1)
        self.ComputersMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ComputersMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.ComputersMisc.setReadOnly(True)
        self.ComputersMisc.setObjectName("ComputersMisc")
        self.SkillsScoreGrid.addWidget(self.ComputersMisc, 4, 5, 1, 1)
        self.CultureTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.CultureTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.CultureTotal.setReadOnly(True)
        self.CultureTotal.setObjectName("CultureTotal")
        self.SkillsScoreGrid.addWidget(self.CultureTotal, 5, 1, 1, 1)
        self.CultureRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.CultureRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.CultureRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CultureRanks.setObjectName("CultureRanks")
        self.SkillsScoreGrid.addWidget(self.CultureRanks, 5, 2, 1, 1)
        self.CultureClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.CultureClass.setMaximumSize(QtCore.QSize(50, 25))
        self.CultureClass.setReadOnly(True)
        self.CultureClass.setObjectName("CultureClass")
        self.SkillsScoreGrid.addWidget(self.CultureClass, 5, 3, 1, 1)
        self.CultureAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.CultureAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.CultureAbility.setObjectName("CultureAbility")
        self.SkillsScoreGrid.addWidget(self.CultureAbility, 5, 4, 1, 1)
        self.CultureMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.CultureMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.CultureMisc.setReadOnly(True)
        self.CultureMisc.setObjectName("CultureMisc")
        self.SkillsScoreGrid.addWidget(self.CultureMisc, 5, 5, 1, 1)
        self.DiplomacyTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DiplomacyTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.DiplomacyTotal.setReadOnly(True)
        self.DiplomacyTotal.setObjectName("DiplomacyTotal")
        self.SkillsScoreGrid.addWidget(self.DiplomacyTotal, 6, 1, 1, 1)
        self.DiplomacyRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DiplomacyRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.DiplomacyRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DiplomacyRanks.setObjectName("DiplomacyRanks")
        self.SkillsScoreGrid.addWidget(self.DiplomacyRanks, 6, 2, 1, 1)
        self.DiplomacyClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DiplomacyClass.setMaximumSize(QtCore.QSize(50, 25))
        self.DiplomacyClass.setReadOnly(True)
        self.DiplomacyClass.setObjectName("DiplomacyClass")
        self.SkillsScoreGrid.addWidget(self.DiplomacyClass, 6, 3, 1, 1)
        self.DiplomacyAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DiplomacyAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.DiplomacyAbility.setObjectName("DiplomacyAbility")
        self.SkillsScoreGrid.addWidget(self.DiplomacyAbility, 6, 4, 1, 1)
        self.DiplomacyMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DiplomacyMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.DiplomacyMisc.setReadOnly(True)
        self.DiplomacyMisc.setObjectName("DiplomacyMisc")
        self.SkillsScoreGrid.addWidget(self.DiplomacyMisc, 6, 5, 1, 1)
        self.DisguiseTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DisguiseTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.DisguiseTotal.setReadOnly(True)
        self.DisguiseTotal.setObjectName("DisguiseTotal")
        self.SkillsScoreGrid.addWidget(self.DisguiseTotal, 7, 1, 1, 1)
        self.DisguiseRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DisguiseRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.DisguiseRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DisguiseRanks.setObjectName("DisguiseRanks")
        self.SkillsScoreGrid.addWidget(self.DisguiseRanks, 7, 2, 1, 1)
        self.DisguiseClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DisguiseClass.setMaximumSize(QtCore.QSize(50, 25))
        self.DisguiseClass.setObjectName("DisguiseClass")
        self.SkillsScoreGrid.addWidget(self.DisguiseClass, 7, 3, 1, 1)
        self.DisguiseAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DisguiseAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.DisguiseAbility.setReadOnly(True)
        self.DisguiseAbility.setObjectName("DisguiseAbility")
        self.SkillsScoreGrid.addWidget(self.DisguiseAbility, 7, 4, 1, 1)
        self.DisguiseMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.DisguiseMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.DisguiseMisc.setReadOnly(True)
        self.DisguiseMisc.setObjectName("DisguiseMisc")
        self.SkillsScoreGrid.addWidget(self.DisguiseMisc, 7, 5, 1, 1)
        self.LifeTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.LifeTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.LifeTotal.setReadOnly(True)
        self.LifeTotal.setObjectName("LifeTotal")
        self.SkillsScoreGrid.addWidget(self.LifeTotal, 8, 1, 1, 1)
        self.LifeRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.LifeRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.LifeRanks.setObjectName("LifeRanks")
        self.SkillsScoreGrid.addWidget(self.LifeRanks, 8, 2, 1, 1)
        self.LifeClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.LifeClass.setMaximumSize(QtCore.QSize(50, 25))
        self.LifeClass.setReadOnly(True)
        self.LifeClass.setObjectName("LifeClass")
        self.SkillsScoreGrid.addWidget(self.LifeClass, 8, 3, 1, 1)
        self.LifeAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.LifeAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.LifeAbility.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LifeAbility.setObjectName("LifeAbility")
        self.SkillsScoreGrid.addWidget(self.LifeAbility, 8, 4, 1, 1)
        self.LifeMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.LifeMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.LifeMisc.setReadOnly(True)
        self.LifeMisc.setObjectName("LifeMisc")
        self.SkillsScoreGrid.addWidget(self.LifeMisc, 8, 5, 1, 1)
        self.MedicineTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MedicineTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.MedicineTotal.setReadOnly(True)
        self.MedicineTotal.setObjectName("MedicineTotal")
        self.SkillsScoreGrid.addWidget(self.MedicineTotal, 9, 1, 1, 1)
        self.MedicineRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MedicineRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.MedicineRanks.setReadOnly(True)
        self.MedicineRanks.setObjectName("MedicineRanks")
        self.SkillsScoreGrid.addWidget(self.MedicineRanks, 9, 2, 1, 1)
        self.MedicineClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MedicineClass.setMaximumSize(QtCore.QSize(50, 25))
        self.MedicineClass.setObjectName("MedicineClass")
        self.SkillsScoreGrid.addWidget(self.MedicineClass, 9, 3, 1, 1)
        self.MedicineAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MedicineAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.MedicineAbility.setReadOnly(True)
        self.MedicineAbility.setObjectName("MedicineAbility")
        self.SkillsScoreGrid.addWidget(self.MedicineAbility, 9, 4, 1, 1)
        self.MedicineMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MedicineMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.MedicineMisc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MedicineMisc.setObjectName("MedicineMisc")
        self.SkillsScoreGrid.addWidget(self.MedicineMisc, 9, 5, 1, 1)
        self.MysticismTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MysticismTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.MysticismTotal.setReadOnly(True)
        self.MysticismTotal.setObjectName("MysticismTotal")
        self.SkillsScoreGrid.addWidget(self.MysticismTotal, 10, 1, 1, 1)
        self.MysticismRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MysticismRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.MysticismRanks.setReadOnly(True)
        self.MysticismRanks.setObjectName("MysticismRanks")
        self.SkillsScoreGrid.addWidget(self.MysticismRanks, 10, 2, 1, 1)
        self.MysticismClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MysticismClass.setMaximumSize(QtCore.QSize(50, 25))
        self.MysticismClass.setReadOnly(True)
        self.MysticismClass.setObjectName("MysticismClass")
        self.SkillsScoreGrid.addWidget(self.MysticismClass, 10, 3, 1, 1)
        self.MysticismAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MysticismAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.MysticismAbility.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MysticismAbility.setObjectName("MysticismAbility")
        self.SkillsScoreGrid.addWidget(self.MysticismAbility, 10, 4, 1, 1)
        self.MysticismMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.MysticismMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.MysticismMisc.setObjectName("MysticismMisc")
        self.SkillsScoreGrid.addWidget(self.MysticismMisc, 10, 5, 1, 1)
        self.PerceptionTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PerceptionTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.PerceptionTotal.setReadOnly(True)
        self.PerceptionTotal.setObjectName("PerceptionTotal")
        self.SkillsScoreGrid.addWidget(self.PerceptionTotal, 11, 1, 1, 1)
        self.PerceptionRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PerceptionRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.PerceptionRanks.setReadOnly(True)
        self.PerceptionRanks.setObjectName("PerceptionRanks")
        self.SkillsScoreGrid.addWidget(self.PerceptionRanks, 11, 2, 1, 1)
        self.PerceptionClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PerceptionClass.setMaximumSize(QtCore.QSize(50, 25))
        self.PerceptionClass.setObjectName("PerceptionClass")
        self.SkillsScoreGrid.addWidget(self.PerceptionClass, 11, 3, 1, 1)
        self.PerceptionAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PerceptionAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.PerceptionAbility.setReadOnly(True)
        self.PerceptionAbility.setObjectName("PerceptionAbility")
        self.SkillsScoreGrid.addWidget(self.PerceptionAbility, 11, 4, 1, 1)
        self.PerceptionMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PerceptionMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.PerceptionMisc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PerceptionMisc.setObjectName("PerceptionMisc")
        self.SkillsScoreGrid.addWidget(self.PerceptionMisc, 11, 5, 1, 1)
        self.PhysicalTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PhysicalTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.PhysicalTotal.setReadOnly(True)
        self.PhysicalTotal.setObjectName("PhysicalTotal")
        self.SkillsScoreGrid.addWidget(self.PhysicalTotal, 12, 1, 1, 1)
        self.PhysicalRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PhysicalRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.PhysicalRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PhysicalRanks.setObjectName("PhysicalRanks")
        self.SkillsScoreGrid.addWidget(self.PhysicalRanks, 12, 2, 1, 1)
        self.PhysicalClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PhysicalClass.setMaximumSize(QtCore.QSize(50, 25))
        self.PhysicalClass.setObjectName("PhysicalClass")
        self.SkillsScoreGrid.addWidget(self.PhysicalClass, 12, 3, 1, 1)
        self.PhysicalAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PhysicalAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.PhysicalAbility.setReadOnly(True)
        self.PhysicalAbility.setObjectName("PhysicalAbility")
        self.SkillsScoreGrid.addWidget(self.PhysicalAbility, 12, 4, 1, 1)
        self.PhysicalMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.PhysicalMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.PhysicalMisc.setReadOnly(True)
        self.PhysicalMisc.setObjectName("PhysicalMisc")
        self.SkillsScoreGrid.addWidget(self.PhysicalMisc, 12, 5, 1, 1)
        self.ProfessionTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ProfessionTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.ProfessionTotal.setReadOnly(True)
        self.ProfessionTotal.setObjectName("ProfessionTotal")
        self.SkillsScoreGrid.addWidget(self.ProfessionTotal, 13, 1, 1, 1)
        self.ProfessionRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ProfessionRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.ProfessionRanks.setReadOnly(True)
        self.ProfessionRanks.setObjectName("ProfessionRanks")
        self.SkillsScoreGrid.addWidget(self.ProfessionRanks, 13, 2, 1, 1)
        self.ProfessionClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ProfessionClass.setMaximumSize(QtCore.QSize(50, 25))
        self.ProfessionClass.setReadOnly(True)
        self.ProfessionClass.setObjectName("ProfessionClass")
        self.SkillsScoreGrid.addWidget(self.ProfessionClass, 13, 3, 1, 1)
        self.ProfessionAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ProfessionAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.ProfessionAbility.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ProfessionAbility.setObjectName("ProfessionAbility")
        self.SkillsScoreGrid.addWidget(self.ProfessionAbility, 13, 4, 1, 1)
        self.ProfessionMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.ProfessionMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.ProfessionMisc.setObjectName("ProfessionMisc")
        self.SkillsScoreGrid.addWidget(self.ProfessionMisc, 13, 5, 1, 1)
        self.Profession2Total = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Profession2Total.setMaximumSize(QtCore.QSize(50, 25))
        self.Profession2Total.setReadOnly(True)
        self.Profession2Total.setObjectName("Profession2Total")
        self.SkillsScoreGrid.addWidget(self.Profession2Total, 14, 1, 1, 1)
        self.Profession2Ranks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Profession2Ranks.setMaximumSize(QtCore.QSize(50, 25))
        self.Profession2Ranks.setReadOnly(True)
        self.Profession2Ranks.setObjectName("Profession2Ranks")
        self.SkillsScoreGrid.addWidget(self.Profession2Ranks, 14, 2, 1, 1)
        self.Profession2Class = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Profession2Class.setMaximumSize(QtCore.QSize(50, 25))
        self.Profession2Class.setObjectName("Profession2Class")
        self.SkillsScoreGrid.addWidget(self.Profession2Class, 14, 3, 1, 1)
        self.Profession2Ability = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Profession2Ability.setMaximumSize(QtCore.QSize(50, 25))
        self.Profession2Ability.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Profession2Ability.setObjectName("Profession2Ability")
        self.SkillsScoreGrid.addWidget(self.Profession2Ability, 14, 4, 1, 1)
        self.Profession2Misc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.Profession2Misc.setMaximumSize(QtCore.QSize(50, 25))
        self.Profession2Misc.setReadOnly(True)
        self.Profession2Misc.setObjectName("Profession2Misc")
        self.SkillsScoreGrid.addWidget(self.Profession2Misc, 14, 5, 1, 1)
        self.SenseTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SenseTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.SenseTotal.setReadOnly(True)
        self.SenseTotal.setObjectName("SenseTotal")
        self.SkillsScoreGrid.addWidget(self.SenseTotal, 15, 1, 1, 1)
        self.SenseRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SenseRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.SenseRanks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SenseRanks.setObjectName("SenseRanks")
        self.SkillsScoreGrid.addWidget(self.SenseRanks, 15, 2, 1, 1)
        self.SenseClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SenseClass.setMaximumSize(QtCore.QSize(50, 25))
        self.SenseClass.setReadOnly(True)
        self.SenseClass.setObjectName("SenseClass")
        self.SkillsScoreGrid.addWidget(self.SenseClass, 15, 3, 1, 1)
        self.SenseAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SenseAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.SenseAbility.setObjectName("SenseAbility")
        self.SkillsScoreGrid.addWidget(self.SenseAbility, 15, 4, 1, 1)
        self.SenseMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SenseMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.SenseMisc.setReadOnly(True)
        self.SenseMisc.setObjectName("SenseMisc")
        self.SkillsScoreGrid.addWidget(self.SenseMisc, 15, 5, 1, 1)
        self.SlightTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SlightTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.SlightTotal.setReadOnly(True)
        self.SlightTotal.setObjectName("SlightTotal")
        self.SkillsScoreGrid.addWidget(self.SlightTotal, 16, 1, 1, 1)
        self.SlightRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SlightRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.SlightRanks.setReadOnly(True)
        self.SlightRanks.setObjectName("SlightRanks")
        self.SkillsScoreGrid.addWidget(self.SlightRanks, 16, 2, 1, 1)
        self.SlightClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SlightClass.setMaximumSize(QtCore.QSize(50, 25))
        self.SlightClass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SlightClass.setObjectName("SlightClass")
        self.SkillsScoreGrid.addWidget(self.SlightClass, 16, 3, 1, 1)
        self.SlightAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SlightAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.SlightAbility.setReadOnly(True)
        self.SlightAbility.setObjectName("SlightAbility")
        self.SkillsScoreGrid.addWidget(self.SlightAbility, 16, 4, 1, 1)
        self.SlightMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SlightMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.SlightMisc.setObjectName("SlightMisc")
        self.SkillsScoreGrid.addWidget(self.SlightMisc, 16, 5, 1, 1)
        self.StealthTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.StealthTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.StealthTotal.setReadOnly(True)
        self.StealthTotal.setObjectName("StealthTotal")
        self.SkillsScoreGrid.addWidget(self.StealthTotal, 17, 1, 1, 1)
        self.StealthRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.StealthRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.StealthRanks.setObjectName("StealthRanks")
        self.SkillsScoreGrid.addWidget(self.StealthRanks, 17, 2, 1, 1)
        self.StealthClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.StealthClass.setMaximumSize(QtCore.QSize(50, 25))
        self.StealthClass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StealthClass.setObjectName("StealthClass")
        self.SkillsScoreGrid.addWidget(self.StealthClass, 17, 3, 1, 1)
        self.StealthAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.StealthAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.StealthAbility.setReadOnly(True)
        self.StealthAbility.setObjectName("StealthAbility")
        self.SkillsScoreGrid.addWidget(self.StealthAbility, 17, 4, 1, 1)
        self.StealthMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.StealthMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.StealthMisc.setReadOnly(True)
        self.StealthMisc.setObjectName("StealthMisc")
        self.SkillsScoreGrid.addWidget(self.StealthMisc, 17, 5, 1, 1)
        self.SurvivalTotal = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SurvivalTotal.setMaximumSize(QtCore.QSize(50, 25))
        self.SurvivalTotal.setReadOnly(True)
        self.SurvivalTotal.setObjectName("SurvivalTotal")
        self.SkillsScoreGrid.addWidget(self.SurvivalTotal, 18, 1, 1, 1)
        self.SurvivalRanks = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SurvivalRanks.setMaximumSize(QtCore.QSize(50, 25))
        self.SurvivalRanks.setReadOnly(True)
        self.SurvivalRanks.setObjectName("SurvivalRanks")
        self.SkillsScoreGrid.addWidget(self.SurvivalRanks, 18, 2, 1, 1)
        self.SurvivalClass = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SurvivalClass.setMaximumSize(QtCore.QSize(50, 25))
        self.SurvivalClass.setReadOnly(True)
        self.SurvivalClass.setObjectName("SurvivalClass")
        self.SkillsScoreGrid.addWidget(self.SurvivalClass, 18, 3, 1, 1)
        self.SurvivalAbility = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SurvivalAbility.setMaximumSize(QtCore.QSize(50, 25))
        self.SurvivalAbility.setObjectName("SurvivalAbility")
        self.SkillsScoreGrid.addWidget(self.SurvivalAbility, 18, 4, 1, 1)
        self.SurvivalMisc = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.SurvivalMisc.setMaximumSize(QtCore.QSize(50, 25))
        self.SurvivalMisc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SurvivalMisc.setObjectName("SurvivalMisc")
        self.SkillsScoreGrid.addWidget(self.SurvivalMisc, 18, 5, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 230, 311, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.SkillCountGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.SkillCountGrid.setContentsMargins(0, 0, 0, 0)
        self.SkillCountGrid.setObjectName("SkillCountGrid")
        self.RemainingSkillText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.RemainingSkillText.setObjectName("RemainingSkillText")
        self.RemainingSkillText.setText("Remaining Skill Points")
        self.SkillCountGrid.addWidget(self.RemainingSkillText)
        self.RemainingSkillBox = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.RemainingSkillBox.setMaximumSize(QtCore.QSize(40, 25))
        self.RemainingSkillBox.setReadOnly(True)
        self.RemainingSkillBox.setObjectName("RemainingSkillBox")
        self.SkillCountGrid.addWidget(self.RemainingSkillBox)
        self.SkillsPerText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.SkillsPerText.setObjectName("SkillsPerText")
        self.SkillsPerText.setText("Skill Ranks Per Level")
        self.SkillCountGrid.addWidget(self.SkillsPerText)
        self.SkillsPerBox = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.SkillsPerBox.setMaximumSize(QtCore.QSize(40, 25))
        self.SkillsPerBox.setReadOnly(True)
        self.SkillsPerBox.setObjectName("SkillsPerBox")
        self.SkillCountGrid.addWidget(self.SkillsPerBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 311, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.CharacterNameGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.CharacterNameGrid.setContentsMargins(0, 0, 0, 0)
        self.CharacterNameGrid.setObjectName("CharacterNameGrid")
        self.CharacterNameText = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.CharacterNameText.setObjectName("CharacterNameText")
        self.CharacterNameText.setText("Character Name")
        self.CharacterNameGrid.addWidget(self.CharacterNameText)
        self.CharacterNameBox = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.CharacterNameBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.CharacterNameBox.setObjectName("CharacterNameBox")
        self.CharacterNameGrid.addWidget(self.CharacterNameBox)
        self.CharacterLevelBox = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.CharacterLevelBox.setMaximumSize(QtCore.QSize(40, 25))
        self.CharacterLevelBox.setReadOnly(True)
        self.CharacterLevelBox.setObjectName("CharacterLevelBox")
        self.CharacterNameGrid.addWidget(self.CharacterLevelBox)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(480, 310, 241, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.InitiativeGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.InitiativeGrid.setContentsMargins(0, 0, 0, 0)
        self.InitiativeGrid.setObjectName("InitiativeGrid")
        self.InitiativeText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.InitiativeText.setMaximumSize(QtCore.QSize(50, 25))
        self.InitiativeText.setObjectName("InitiativeText")
        self.InitiativeText.setText("Initiative")
        self.InitiativeGrid.addWidget(self.InitiativeText)
        self.InitiativeTotal = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_3)
        self.InitiativeTotal.setMaximumSize(QtCore.QSize(40, 25))
        self.InitiativeTotal.setReadOnly(True)
        self.InitiativeTotal.setObjectName("InitiativeTotal")
        self.InitiativeGrid.addWidget(self.InitiativeTotal)
        self.InitiativeEquals = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.InitiativeEquals.setMaximumSize(QtCore.QSize(10, 25))
        self.InitiativeEquals.setObjectName("InitiativeEquals")
        self.InitiativeEquals.setText("=")
        self.InitiativeGrid.addWidget(self.InitiativeEquals)
        self.InitiativeDexMod = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_3)
        self.InitiativeDexMod.setMaximumSize(QtCore.QSize(40, 25))
        self.InitiativeDexMod.setReadOnly(True)
        self.InitiativeDexMod.setObjectName("InitiativeDexMod")
        self.InitiativeGrid.addWidget(self.InitiativeDexMod)
        self.InitiativePlus = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.InitiativePlus.setMaximumSize(QtCore.QSize(10, 25))
        self.InitiativePlus.setObjectName("InitiativePlus")
        self.InitiativePlus.setText("+")
        self.InitiativeGrid.addWidget(self.InitiativePlus)
        self.InitiativeMiscMod = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_3)
        self.InitiativeMiscMod.setMaximumSize(QtCore.QSize(40, 25))
        self.InitiativeMiscMod.setReadOnly(True)
        self.InitiativeMiscMod.setObjectName("InitiativeMiscMod")
        self.InitiativeGrid.addWidget(self.InitiativeMiscMod)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(480, 360, 221, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.HPGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.HPGrid.setContentsMargins(0, 0, 0, 0)
        self.HPGrid.setObjectName("HPGrid")
        self.HPHitBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_3)
        self.HPHitBox.setMaximumSize(QtCore.QSize(40, 25))
        self.HPHitBox.setReadOnly(True)
        self.HPHitBox.setObjectName("HPHitBox")
        self.HPGrid.addWidget(self.HPHitBox, 1, 2, 1, 1)
        self.HPHitText = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HPHitText.setObjectName("HPHitText")
        self.HPHitText.setText("Hit Points")
        self.HPGrid.addWidget(self.HPHitText, 0, 2, 1, 1)
        self.HPStaminaText = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HPStaminaText.setObjectName("HPStaminaText")
        self.HPStaminaText.setText("Stamina Points")
        self.HPGrid.addWidget(self.HPStaminaText, 0, 1, 1, 1)
        self.HPStaminaBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_3)
        self.HPStaminaBox.setMaximumSize(QtCore.QSize(40, 25))
        self.HPStaminaBox.setReadOnly(True)
        self.HPStaminaBox.setObjectName("HPStaminaBox")
        self.HPGrid.addWidget(self.HPStaminaBox, 1, 1, 1, 1)
        self.HPResolveBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_3)
        self.HPResolveBox.setMaximumSize(QtCore.QSize(40, 25))
        self.HPResolveBox.setReadOnly(True)
        self.HPResolveBox.setObjectName("HPResolveBox")
        self.HPGrid.addWidget(self.HPResolveBox, 1, 3, 1, 1)
        self.HPTotalText = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HPTotalText.setObjectName("HPTotalText")
        self.HPTotalText.setText("Total")
        self.HPGrid.addWidget(self.HPTotalText, 1, 0, 1, 1)
        self.HPResolveText = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.HPResolveText.setObjectName("HPResolveText")
        self.HPResolveText.setText("Resolve")
        self.HPGrid.addWidget(self.HPResolveText, 0, 3, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(480, 440, 421, 115))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.ACGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.ACGrid.setContentsMargins(0, 0, 0, 0)
        self.ACGrid.setObjectName("ACGrid")
        self.EACText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.EACText.setObjectName("EACText")
        self.EACText.setText("Energy Armor Class (EAC)")
        self.ACGrid.addWidget(self.EACText, 2, 0, 1, 1)
        self.KACText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.KACText.setObjectName("KACText")
        self.KACText.setText("Kinetic Armor Class (KAC)")
        self.ACGrid.addWidget(self.KACText, 3, 0, 1, 1)
        self.ACVSText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACVSText.setObjectName("ACVSText")
        self.ACVSText.setText("AC VS Combat Maneuvers")
        self.ACGrid.addWidget(self.ACVSText, 4, 0, 1, 1)
        self.ACTotalText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACTotalText.setObjectName("ACTotalText")
        self.ACTotalText.setText("Total")
        self.ACGrid.addWidget(self.ACTotalText, 0, 1, 1, 1)
        self.ACArmorText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACArmorText.setObjectName("ACArmorText")
        self.ACArmorText.setText("Armor Bonus")
        self.ACGrid.addWidget(self.ACArmorText, 0, 3, 1, 1)
        self.ACDexText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACDexText.setObjectName("ACDexText")
        self.ACDexText.setText("Dex Mod")
        self.ACGrid.addWidget(self.ACDexText, 0, 5, 1, 1)
        self.ACMiscText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACMiscText.setObjectName("ACMiscText")
        self.ACMiscText.setText("MiscMod")
        self.ACGrid.addWidget(self.ACMiscText, 0, 7, 1, 1)
        self.EACPlus = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.EACPlus.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus.setObjectName("EACPlus")
        self.EACPlus.setText("+")
        self.ACGrid.addWidget(self.EACPlus, 2, 4, 1, 1)
        self.EACArmorBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.EACArmorBox.setMaximumSize(QtCore.QSize(40, 25))
        self.EACArmorBox.setReadOnly(True)
        self.EACArmorBox.setObjectName("EACArmorBox")
        self.ACGrid.addWidget(self.EACArmorBox, 2, 3, 1, 1)
        self.EACEquals = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.EACEquals.setMaximumSize(QtCore.QSize(40, 25))
        self.EACEquals.setObjectName("EACEquals")
        self.EACEquals.setText("= 10 +")
        self.ACGrid.addWidget(self.EACEquals, 2, 2, 1, 1)
        self.EACTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.EACTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.EACTotalBox.setReadOnly(True)
        self.EACTotalBox.setObjectName("EACTotalBox")
        self.ACGrid.addWidget(self.EACTotalBox, 2, 1, 1, 1)
        self.EACDexBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.EACDexBox.setMaximumSize(QtCore.QSize(40, 25))
        self.EACDexBox.setReadOnly(True)
        self.EACDexBox.setObjectName("EACDexBox")
        self.ACGrid.addWidget(self.EACDexBox, 2, 5, 1, 1)
        self.EACPlus_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.EACPlus_2.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_2.setObjectName("EACPlus_2")
        self.EACPlus_2.setText("+")
        self.ACGrid.addWidget(self.EACPlus_2, 2, 6, 1, 1)
        self.EACMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.EACMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.EACMiscBox.setReadOnly(True)
        self.EACMiscBox.setObjectName("EACMiscBox")
        self.ACGrid.addWidget(self.EACMiscBox, 2, 7, 1, 1)
        self.KACTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.KACTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.KACTotalBox.setReadOnly(True)
        self.KACTotalBox.setObjectName("KACTotalBox")
        self.ACGrid.addWidget(self.KACTotalBox, 3, 1, 1, 1)
        self.KACPlus = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.KACPlus.setMaximumSize(QtCore.QSize(10, 25))
        self.KACPlus.setObjectName("KACPlus")
        self.KACPlus.setText("+")
        self.ACGrid.addWidget(self.KACPlus, 3, 4, 1, 1)
        self.KACMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.KACMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.KACMiscBox.setReadOnly(True)
        self.KACMiscBox.setObjectName("KACMiscBox")
        self.ACGrid.addWidget(self.KACMiscBox, 3, 7, 1, 1)
        self.KACArmorBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.KACArmorBox.setMaximumSize(QtCore.QSize(40, 25))
        self.KACArmorBox.setReadOnly(True)
        self.KACArmorBox.setObjectName("KACArmorBox")
        self.ACGrid.addWidget(self.KACArmorBox, 3, 3, 1, 1)
        self.KACPlus_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.KACPlus_2.setMaximumSize(QtCore.QSize(10, 25))
        self.KACPlus_2.setObjectName("KACPlus_2")
        self.KACPlus_2.setText("+")
        self.ACGrid.addWidget(self.KACPlus_2, 3, 6, 1, 1)
        self.KACDexBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.KACDexBox.setMaximumSize(QtCore.QSize(40, 25))
        self.KACDexBox.setReadOnly(True)
        self.KACDexBox.setObjectName("KACDexBox")
        self.ACGrid.addWidget(self.KACDexBox, 3, 5, 1, 1)
        self.ACVSTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.ACVSTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ACVSTotalBox.setReadOnly(True)
        self.ACVSTotalBox.setObjectName("ACVSTotalBox")
        self.ACGrid.addWidget(self.ACVSTotalBox, 4, 1, 1, 1)
        self.KACEquals = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.KACEquals.setMaximumSize(QtCore.QSize(40, 25))
        self.KACEquals.setObjectName("KACEquals")
        self.KACEquals.setText("= 10 +")
        self.ACGrid.addWidget(self.KACEquals, 3, 2, 1, 1)
        self.ACVSEquals = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ACVSEquals.setMaximumSize(QtCore.QSize(40, 25))
        self.ACVSEquals.setObjectName("ACVSEquals")
        self.ACVSEquals.setText("= 8 +")
        self.ACGrid.addWidget(self.ACVSEquals, 4, 2, 1, 1)
        self.ACVSKACBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.ACVSKACBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ACVSKACBox.setReadOnly(True)
        self.ACVSKACBox.setObjectName("ACVSKACBox")
        self.ACGrid.addWidget(self.ACVSKACBox, 4, 3, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(480, 570, 297, 108))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.SaveGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.SaveGrid.setContentsMargins(0, 0, 0, 0)
        self.SaveGrid.setObjectName("SaveGrid")
        self.WillEquals = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.WillEquals.setMaximumSize(QtCore.QSize(10, 25))
        self.WillEquals.setObjectName("WillEquals")
        self.WillEquals.setText("=")
        self.SaveGrid.addWidget(self.WillEquals, 3, 2, 1, 1)
        self.ReflexEquals = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.ReflexEquals.setMaximumSize(QtCore.QSize(10, 25))
        self.ReflexEquals.setObjectName("ReflexEquals")
        self.ReflexEquals.setText("=")
        self.SaveGrid.addWidget(self.ReflexEquals, 2, 2, 1, 1)
        self.FortitudeEquals = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.FortitudeEquals.setMaximumSize(QtCore.QSize(10, 25))
        self.FortitudeEquals.setObjectName("FortitudeEquals")
        self.FortitudeEquals.setText("=")
        self.SaveGrid.addWidget(self.FortitudeEquals, 1, 2, 1, 1)
        self.ReflexTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.ReflexTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ReflexTotalBox.setReadOnly(True)
        self.ReflexTotalBox.setObjectName("ReflexTotalBox")
        self.SaveGrid.addWidget(self.ReflexTotalBox, 2, 1, 1, 1)
        self.ReflexAbilityBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.ReflexAbilityBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ReflexAbilityBox.setReadOnly(True)
        self.ReflexAbilityBox.setObjectName("ReflexAbilityBox")
        self.SaveGrid.addWidget(self.ReflexAbilityBox, 2, 5, 1, 1)
        self.WillPlus = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.WillPlus.setMaximumSize(QtCore.QSize(10, 25))
        self.WillPlus.setObjectName("WillPlus")
        self.WillPlus.setText("+")
        self.SaveGrid.addWidget(self.WillPlus, 3, 4, 1, 1)
        self.ReflexPlus = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.ReflexPlus.setMaximumSize(QtCore.QSize(10, 25))
        self.ReflexPlus.setObjectName("ReflexPlus")
        self.ReflexPlus.setText("+")
        self.SaveGrid.addWidget(self.ReflexPlus, 2, 4, 1, 1)
        self.WillAbilityBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.WillAbilityBox.setMaximumSize(QtCore.QSize(40, 25))
        self.WillAbilityBox.setReadOnly(True)
        self.WillAbilityBox.setObjectName("WillAbilityBox")
        self.SaveGrid.addWidget(self.WillAbilityBox, 3, 5, 1, 1)
        self.FortitudeTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.FortitudeTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.FortitudeTotalBox.setReadOnly(True)
        self.FortitudeTotalBox.setObjectName("FortitudeTotalBox")
        self.SaveGrid.addWidget(self.FortitudeTotalBox, 1, 1, 1, 1)
        self.FortitudeBaseBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.FortitudeBaseBox.setMaximumSize(QtCore.QSize(40, 25))
        self.FortitudeBaseBox.setReadOnly(True)
        self.FortitudeBaseBox.setObjectName("FortitudeBaseBox")
        self.SaveGrid.addWidget(self.FortitudeBaseBox, 1, 3, 1, 1)
        self.FortitudeAbilityBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.FortitudeAbilityBox.setMaximumSize(QtCore.QSize(40, 25))
        self.FortitudeAbilityBox.setReadOnly(True)
        self.FortitudeAbilityBox.setObjectName("FortitudeAbilityBox")
        self.SaveGrid.addWidget(self.FortitudeAbilityBox, 1, 5, 1, 1)
        self.SaveBaseText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.SaveBaseText.setObjectName("SaveBaseText")
        self.SaveBaseText.setText("Base Save")
        self.SaveGrid.addWidget(self.SaveBaseText, 0, 3, 1, 1)
        self.SaveMiscText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.SaveMiscText.setObjectName("SaveMiscText")
        self.SaveMiscText.setText("Misc Mod")
        self.SaveGrid.addWidget(self.SaveMiscText, 0, 7, 1, 1)
        self.ReflexBaseBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.ReflexBaseBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ReflexBaseBox.setReadOnly(True)
        self.ReflexBaseBox.setObjectName("ReflexBaseBox")
        self.SaveGrid.addWidget(self.ReflexBaseBox, 2, 3, 1, 1)
        self.SaveAbilityText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.SaveAbilityText.setObjectName("SaveAbilityText")
        self.SaveAbilityText.setText("Ability Mod")
        self.SaveGrid.addWidget(self.SaveAbilityText, 0, 5, 1, 1)
        self.FortitudeMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.FortitudeMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.FortitudeMiscBox.setReadOnly(True)
        self.FortitudeMiscBox.setObjectName("FortitudeMiscBox")
        self.SaveGrid.addWidget(self.FortitudeMiscBox, 1, 7, 1, 1)
        self.FortitudeText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.FortitudeText.setObjectName("FortitudeText")
        self.FortitudeText.setText("Fortitude")
        self.SaveGrid.addWidget(self.FortitudeText, 1, 0, 1, 1)
        self.SaveTotalText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.SaveTotalText.setObjectName("SaveTotalText")
        self.SaveTotalText.setText("Total")
        self.SaveGrid.addWidget(self.SaveTotalText, 0, 1, 1, 1)
        self.WillText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.WillText.setObjectName("WillText")
        self.WillText.setText("Will")
        self.SaveGrid.addWidget(self.WillText, 3, 0, 1, 1)
        self.ReflexText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.ReflexText.setObjectName("ReflexText")
        self.ReflexText.setText("Reflex")
        self.SaveGrid.addWidget(self.ReflexText, 2, 0, 1, 1)
        self.ReflexMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.ReflexMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ReflexMiscBox.setReadOnly(True)
        self.ReflexMiscBox.setObjectName("ReflexMiscBox")
        self.SaveGrid.addWidget(self.ReflexMiscBox, 2, 7, 1, 1)
        self.WillMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.WillMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.WillMiscBox.setReadOnly(True)
        self.WillMiscBox.setObjectName("WillMiscBox")
        self.SaveGrid.addWidget(self.WillMiscBox, 3, 7, 1, 1)
        self.WillTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.WillTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.WillTotalBox.setReadOnly(True)
        self.WillTotalBox.setObjectName("WillTotalBox")
        self.SaveGrid.addWidget(self.WillTotalBox, 3, 1, 1, 1)
        self.FortitudePlus = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.FortitudePlus.setMaximumSize(QtCore.QSize(10, 25))
        self.FortitudePlus.setObjectName("FortitudePlus")
        self.FortitudePlus.setText("+")
        self.SaveGrid.addWidget(self.FortitudePlus, 1, 4, 1, 1)
        self.WillBaseBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.WillBaseBox.setMaximumSize(QtCore.QSize(40, 25))
        self.WillBaseBox.setReadOnly(True)
        self.WillBaseBox.setObjectName("WillBaseBox")
        self.SaveGrid.addWidget(self.WillBaseBox, 3, 3, 1, 1)
        self.FortitudePlus_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.FortitudePlus_2.setMaximumSize(QtCore.QSize(10, 25))
        self.FortitudePlus_2.setObjectName("FortitudePlus_2")
        self.FortitudePlus_2.setText("+")
        self.SaveGrid.addWidget(self.FortitudePlus_2, 1, 6, 1, 1)
        self.ReflexPlus_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.ReflexPlus_2.setMaximumSize(QtCore.QSize(10, 25))
        self.ReflexPlus_2.setObjectName("ReflexPlus_2")
        self.ReflexPlus_2.setText("+")
        self.SaveGrid.addWidget(self.ReflexPlus_2, 2, 6, 1, 1)
        self.WillPlus_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.WillPlus_2.setMaximumSize(QtCore.QSize(10, 25))
        self.WillPlus_2.setObjectName("WillPlus_2")
        self.WillPlus_2.setText("+")
        self.SaveGrid.addWidget(self.WillPlus_2, 3, 6, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(480, 700, 321, 151))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.AttackGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.AttackGrid.setContentsMargins(0, 0, 0, 0)
        self.AttackGrid.setObjectName("AttackGrid")
        self.RangedModBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.RangedModBox.setMaximumSize(QtCore.QSize(40, 25))
        self.RangedModBox.setReadOnly(True)
        self.RangedModBox.setObjectName("RangedModBox")
        self.AttackGrid.addWidget(self.RangedModBox, 3, 5, 1, 1)
        self.RangedModText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.RangedModText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RangedModText.setObjectName("RangedModText")
        self.RangedModText.setText("Dex Mod")
        self.AttackGrid.addWidget(self.RangedModText, 2, 5, 1, 1)
        self.ThrownModBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.ThrownModBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ThrownModBox.setReadOnly(True)
        self.ThrownModBox.setObjectName("ThrownModBox")
        self.AttackGrid.addWidget(self.ThrownModBox, 5, 5, 1, 1)
        self.ThrownTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.ThrownTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ThrownTotalBox.setReadOnly(True)
        self.ThrownTotalBox.setObjectName("ThrownTotalBox")
        self.AttackGrid.addWidget(self.ThrownTotalBox, 5, 1, 1, 1)
        self.RangedMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.RangedMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.RangedMiscBox.setReadOnly(True)
        self.RangedMiscBox.setObjectName("RangedMiscBox")
        self.AttackGrid.addWidget(self.RangedMiscBox, 3, 7, 1, 1)
        self.ThrownBABBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.ThrownBABBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ThrownBABBox.setReadOnly(True)
        self.ThrownBABBox.setObjectName("ThrownBABBox")
        self.AttackGrid.addWidget(self.ThrownBABBox, 5, 3, 1, 1)
        self.RangedTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.RangedTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.RangedTotalBox.setReadOnly(True)
        self.RangedTotalBox.setObjectName("RangedTotalBox")
        self.AttackGrid.addWidget(self.RangedTotalBox, 3, 1, 1, 1)
        self.EACPlus_4 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_4.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_4.setObjectName("EACPlus_4")
        self.EACPlus_4.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_4, 1, 6, 1, 1)
        self.InitiativeEquals_4 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.InitiativeEquals_4.setMaximumSize(QtCore.QSize(10, 25))
        self.InitiativeEquals_4.setObjectName("InitiativeEquals_4")
        self.InitiativeEquals_4.setText("=")
        self.AttackGrid.addWidget(self.InitiativeEquals_4, 5, 2, 1, 1)
        self.MeleeMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.MeleeMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.MeleeMiscBox.setReadOnly(True)
        self.MeleeMiscBox.setObjectName("MeleeMiscBox")
        self.AttackGrid.addWidget(self.MeleeMiscBox, 1, 7, 1, 1)
        self.RangedBABText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.RangedBABText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RangedBABText.setObjectName("RangedBABText")
        self.RangedBABText.setText("BAB")
        self.AttackGrid.addWidget(self.RangedBABText, 2, 3, 1, 1)
        self.InitiativeEquals_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.InitiativeEquals_3.setMaximumSize(QtCore.QSize(10, 25))
        self.InitiativeEquals_3.setObjectName("InitiativeEquals_3")
        self.InitiativeEquals_3.setText("=")
        self.AttackGrid.addWidget(self.InitiativeEquals_3, 3, 2, 1, 1)
        self.RangedTotalText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.RangedTotalText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RangedTotalText.setObjectName("RangedTotalText")
        self.RangedTotalText.setText("Total")
        self.AttackGrid.addWidget(self.RangedTotalText, 2, 1, 1, 1)
        self.MeleeTotalBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.MeleeTotalBox.setMaximumSize(QtCore.QSize(40, 25))
        self.MeleeTotalBox.setReadOnly(True)
        self.MeleeTotalBox.setObjectName("MeleeTotalBox")
        self.AttackGrid.addWidget(self.MeleeTotalBox, 1, 1, 1, 1)
        self.EACPlus_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_3.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_3.setObjectName("EACPlus_3")
        self.EACPlus_3.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_3, 1, 4, 1, 1)
        self.MeleeTotalText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.MeleeTotalText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MeleeTotalText.setObjectName("MeleeTotalText")
        self.MeleeTotalText.setText("Total")
        self.AttackGrid.addWidget(self.MeleeTotalText, 0, 1, 1, 1)
        self.MeleeMiscText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.MeleeMiscText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MeleeMiscText.setObjectName("MeleeMiscText")
        self.MeleeMiscText.setText("Misc Mod")
        self.AttackGrid.addWidget(self.MeleeMiscText, 0, 7, 1, 1)
        self.MeleeBABBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.MeleeBABBox.setMaximumSize(QtCore.QSize(40, 25))
        self.MeleeBABBox.setReadOnly(True)
        self.MeleeBABBox.setObjectName("MeleeBABBox")
        self.AttackGrid.addWidget(self.MeleeBABBox, 1, 3, 1, 1)
        self.InitiativeEquals_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.InitiativeEquals_2.setMaximumSize(QtCore.QSize(10, 25))
        self.InitiativeEquals_2.setObjectName("InitiativeEquals_2")
        self.InitiativeEquals_2.setText("=")
        self.AttackGrid.addWidget(self.InitiativeEquals_2, 1, 2, 1, 1)
        self.RangedMiscText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.RangedMiscText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RangedMiscText.setObjectName("RangedMiscText")
        self.RangedMiscText.setText("Misc Mod")
        self.AttackGrid.addWidget(self.RangedMiscText, 2, 7, 1, 1)
        self.ThrownMiscBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.ThrownMiscBox.setMaximumSize(QtCore.QSize(40, 25))
        self.ThrownMiscBox.setReadOnly(True)
        self.ThrownMiscBox.setObjectName("ThrownMiscBox")
        self.AttackGrid.addWidget(self.ThrownMiscBox, 5, 7, 1, 1)
        self.RangedBABBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.RangedBABBox.setMaximumSize(QtCore.QSize(40, 25))
        self.RangedBABBox.setReadOnly(True)
        self.RangedBABBox.setObjectName("RangedBABBox")
        self.AttackGrid.addWidget(self.RangedBABBox, 3, 3, 1, 1)
        self.EACPlus_6 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_6.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_6.setObjectName("EACPlus_6")
        self.EACPlus_6.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_6, 5, 4, 1, 1)
        self.EACPlus_8 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_8.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_8.setObjectName("EACPlus_8")
        self.EACPlus_8.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_8, 5, 6, 1, 1)
        self.EACPlus_5 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_5.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_5.setObjectName("EACPlus_5")
        self.EACPlus_5.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_5, 3, 4, 1, 1)
        self.EACPlus_7 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.EACPlus_7.setMaximumSize(QtCore.QSize(10, 25))
        self.EACPlus_7.setObjectName("EACPlus_7")
        self.EACPlus_7.setText("+")
        self.AttackGrid.addWidget(self.EACPlus_7, 3, 6, 1, 1)
        self.MeleeModText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.MeleeModText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MeleeModText.setObjectName("MeleeModText")
        self.MeleeModText.setText("Str Mod")
        self.AttackGrid.addWidget(self.MeleeModText, 0, 5, 1, 1)
        self.RangedText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.RangedText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RangedText.setObjectName("RangedText")
        self.RangedText.setText("Ranged Attack")
        self.AttackGrid.addWidget(self.RangedText, 3, 0, 1, 1)
        self.ThrownText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.ThrownText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ThrownText.setObjectName("ThrownText")
        self.ThrownText.setText("Thrown Attack")
        self.AttackGrid.addWidget(self.ThrownText, 5, 0, 1, 1)
        self.MeleeModBox = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
        self.MeleeModBox.setMaximumSize(QtCore.QSize(40, 25))
        self.MeleeModBox.setReadOnly(True)
        self.MeleeModBox.setObjectName("MeleeModBox")
        self.AttackGrid.addWidget(self.MeleeModBox, 1, 5, 1, 1)
        self.MeleeBABText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.MeleeBABText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MeleeBABText.setObjectName("MeleeBABText")
        self.MeleeBABText.setText("BAB")
        self.AttackGrid.addWidget(self.MeleeBABText, 0, 3, 1, 1)
        self.MeleeText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.MeleeText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.MeleeText.setObjectName("MeleeText")
        self.MeleeText.setText("Melee Attack")
        self.AttackGrid.addWidget(self.MeleeText, 1, 0, 1, 1)
        self.ThrownTotalText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.ThrownTotalText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ThrownTotalText.setObjectName("ThrownTotalText")
        self.ThrownTotalText.setText("Total")
        self.AttackGrid.addWidget(self.ThrownTotalText, 4, 1, 1, 1)
        self.ThrownBABText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.ThrownBABText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ThrownBABText.setObjectName("ThrownBABText")
        self.ThrownBABText.setText("BAB")
        self.AttackGrid.addWidget(self.ThrownBABText, 4, 3, 1, 1)
        self.ThrownModText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.ThrownModText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ThrownModText.setObjectName("ThrownModText")
        self.ThrownModText.setText("Str Mod")
        self.AttackGrid.addWidget(self.ThrownModText, 4, 5, 1, 1)
        self.ThrownMiscText = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.ThrownMiscText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ThrownMiscText.setObjectName("ThrownMiscText")
        self.ThrownMiscText.setText("Misc Mod")
        self.AttackGrid.addWidget(self.ThrownMiscText, 4, 7, 1, 1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 181, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.RaceGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.RaceGrid.setContentsMargins(0, 0, 0, 0)
        self.RaceGrid.setObjectName("RaceGrid")
        self.RaceText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.RaceText.setMaximumSize(QtCore.QSize(30, 25))
        self.RaceText.setObjectName("RaceText")
        self.RaceText.setText("Race")
        self.RaceGrid.addWidget(self.RaceText)
        self.RaceCombo = ComboBox()
        self.RaceCombo.setObjectName("RaceCombo")
        self.RaceCombo.setPlaceholderText("<<Select Race>>")
        self.RaceCombo.addItem("Android")
        self.RaceCombo.addItem("Human")
        self.RaceCombo.addItem("Kasatha")
        self.RaceCombo.addItem("Lashunta(Korasha)")
        self.RaceCombo.addItem("Lashunta(Damaya)")
        self.RaceCombo.addItem("Shirren")
        self.RaceCombo.addItem("Vesk")
        self.RaceCombo.addItem("Ysoki")
        self.RaceGrid.addWidget(self.RaceCombo)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 110, 181, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.ThemeGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.ThemeGrid.setContentsMargins(0, 0, 0, 0)
        self.ThemeGrid.setObjectName("ThemeGrid")
        self.ThemeText = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.ThemeText.setMaximumSize(QtCore.QSize(30, 25))
        self.ThemeText.setObjectName("ThemeText")
        self.ThemeText.setText("Theme")
        self.ThemeGrid.addWidget(self.ThemeText)
        self.ThemeCombo = ComboBox()
        self.ThemeCombo.setObjectName("ThemeCombo")
        self.ThemeCombo.setPlaceholderText("<<Select Theme>>")
        self.ThemeCombo.addItem("Ace Pilot")
        self.ThemeCombo.addItem("Bounty Hunter")
        self.ThemeCombo.addItem("Icon")
        self.ThemeCombo.addItem("Mercenary")
        self.ThemeCombo.addItem("Outlaw")
        self.ThemeCombo.addItem("Priest")
        self.ThemeCombo.addItem("Scholar")
        self.ThemeCombo.addItem("Spacefarer")
        self.ThemeCombo.addItem("Xenoseeker")
        self.ThemeCombo.addItem("Themeless")
        self.ThemeGrid.addWidget(self.ThemeCombo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CharacterSheetMaker"))
        # self.IntText.setText(_translate("MainWindow", "Int"))
        # self.ConText.setText(_translate("MainWindow", "Con"))
        # self.StrText.setText(_translate("MainWindow", "Str"))
        # self.DexText.setText(_translate("MainWindow", "Dex"))
        # self.ChaText.setText(_translate("MainWindow", "Cha"))
        # self.RacePointText.setText(_translate("MainWindow", "Race Points"))
        # self.ModifierText.setText(_translate("MainWindow", "Modifier"))
        # self.ThemePointText.setText(_translate("MainWindow", "Theme Points"))
        # self.ScoreText.setText(_translate("MainWindow", "Score"))
        # self.WisText.setText(_translate("MainWindow", "Wis"))
        # self.PointBuyText.setText(_translate("MainWindow", "Point Buy"))
        # self.AbilityIncreasesText.setText(_translate("MainWindow", "Ability Increases"))
        # self.SkillRanksText.setText(_translate("MainWindow", "Ranks"))
        # self.SurvivalText.setText(_translate("MainWindow", "Survival (Wis)"))
        # self.SkillClassText.setText(_translate("MainWindow", "Class Bonus"))
        # self.SkillTotalText.setText(_translate("MainWindow", "Total"))
        # self.DisguiseText.setText(_translate("MainWindow", "Disguise (Cha)"))
        # self.SlightText.setText(_translate("MainWindow", "Slight of Hand (Dex)"))
        # self.StealthText.setText(_translate("MainWindow", "Stealth (Dex)"))
        # self.LifeText.setText(_translate("MainWindow", "Life Science (Int)"))
        # self.AcrobaticsText.setText(_translate("MainWindow", "Acrobatics (Dex)"))
        # self.CultureText.setText(_translate("MainWindow", "Culture (Int)"))
        # self.BluffText.setText(_translate("MainWindow", "Bluff (Cha)"))
        # self.AthleticsText.setText(_translate("MainWindow", "Athletics (Str)"))
        # self.ComputersText.setText(_translate("MainWindow", "Computers (Int)"))
        # self.DiplomacyText.setText(_translate("MainWindow", "Diplomacy (Cha)"))
        # self.SenseText.setText(_translate("MainWindow", "Sense Motive (Wis)"))
        # self.MysticismText.setText(_translate("MainWindow", "Mysticism (Wis)"))
        # self.MedicineText.setText(_translate("MainWindow", "Medicine (Int)"))
        # self.PerceptionText.setText(_translate("MainWindow", "Perception (Wis)"))
        # self.PhysicalText.setText(_translate("MainWindow", "Physical Science (Int)"))
        # self.SkillMiscText.setText(_translate("MainWindow", "Misc Mod"))
        # self.ProfessionText.setText(_translate("MainWindow", "Profession (Cha, Int, Wis)"))
        # self.Profession2Text.setText(_translate("MainWindow", "Profession (Cha, Int, Wis)"))
        # self.SkillAbilityText.setText(_translate("MainWindow", "Ability Mod"))
        # self.RemainingSkillText.setText(_translate("MainWindow", "Remaining Skill Points"))
        # self.SkillsPerText.setText(_translate("MainWindow", "Skill Ranks Per Level"))
        # self.CharacterNameText.setText(_translate("MainWindow", "Character Name"))
        # self.InitiativeText.setText(_translate("MainWindow", "Initiative"))
        # self.InitiativeEquals.setText(_translate("MainWindow", "="))
        # self.InitiativePlus.setText(_translate("MainWindow", "+"))
        # self.HPHitText.setText(_translate("MainWindow", "Hit Points"))
        # self.HPStaminaText.setText(_translate("MainWindow", "Stamina Points"))
        # self.HPTotalText.setText(_translate("MainWindow", "Total"))
        # self.HPResolveText.setText(_translate("MainWindow", "Resolve"))
        # self.EACText.setText(_translate("MainWindow", "Energy Armor Class (EAC)"))
        # self.KACText.setText(_translate("MainWindow", "Kinetic Armor Class (KAC)"))
        # self.ACVSText.setText(_translate("MainWindow", "AC VS Combat Maneuvers"))
        # self.ACTotalText.setText(_translate("MainWindow", "Total"))
        # self.ACArmorText.setText(_translate("MainWindow", "Armor Bonus"))
        # self.ACDexText.setText(_translate("MainWindow", "Dex Mod"))
        # self.ACMiscText.setText(_translate("MainWindow", "MiscMod"))
        # self.EACPlus.setText(_translate("MainWindow", "+"))
        # self.EACEquals.setText(_translate("MainWindow", "= 10 +"))
        # self.EACPlus_2.setText(_translate("MainWindow", "+"))
        # self.KACPlus.setText(_translate("MainWindow", "+"))
        # self.KACPlus_2.setText(_translate("MainWindow", "+"))
        # self.KACEquals.setText(_translate("MainWindow", "= 10 +"))
        # self.ACVSEquals.setText(_translate("MainWindow", "= 8 +"))
        # self.WillEquals.setText(_translate("MainWindow", "="))
        # self.ReflexEquals.setText(_translate("MainWindow", "="))
        # self.FortitudeEquals.setText(_translate("MainWindow", "="))
        # self.WillPlus.setText(_translate("MainWindow", "+"))
        # self.ReflexPlus.setText(_translate("MainWindow", "+"))
        # self.SaveBaseText.setText(_translate("MainWindow", "Base Save"))
        # self.SaveMiscText.setText(_translate("MainWindow", "Misc Mod"))
        # self.SaveAbilityText.setText(_translate("MainWindow", "Ability Mod"))
        # self.FortitudeText.setText(_translate("MainWindow", "Fortitude"))
        # self.SaveTotalText.setText(_translate("MainWindow", "Total"))
        # self.WillText.setText(_translate("MainWindow", "Will"))
        # self.ReflexText.setText(_translate("MainWindow", "Reflex"))
        # self.FortitudePlus.setText(_translate("MainWindow", "+"))
        # self.FortitudePlus_2.setText(_translate("MainWindow", "+"))
        # self.ReflexPlus_2.setText(_translate("MainWindow", "+"))
        # self.WillPlus_2.setText(_translate("MainWindow", "+"))
        # self.RangedModText.setText(_translate("MainWindow", "Dex Mod"))
        # self.EACPlus_4.setText(_translate("MainWindow", "+"))
        # self.InitiativeEquals_4.setText(_translate("MainWindow", "="))
        # self.RangedBABText.setText(_translate("MainWindow", "BAB"))
        # self.InitiativeEquals_3.setText(_translate("MainWindow", "="))
        # self.RangedTotalText.setText(_translate("MainWindow", "Total"))
        # self.EACPlus_3.setText(_translate("MainWindow", "+"))
        # self.MeleeTotalText.setText(_translate("MainWindow", "Total"))
        # self.MeleeMiscText.setText(_translate("MainWindow", "Misc Mod"))
        # self.InitiativeEquals_2.setText(_translate("MainWindow", "="))
        # self.RangedMiscText.setText(_translate("MainWindow", "Misc Mod"))
        # self.EACPlus_6.setText(_translate("MainWindow", "+"))
        # self.EACPlus_8.setText(_translate("MainWindow", "+"))
        # self.EACPlus_5.setText(_translate("MainWindow", "+"))
        # self.EACPlus_7.setText(_translate("MainWindow", "+"))
        # self.MeleeModText.setText(_translate("MainWindow", "Str Mod"))
        # self.RangedText.setText(_translate("MainWindow", "Ranged Attack"))
        # self.ThrownText.setText(_translate("MainWindow", "Thrown Attack"))
        # self.MeleeBABText.setText(_translate("MainWindow", "BAB"))
        # self.MeleeText.setText(_translate("MainWindow", "Melee Attack"))
        # self.ThrownTotalText.setText(_translate("MainWindow", "Total"))
        # self.ThrownBABText.setText(_translate("MainWindow", "BAB"))
        # self.ThrownModText.setText(_translate("MainWindow", "Str Mod"))
        # self.ThrownMiscText.setText(_translate("MainWindow", "Misc Mod"))
        # self.RaceText.setText(_translate("MainWindow", "Race"))
        # self.RaceCombo.setItemText(0, _translate("MainWindow", "<<Select Race>>"))
        # self.RaceCombo.setItemText(1, _translate("MainWindow", "Android"))
        # self.RaceCombo.setItemText(2, _translate("MainWindow", "Human"))
        # self.RaceCombo.setItemText(3, _translate("MainWindow", "Kasatha"))
        # self.RaceCombo.setItemText(4, _translate("MainWindow", "Lashunta(Korasha)"))
        # self.RaceCombo.setItemText(5, _translate("MainWindow", "Lashunta(Damaya)"))
        # self.RaceCombo.setItemText(6, _translate("MainWindow", "Shirren"))
        # self.RaceCombo.setItemText(7, _translate("MainWindow", "Vesk"))
        # self.RaceCombo.setItemText(8, _translate("MainWindow", "Ysoki"))
        # self.ThemeText.setText(_translate("MainWindow", "Theme"))
        # self.ThemeCombo.setItemText(0, _translate("MainWindow", "<<Select Theme>>"))
        # self.ThemeCombo.setItemText(1, _translate("MainWindow", "Ace Pilot"))
        # self.ThemeCombo.setItemText(2, _translate("MainWindow", "Bounty Hunter"))
        # self.ThemeCombo.setItemText(3, _translate("MainWindow", "Icon"))
        # self.ThemeCombo.setItemText(4, _translate("MainWindow", "Mercenary"))
        # self.ThemeCombo.setItemText(5, _translate("MainWindow", "Outlaw"))
        # self.ThemeCombo.setItemText(6, _translate("MainWindow", "Priest"))
        # self.ThemeCombo.setItemText(7, _translate("MainWindow", "Scholar"))
        # self.ThemeCombo.setItemText(8, _translate("MainWindow", "Spacefarer"))
        # self.ThemeCombo.setItemText(9, _translate("MainWindow", "Xenoseeker"))
        # self.ThemeCombo.setItemText(10, _translate("MainWindow", "Themeless"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
