from .item import Armor, RangedWeapon, Weapon, Item

class ItemMeta(type):
    def __new__(cls, name, bases, attrs):
        cls_instance = super().__new__(cls, name, bases, attrs)
        cls_instance._all_weapons = []
        
        for attr_value in attrs.values():
            if isinstance(attr_value, Item):
                cls_instance._all_weapons.append(attr_value)
        
        return cls_instance

class RangedWeaponConstants(metaclass=ItemMeta):
    ZERO_PISTOL_FROSTBITE = RangedWeapon("Zero pistol, frostbite-class", 3060, 5, "Cold", "1d6", "Staggered", 60, 20, 1)
    ZERO_PISTOL_HAILSTORM = RangedWeapon('Zero pistol, hailstorm-class', 16900, 10, 'Cold', '2d6', 'Staggered', 60, 40, 2)
    ZERO_PISTOL_BLIZZARD = RangedWeapon('Zero pistol, blizzard-class', 94500, 15, 'Cold', '4d6', 'Staggered', 60, 40, 2)
    ZERO_PISTOL_AVALANCHE = RangedWeapon('Zero pistol, avalanche-class', 492900, 19, 'Cold', '6d6', 'Staggered', 60, 80, 4)

    CAUSTOJECT_LIQUIDATOR = RangedWeapon('Caustoject, liquidator', 225, 1, 'Acid', '1d4', 'Injection DC +2', 30, 20, 2)
    GLOVE_NEEDLER_TACTICAL = RangedWeapon('Glove needler, tactical', 560, 2, 'Acid', '1d4', 'Injection DC +2', 0, 1, 1)
    CAUSTOJECT_DECIMATOR = RangedWeapon('Caustoject, decimator', 4000, 6, 'Acid', '1d8', 'Injection DC +2', 30, 20, 2)
    GLOVE_NEEDLER_ADVANCED = RangedWeapon('Glove needler, advanced', 5800, 7, 'Acid', '1d12', 'Injection DC +2', 0, 1, 1)
    CAUSTOJECT_EXECUTIONER = RangedWeapon('Caustoject, executioner', 32900, 12, 'Acid', '4d4', 'Injection DC +2', 30, 20, 2)
    GLOVE_NEEDLER_ELITE = RangedWeapon('Glove needler, elite', 69300, 14, 'Acid', '3d12', 'Injection DC +2', 0, 1, 1)

    FLARE_GUN_SURVIVAL = RangedWeapon('Flare gun, survival', 90, 1, 'Fire', '1d3', 'Burn 1d6', 30, 1, 1)
    FLAME_PISTOL = RangedWeapon('Flame pistol', 470, 2, 'Fire', '1d4', 'Burn 1d4', 20, 20, 4)
    LASER_PISTOL_AZIMUTH = RangedWeapon('Laser pistol, azimuth', 350, 1, 'Fire', '1d4', 'Burn 1d4', 80, 20, 1)
    LASER_PISTOL_CORONA = RangedWeapon('Laser pistol, corona', 4270, 6, 'Fire', '2d4', 'Burn 1d4', 90, 20, 1)
    LASER_PISTOL_APHELION = RangedWeapon('Laser pistol, aphelion', 14820, 9, 'Fire', '3d4', 'Burn 1d4', 90, 40, 2)
    LASER_PISTOL_PERIHELION = RangedWeapon('Laser pistol, perihelion', 40200, 12, 'Fire', '4d4', 'Burn 2d4', 90, 40, 2)
    LASER_PISTOL_PARALLAX = RangedWeapon('Laser pistol, parallax', 82000, 14, 'Fire', '5d4', 'Burn 3d4', 90, 80, 4)
    LASER_PISTOL_ZENITH = RangedWeapon('Laser pistol, zenith', 245200, 17, 'Fire', '8d4', 'Burn 4d4', 100, 80, 4)

    PLASMA_PISTOL_RED_STAR = RangedWeapon('Plasma pistol, red star', 7200, 7, 'Electricity', '1d8', 'Burn 1d8', 20, 20, 4)
    PLASMA_PISTOL_YELLOW_STAR = RangedWeapon('Plasma pistol, yellow star', 40300, 12, 'Electricity', '2d8', 'Burn 1d8', 25, 40, 8)
    PLASMA_PISTOL_WHITE_STAR = RangedWeapon('Plasma pistol, white star', 107500, 15, 'Electricity', '3d8', 'Burn 2d8', 30, 100, 20)
    PLASMA_PISTOL_BLUE_STAR = RangedWeapon('Plasma pistol, blue star', 565000, 19, 'Electricity', '5d8', 'Burn 3d8', 40, 100, 20)

    SEMI_AUTO_PISTOL_TACTICAL = RangedWeapon('Semi-Auto pistol, Tactical', 260, 1, 'Piercing', '1d6', None, 30, 9, 1)
    SEMI_AUTO_PISTOL_ADVANCED = RangedWeapon('Semi-Auto pistol, advanced', 5500, 7, 'Piercing', '2d6', None, 60, 12, 1)
    SEMI_AUTO_PISTOL_ELITE = RangedWeapon('Semi-Auto pistol, elite', 18200, 10, 'Piercing', '3d6', None, 60, 12, 1)
    SEMI_AUTO_PISTOL_PARAGON = RangedWeapon('Semi-Auto pistol, paragon', 45200, 13, 'Piercing', '4d6', None, 60, 16, 1)
    GYROJET_PISTOL_TACTICAL = RangedWeapon('Gyrojet pistol, tactical', 91500, 15, 'Bludgeoning', '3d12', 'Knockdown', 80, 8, 1)
    GYROJET_PISTOL_ADVANCED = RangedWeapon('Gyrojet pistol, advanced', 212700, 17, 'Bludgeoning', '4d12', 'Knockdown', 80, 8, 1)
    GYROJET_PISTOL_ELITE = RangedWeapon('Gyrojet pistol, elite', 715800, 20, 'Bludgeoning', '5d12', 'Knockdown', 80, 8, 1)
    CESTUS_PISTOL_TACTICAL = RangedWeapon('Cestus pistol, tactical', 250, 1, 'Piercing', '1d4', None, 0, 1, 1)
    NEEDLER_PISTOL_TACTICAL = RangedWeapon('Needler Pistol, tactical', 175, 1, 'Piercing', '1d4', 'Injection DC +2', 40, 8, 1)
    NEEDLER_PISTOL_ADVANCED = RangedWeapon('Needler Pistol, advanced', 2700, 5, 'Piercing', '1d6', 'Injection DC +2', 40, 8, 1)
    CESTUS_PISTOL_ADVANCED = RangedWeapon('Cestus pistol, advanced', 4170, 6, 'Piercing', '1d12', 'Bleed 1d4', 0, 1, 1)
    NEEDLER_PISTOL_ELITE = RangedWeapon('Needler Pistol, elite', 17250, 10, 'Piercing', '2d8', 'Injection DC +2', 40, 8, 1)
    CESTUS_PISTOL_ELITE = RangedWeapon('Cestus pistol, elite', 24400, 11, 'Piercing', '3d12', 'Bleed 1d6', 0, 1, 1)
    NEEDLER_PISTOL_PARAGON = RangedWeapon('Needler Pistol, paragon', 94500, 15, 'Piercing', '6d6', 'Injection DC +2', 40, 8, 1)
    CESTUS_PISTOL_PARAGON = RangedWeapon('Cestus pistol, paragon', 162000, 16, 'Piercing', '6d12', 'Bleed 1d8', 0, 1, 1)
    NEEDLER_PISTOL_SUPREME = RangedWeapon('Needler Pistol, supreme', 725000, 20, 'Piercing', '8d8', 'Injection DC +2', 40, 8, 1)

    PULSECASTER_PISTOL = RangedWeapon('Pulsecaster pistol', 250, 1, 'Electricity', '1d4', None, 30, 20, 1)
    ARC_PISTOL_STATIC = RangedWeapon('Arc pistol, static', 750, 2, 'Electricity', '1d6', 'Arc 2', 50, 20, 2)
    ARC_PISTOL_AURORA = RangedWeapon('Arc pistol, aurora', 45700, 13, 'Electricity', '3d6', 'Arc 2d6', 50, 40, 2)
    ARC_PISTOL_STORM = RangedWeapon('Arc pistol, storm', 365500, 18, 'Electricity', '3d12', 'Arc 4d6', 50, 100, 10)

    SONIC_PISTOL_THUNDERSTRIKE = RangedWeapon('Sonic Pistol, thunderstrike', 2300, 4, 'Sonic', '1d8', 'Deafen', 40, 20, 2)
    SONIC_PISTOL_LFD = RangedWeapon('Sonic Pistol, LFD', 26200, 11, 'Sonic', '2d8', 'Deafen', 40, 40, 4)
    SONIC_PISTOL_HFD = RangedWeapon('Sonic Pistol, HFD', 71300, 14, 'Sonic', '3d8', 'Deafen', 40, 60, 6)
    SONIC_PISTOL_BANSHEE = RangedWeapon('Sonic Pistol, banshee', 191000, 16, 'Sonic', '4d8', 'Deafen', 40, 80, 8)

    NEEDLER_PISTOL = RangedWeapon('Needler Pistol', 105, 1, 'Piercing', '1d4', 'Injection DC +2', 30, 6, 1)
    NIGHTARCH_NEEDLER_TACTICAL = RangedWeapon('Nightarch Needler; tactical', 1650, 3, 'Piercing', '1d6', 'Injection DC +2', 30, 5, 1)
    NIGHTARCH_NEEDLER_ADVANCED = RangedWeapon('Nightarch Needler; advanced', 6720, 8, 'Piercing', '2d6', 'Injection DC +2', 30, 5, 1)
    NIGHTARCH_NEEDLER_ELITE = RangedWeapon('Nightarch Needler; elite', 44980, 13, 'Piercing', '4d6', 'Injection DC +2', 30, 5, 1)
    NIGHTARCH_NEEDLER_PARAGON = RangedWeapon('Nightarch Needler; paragon', 369000, 18, 'Piercing', '8d6', 'Injection DC +2', 30, 5, 1)

    ZERO_RIFLE_FROSTBITE = RangedWeapon('Zero rifle, frostbite-class', 2330, 4, 'Cold', '1d8', 'Staggered', 60, 40, 2)
    ZERO_RIFLE_HAILSTORM = RangedWeapon('Zero rifle, hailstorm-class', 10100, 8, 'Cold', '2d8', 'Staggered', 60, 40, 2)
    ZERO_RIFLE_BLIZZARD = RangedWeapon('Zero rifle, blizzard-class', 79800, 14, 'Cold', '4d8', 'Staggered', 60, 80, 4)
    ZERO_RIFLE_AVALANCHE = RangedWeapon('Zero rifle, avalanche-class', 410200, 18, 'Cold', '7d8', 'Staggered', 60, 100, 5)

    CAUSTOLANCE_LIQUIDATOR = RangedWeapon('Caustolance, liquidator', 400, 1, 'Acid', '1d6', 'Injection DC +2', 60, 20, 1)
    CAUSTOLANCE_DECIMATOR = RangedWeapon('Caustolance, decimator', 4500, 6, 'Acid', '2d6', 'Injection DC +2', 60, 20, 1)
    CAUSTOLANCE_EXECUTIONER = RangedWeapon('Caustolance, executioner', 38000, 12, 'Acid', '5d6', 'Injection DC +2', 60, 20, 1)
    CAUSTOLANCE_ERADICATOR = RangedWeapon('Caustolance, eradicator', 400000, 18, 'Acid', '12d6', 'Injection DC +2', 60, 20, 1)

    FLAME_RIFLE = RangedWeapon('Flame rifle', 490, 2, 'Fire', '1d6', 'Burn 1d6', 25, 20, 5)

    LASER_RIFLE_AZIMUTH = RangedWeapon('Laser rifle, azimuth', 425, 1, 'Fire', '1d8', 'Burn 1d6', 120, 20, 1)
    LASER_RIFLE_CORONA = RangedWeapon('Laser rifle, corona', 4650, 6, 'Fire', '2d6', 'Burn 1d6', 120, 40, 1)
    LASER_RIFLE_APHELION = RangedWeapon('Laser rifle, aphelion', 14300, 9, 'Fire', '3d6', 'Burn 1d6', 120, 40, 1)
    AUTOBEAM_RIFLE_TACTICAL = RangedWeapon('Autobeam rifle, Tactical', 26900, 11, 'Fire', '5d4', 'Burn 2d4', 60, 40, 4)
    LASER_RIFLE_PERIHELION = RangedWeapon('Laser rifle, perihelion', 53800, 13, 'Fire', '5d6', 'Burn 2d6', 130, 100, 2)
    AUTOBEAM_RIFLE_ADVANCED = RangedWeapon('Autobeam rifle, advanced', 95500, 15, 'Fire', '7d4', 'Burn 3d4', 60, 100, 10)
    LASER_RIFLE_PARALLAX = RangedWeapon('Laser rifle, parallax', 248000, 17, 'Fire', '8d6', 'Burn 4d6', 150, 100, 2)
    AUTOBEAM_RIFLE_ELITE = RangedWeapon('Autobeam rifle, elite', 548100, 19, 'Fire', '12d4', 'Burn 5d4', 60, 100, 5)
    LASER_RIFLE_ZENITH = RangedWeapon('Laser rifle, zenith', 722000, 20, 'Fire', '11d6', 'Burn 5d6', 150, 100, 2)

    PLASMA_RIFLE_RED_STAR = RangedWeapon('Plasma rifle, red star', 4600, 6, 'Electricity', '1d10', 'Burn 1d4', 40, 40, 4)
    PLASMA_RIFLE_YELLOW_STAR = RangedWeapon('Plasma rifle, yellow star', 16800, 10, 'Electricity', '2d10', 'Burn 1d8', 40, 40, 4)
    PLASMA_CASTER_WHITE_STAR = RangedWeapon('Plasma caster, white star', 49100, 13, 'Electricity', '3d10', 'Burn 1d10', 80, 100, 5)
    PLASMA_RIFLE_WHITE_STAR = RangedWeapon('Plasma rifle, white star', 126600, 15, 'Electricity', '4d10', 'Burn 2d8', 60, 40, 4)
    PLASMA_CASTER_BLUE_STAR = RangedWeapon('Plasma caster, blue star', 275000, 17, 'Electricity', '5d10', 'Burn 2d10', 80, 200, 10)
    PLASMA_RIFLE_BLUE_STAR = RangedWeapon('Plasma rifle, blue star', 935000, 20, 'Electricity', '8d10', 'Burn 4d8', 100, 100, 10)

    NEEDLER_RIFLE_TACTICAL = RangedWeapon('Needler Rifle, tactical', 200, 1, 'Piercing', '1d6', 'Injection DC +2', 70, 14, 1)
    NEEDLER_RIFLE_ADVANCED = RangedWeapon('Needler Rifle, advanced', 3000, 5, 'Piercing', '1d8', 'Injection DC +2', 70, 14, 1)
    NEEDLER_RIFLE_ELITE = RangedWeapon('Needler Rifle, elite', 18000, 10, 'Piercing', '4d6', 'Injection DC +2', 70, 14, 1)
    NEEDLER_RIFLE_PARAGON = RangedWeapon('Needler Rifle, paragon', 110000, 15, 'Piercing', '8d6', 'Injection DC +2', 70, 14, 1)
    NEEDLER_RIFLE_SUPREME = RangedWeapon('Needler Rifle, supreme', 850000, 20, 'Piercing', '16d6', 'Injection DC +2', 70, 14, 1)
    CAUSTOJECT_ERADICATOR = RangedWeapon('Caustoject, eradicator', 242300, 18, 'Acid', '6d8', 'Injection DC +2', 30, 20, 2)
    GLOVE_NEEDLER_PARAGON = RangedWeapon('Glove needler, paragon', 765000, 20, 'Acid', '6d12', 'Injection DC +2', 0, 1, 1)
    HUNTING_RIFLE = RangedWeapon('Hunting rifle', 240, 1, 'Piercing', '1d8', None, 90, 6, 1)
    SCATTERGUN_UTILITY = RangedWeapon('Scattergun, utility', 235, 1, 'Piercing', '1d4', None, 15, 4, 1)
    ACID_DART_RIFLE_TACTICAL = RangedWeapon('Acid dart rifle, Tactical', 485, 2, 'Acid', '1d8', 'Corrode', 80, 1, 10)
    AUTOTARGET_RIFLE = RangedWeapon('Autotarget rifle', 755, 2, 'Piercing', '1d6', None, 60, 10, 1)
    CROSSBOLTER_TACTICAL = RangedWeapon('Crossbolter, Tactical', 475, 2, 'Piercing', '1d10', None, 70, 1, 1)
    KALO_SHREDDER_SLIPSTREAM = RangedWeapon('Kalo shredder, slipstream-class', 1610, 3, 'Slashing', '1d6', 'Bleed 1d4', 30, 8, 1)
    ACID_DART_RIFLE_DUAL = RangedWeapon('Acid dart rifle, dual', 6900, 7, 'Acid', '2d8', 'Corrode 2d4', 90, 24, 2)
    KALO_SHREDDER_CASCADE = RangedWeapon('Kalo shredder, cascade-class', 6630, 7, 'Slashing', '2d6', 'Bleed 1d6', 40, 18, 1)
    SEEKER_RIFLE_TACTICAL = RangedWeapon('Seeker rifle, tactical', 6030, 7, 'Piercing', '2d8', None, 100, 8, 1)
    CROSSBOLTER_DUAL = RangedWeapon('Crossbolter, dual', 8250, 8, 'Piercing', '2d10', None, 70, 4, 2)
    SCATTERGUN_SNUB = RangedWeapon('Scattergun, snub', 8300, 8, 'Piercing', '1d12', None, 15, 8, 1)
    MAGNETAR_RIFLE_TACTICAL = RangedWeapon('Magnetar rifle, tactical', 11800, 9, 'Piercing', '2d8', None, 60, 18, 1)
    COMBAT_RIFLE = RangedWeapon('Combat rifle', 16500, 10, 'Piercing', '3d8', None, 90, 12, 1)
    KALO_SHREDDER_TORRENT = RangedWeapon('Kalo shredder, torrent-class', 26700, 11, 'Slashing', '4d6', 'Bleed 3d4', 40, 24, 1)
    ACID_DART_RIFLE_COMPLEX = RangedWeapon('Acid dart rifle, complex', 39200, 12, 'Acid', '4d8', 'Corrode 4d4', 90, 48, 4)
    SCATTERGUN_IMPACT = RangedWeapon('Scattergun, impact', 30400, 12, 'Piercing', '2d12', None, 15, 12, 1)
    GYROJET_RIFLE_TACTICAL = RangedWeapon('Gyrojet rifle, Tactical', 54000, 13, 'Bludgeoning', '3d12', 'Knockdown', 100, 12, 1)
    MAGNETAR_RIFLE_ADVANCED = RangedWeapon('Magnetar rifle, advanced', 53700, 13, 'Piercing', '4d8', None, 60, 24, 1)
    KALO_SHREDDER_DELUGE = RangedWeapon('Kalo shredder, deluge-class', 74300, 14, 'Slashing', '6d6', 'Bleed 4d4', 60, 36, 1)
    SEEKER_RIFLE_ADVANCED = RangedWeapon('Seeker rifle, advanced', 72300, 14, 'Piercing', '6d8', None, 100, 18, 1)
    GYROJET_RIFLE_ADVANCED = RangedWeapon('Gyrojet rifle, advanced', 122800, 15, 'Bludgeoning', '5d12', 'Knockdown', 120, 12, 1)
    SCATTERGUN_VORTEX = RangedWeapon('Scattergun, vortex', 91900, 15, 'Piercing', '3d12', None, 30, 12, 1)
    MAGNETAR_RIFLE_ELITE = RangedWeapon('Magnetar rifle, elite', 185100, 16, 'Piercing', '6d8', None, 120, 36, 1)
    GYROJET_RIFLE_ELITE = RangedWeapon('Gyrojet rifle, elite', 245600, 17, 'Bludgeoning', '6d12', 'Knockdown', 120, 12, 1)
    KALO_SHREDDER_MONSOON = RangedWeapon('Kalo shredder, monsoon-class', 784000, 17, 'Slashing', '12d6', 'Bleed 4d6', 60, 48, 1)
    SEEKER_RIFLE_ELITE = RangedWeapon('Seeker rifle, elite', 242500, 17, 'Piercing', '9d8', None, 100, 18, 1)
    SCATTERGUN_GRAPESHOT = RangedWeapon('Scattergun, grapeshot', 331000, 18, 'Piercing', '4d12', None, 30, 12, 1)
    MAGNETAR_RIFLE_PARAGON = RangedWeapon('Magnetar rifle, paragon', 612600, 19, 'Piercing', '8d8', None, 120, 48, 1)
    GYROJET_RIFLE_PARAGON = RangedWeapon('Gyrojet rifle, paragon', 723500, 20, 'Bludgeoning', '8d12', 'Knockdown', 120, 12, 1)
    SEEKER_RIFLE_PARAGON = RangedWeapon('Seeker rifle, paragon', 809200, 20, 'Piercing', '12d8', None, 100, 24, 1)
    PULSECASTER_RIFLE = RangedWeapon('Pulsecaster rifle', 100, 1, 'Electricity', '1d6', None, 50, 40, 2)
    ARC_EMITTER_TACTICAL = RangedWeapon('Arc emitter, Tactical', 750, 2, 'Electricity', '1d4', None, 15, 20, 4)
    ARC_RIFLE_STATIC = RangedWeapon('Arc rifle, static', 4200, 6, 'Electricity', '1d12', 'Arc 1d6', 70, 40, 1)
    ARC_EMITTER_ADVANCED = RangedWeapon('Arc emitter, advanced', 13200, 9, 'Electricity', '2d4', None, 30, 40, 10)
    ARC_RIFLE_AURORA = RangedWeapon('Arc rifle, aurora', 24500, 11, 'Electricity', '2d12', 'Arc 2d6', 70, 40, 1)
    ARC_RIFLE_STORM = RangedWeapon('Arc rifle, storm', 190300, 16, 'Electricity', '4d12', 'Arc 4d6', 80, 80, 2)
    ARC_RIFLE_TEMPEST = RangedWeapon('Arc rifle, tempest', 622000, 19, 'Electricity', '6d12', 'Arc 6d6', 80, 100, 2)

    SONIC_RIFLE_THUNDERSTRIKE = RangedWeapon('Sonic Rifle, thunderstrike', 3400, 5, 'Sonic', '1d10', 'Deafen', 50, 40, 2)
    STREETSWEEPER_THUNDERSTRIKE = RangedWeapon('Streetsweeper, thunderstrike', 7150, 7, 'Sonic', '1d10', 'Knockdown', 50, 40, 5)
    SONIC_RIFLE_LFD = RangedWeapon('Sonic Rifle, LFD', 17000, 10, 'Sonic', '2d10', 'Deafen', 50, 40, 2)
    STREETSWEEPER_LFD = RangedWeapon('Streetsweeper, LFD', 39300, 12, 'Sonic', '3d10', 'Knockdown', 50, 40, 5)
    SONIC_RIFLE_HFD = RangedWeapon('Sonic Rifle, HFD', 80200, 14, 'Sonic', '4d10', 'Deafen', 50, 80, 4)
    STREETSWEEPER_HFD = RangedWeapon('Streetsweeper, HFD', 195000, 16, 'Sonic', '5d10', 'Knockdown', 50, 40, 5)
    SONIC_RIFLE_BANSHEE = RangedWeapon('Sonic Rifle, banshee', 364500, 18, 'Sonic', '6d10', 'Deafen', 50, 100, 5)

    NEEDLER_RIFLE = RangedWeapon('Needler Rifle', 110, 1, 'Piercing', '1d6', 'Injection DC +2', 60, 12, 1)

    ZERO_CANNON_TACTICAL = RangedWeapon('Zero cannon, Tactical', 23000, 11, 'Cold', '3d8', 'Staggered', 60, 80, 4)
    ZERO_CANNON_ADVANCED = RangedWeapon('Zero cannon, advanced', 81400, 14, 'Cold', '5d8', 'Staggered', 60, 100, 5)
    ZERO_CANNON_ELITE = RangedWeapon('Zero cannon, elite', 412800, 18, 'Cold', '8d8', 'Staggered', 80, 100, 5)

    FLAMETHROWER_IFRIT = RangedWeapon('Flamethrower, ifrit-class', 780, 2, 'Fire', '1d6', 'Burn 1d6', 15, 20, 4)
    FLAMETHROWER_SALAMANDER = RangedWeapon('Flamethrower, salamander-class', 8600, 8, 'Fire', '2d6', 'Burn 2d6', 30, 20, 5)
    FLAMETHROWER_HELLHOUND = RangedWeapon('Flamethrower, hellhound-class', 35100, 12, 'Fire', '4d6', 'Burn 4d6', 30, 40, 8)
    FLAMETHROWER_FIREDRAKE = RangedWeapon('Flamethrower, firedrake-class', 128000, 15, 'Fire', '6d6', 'Burn 6d6', 30, 40, 10)
    FLAMETHROWER_PHOENIX = RangedWeapon('Flamethrower, phoenix-class', 367500, 18, 'Fire', '9d6', 'Burn 9d6', 30, 40, 10)

    ARTILLERY_LASER_AZIMUTH = RangedWeapon('Artillery laser, azimuth', 425, 1, 'Fire', '1d10', 'Burn 1d6', 120, 20, 2)
    ARTILLERY_LASER_CORONA = RangedWeapon('Artillery laser, corona', 4650, 6, 'Fire', '2d8', 'Burn 1d6', 120, 40, 4)
    ARTILLERY_LASER_APHELION = RangedWeapon('Artillery laser, aphelion', 14300, 9, 'Fire', '3d8', 'Burn 1d6', 120, 40, 4)
    AUTOBEAM_ARTILLERY_TACTICAL = RangedWeapon('Autobeam artillery, tactical', 19400, 10, 'Fire', '2d8', 'Burn 1d8', 120, 40, 1)
    ARTILLERY_LASER_PERIHELION = RangedWeapon('Artillery laser, perihelion', 53800, 13, 'Fire', '4d8', 'Burn 2d6', 130, 100, 5)
    AUTOBEAM_ARTILLERY_ADVANCED = RangedWeapon('Autobeam artillery, advanced', 145700, 16, 'Fire', '4d8', 'Burn 2d8', 120, 40, 1)
    ARTILLERY_LASER_PARALLAX = RangedWeapon('Artillery laser, parallax', 248000, 17, 'Fire', '7d8', 'Burn 4d6', 150, 100, 5)
    AUTOBEAM_ARTILLERY_ELITE = RangedWeapon('Autobeam artillery, elite', 543300, 19, 'Fire', '6d8', 'Burn 2d10', 120, 40, 1)
    ARTILLERY_LASER_ZENITH = RangedWeapon('Artillery laser, zenith', 722000, 20, 'Fire', '9d8', 'Burn 5d6', 150, 100, 5)

    STARHEART_CANNON_RED_STAR = RangedWeapon('Starheart cannon, red star', 1300, 3, 'Electricity', '1d6', 'Blind', 100, 40, 5)
    PLASMA_CANNON_RED_STAR = RangedWeapon('Plasma cannon, red star', 8650, 8, 'Electricity', '2d10', 'Blind', 100, 100, 5)
    STARHEART_CANNON_YELLOW_STAR = RangedWeapon('Starheart cannon, yellow star', 9050, 8, 'Electricity', '3d6', 'Blind', 100, 40, 5)
    STARHEART_CANNON_WHITE_STAR = RangedWeapon('Starheart cannon, white star', 48100, 13, 'Electricity', '2d10', 'Blind', 100, 100, 5)
    PLASMA_CANNON_YELLOW_STAR = RangedWeapon('Plasma cannon, yellow star', 62800, 14, 'Electricity', '4d10', 'Burn 2d8', 100, 100, 5)
    PLASMA_CANNON_WHITE_STAR = RangedWeapon('Plasma cannon, white star', 189200, 16, 'Electricity', '6d10', 'Burn 3d8', 100, 100, 5)
    STARHEART_CANNON_BLUE_STAR = RangedWeapon('Starheart cannon, blue star', 360000, 18, 'Electricity', '9d6', 'Blind', 100, 100, 10)
    PLASMA_CANNON_BLUE_STAR = RangedWeapon('Plasma cannon, blue star', 950000, 20, 'Electricity', '8d10', 'Burn 4d8', 100, 100, 10)

    REACTION_CANNON_LIGHT = RangedWeapon('Reaction cannon, light', 250, 1, 'Piercing', '1d10', None, 90, 6, 1)
    MACHINE_GUN_SQUAD = RangedWeapon('Machine gun, squad', 2060, 4, 'Piercing', '1d10', None, 60, 40, 2)
    X_GEN_GUN_TACTICAL = RangedWeapon('X-Gen gun, Tactical', 4240, 6, 'Piercing', '1d12', None, 120, 80, 2)
    REACTION_CANNON_TACTICAL = RangedWeapon('Reaction cannon, Tactical', 6100, 7, 'Piercing', '2d10', None, 90, 6, 1)
    MACHINE_GUN_LIGHT = RangedWeapon('Machine gun, light', 8600, 8, 'Piercing', '2d10', None, 60, 60, 2)
    X_GEN_GUN_ADVANCED = RangedWeapon('X-Gen gun, advanced', 13100, 9, 'Piercing', '2d12', None, 120, 100, 2)
    REACTION_CANNON_HEAVY = RangedWeapon('Reaction cannon, heavy', 16750, 10, 'Piercing', '3d10', None, 100, 6, 1)
    STELLAR_CANNON_LIGHT = RangedWeapon('Stellar cannon, light', 19200, 10, 'Piercing', '2d12', 'Wound', 30, 18, 6)
    CROSSBOLTER_ADVANCED = RangedWeapon('Crossbolter, advanced', 21900, 11, 'Piercing', '4d10', None, 70, 12, 4)
    MACHINE_GUN_MEDIUM = RangedWeapon('Machine gun, medium', 23100, 11, 'Piercing', '3d10', None, 60, 60, 2)
    X_GEN_GUN_ELITE = RangedWeapon('X-Gen gun, elite', 53700, 13, 'Piercing', '4d12', None, 120, 100, 2)
    CROSSBOLTER_ELITE = RangedWeapon('Crossbolter, elite', 71400, 14, 'Piercing', '6d10', None, 60, 30, 6)
    REACTION_CANNON_ADVANCED = RangedWeapon('Reaction cannon, advanced', 73000, 14, 'Piercing', '6d10', None, 100, 6, 1)
    STELLAR_CANNON_HEAVY = RangedWeapon('Stellar cannon, heavy', 122800, 15, 'Piercing', '4d12', 'Wound', 30, 32, 8)
    MACHINE_GUN_HEAVY = RangedWeapon('Machine gun, heavy', 220300, 17, 'Piercing', '7d10', None, 120, 100, 4)
    REACTION_CANNON_ELITE = RangedWeapon('Reaction cannon, elite', 244000, 17, 'Piercing', '8d10', None, 100, 6, 1)
    CROSSBOLTER_PARAGON = RangedWeapon('Crossbolter, paragon', 327200, 18, 'Piercing', '10d10', None, 60, 40, 8)
    REACTION_CANNON_PARAGON = RangedWeapon('Reaction cannon, paragon', 810000, 20, 'Piercing', '12d10', None, 100, 6, 1)
    X_GEN_GUN_PARAGON = RangedWeapon('X-Gen gun, paragon', 826000, 20, 'Piercing', '9d12', None, 120, 100, 2)

    ANACITE_ION_CANNON_STATIC = RangedWeapon('Anacite ion cannon, static', 1550, 3, 'Electricity', '1d10', 'Staggered', 20, 20, 2)
    SHOCK_CASTER_STATIC = RangedWeapon('Shock caster, static', 4620, 6, 'Electricity', '1d12', None, 40, 40, 2)
    ANACITE_ION_CANNON_AURORA = RangedWeapon('Anacite ion cannon, aurora', 10900, 8, 'Electricity', '2d10', 'Staggered', 45, 40, 4)
    SHOCK_CASTER_AURORA = RangedWeapon('Shock caster, aurora', 19100, 10, 'Electricity', '2d12', None, 40, 40, 4)
    ANACITE_ION_CANNON_STORM = RangedWeapon('Anacite ion cannon, storm', 52900, 13, 'Electricity', '4d10', 'Staggered', 75, 80, 5)
    SHOCK_CASTER_STORM = RangedWeapon('Shock caster, storm', 164800, 16, 'Electricity', '5d12', None, 40, 100, 10)
    ANACITE_ION_CANNON_TEMPEST = RangedWeapon('Anacite ion cannon, tempest', 441000, 18, 'Electricity', '6d10', 'Staggered', 100, 100, 10)
    SHOCK_CASTER_TEMPEST = RangedWeapon('Shock caster, tempest', 735000, 20, 'Electricity', '7d12', None, 40, 100, 10)

    SCREAMER_THUNDERSTRIKE = RangedWeapon('Screamer, thunderstrike', 3350, 5, 'Sonic', '1d10', 'Deafen', 30, 40, 4)
    SCREAMER_LFD = RangedWeapon('Screamer, LFD', 14000, 9, 'Sonic', '2d10', 'Deafen', 60, 80, 8)
    SCREAMER_HFD = RangedWeapon('Screamer, HFD', 107500, 15, 'Sonic', '4d10', 'Deafen', 60, 100, 10)

    SHOBHAD_HORIZON_STRIKER_TACTICAL = RangedWeapon('Shobhad horizon striker, tactical', 440, 1, 'Piercing', '2d4', None, 100, 2, 1)
    SHIRREN_EYE_RIFLE_TACTICAL = RangedWeapon('Shirren-eye rifle, tactical', 755, 2, 'Piercing', '1d10', None, 70, 1, 1)
    SHOBHAD_HORIZON_STRIKER_ADVANCED = RangedWeapon('Shobhad horizon striker, advanced', 4750, 6, 'Piercing', '3d4', None, 120, 2, 1)
    SHIRREN_EYE_RIFLE_ADVANCED = RangedWeapon('Shirren-eye rifle, advanced', 9350, 8, 'Piercing', '2d10', None, 70, 4, 1)
    SHOBHAD_HORIZON_STRIKER_ELITE = RangedWeapon('Shobhad horizon striker, elite', 27300, 11, 'Piercing', '6d4', None, 140, 2, 1)
    SHIRREN_EYE_RIFLE_ELITE = RangedWeapon('Shirren-eye rifle, elite', 54000, 13, 'Piercing', '4d10', None, 80, 6, 1)
    SHIRREN_EYE_RIFLE_PARAGON = RangedWeapon('Shirren-eye rifle, paragon', 147200, 16, 'Piercing', '6d10', None, 80, 6, 1)
    SHOBHAD_HORIZON_STRIKER_PARAGON = RangedWeapon('Shobhad horizon striker, paragon', 185000, 16, 'Piercing', '8d8', None, 160, 2, 1)
    SHIRREN_EYE_RIFLE_WARPSHOT = RangedWeapon('Shirren-eye rifle, warpshot', 740800, 20, 'Piercing', '10d10', None, 80, 4, 1)

class MeleeWeapon(metaclass=ItemMeta):
    BATON_TACTICAL = Weapon('Baton, Tactical', 90, 1, 'Bludgeoning', '1d4', None)
    BATTLEGLOVE_CESTUS = Weapon('Battleglove, cestus', 100, 1, 'Bludgeoning', '1d4', None)
    KNIFE_SURVIVAL = Weapon('Knife, survival', 95, 1, 'Slashing', '1d4', None)
    SWORD_CANE_TACTICAL = Weapon('Sword cane, tactical', 250, 1, 'Piercing', '1d4', 'Bleed 1d3')
    DUELING_SWORD_TACTICAL = Weapon('Dueling Sword, tactical', 475, 2, 'Slashing', '1d6', None)
    SWORD_CANE_ADVANCED = Weapon('Sword cane, advanced', 2100, 4, 'Piercing', '1d4', 'Bleed 1d4')
    KNIFE_TACTICAL = Weapon('Knife, tactical', 6000, 7, 'Slashing', '2d4', None)
    SWORD_CANE_ULTRATHIN = Weapon('Sword cane, ultrathin', 7000, 7, 'Piercing', '2d4', 'Bleed 1d3')
    DUELING_SWORD_BUZZBLADE = Weapon('Dueling Sword, buzzblade', 9500, 8, 'Slashing', '2d6', None)
    INCAPACITATOR = Weapon('Incapacitator', 14200, 9, 'Bludgeoning', '3d4', 'Staggered')
    BATTLEGLOVE_POWER = Weapon('Battleglove, power', 16100, 10, 'Bludgeoning', '2d8', None)
    SWORD_CANE_ZERO_EDGE = Weapon('Sword cane, zero-Edge', 18000, 10, 'Piercing', '2d6', 'Bleed 1d6')
    DUELING_SWORD_ULTRATHIN = Weapon('Dueling Sword, ultrathin', 26000, 11, 'Slashing', '3d6', None)
    DAGGER_ULTRATHIN = Weapon('Dagger, ultrathin', 32800, 12, 'Slashing', '4d4', None)
    BATTLEGLOVE_NOVA = Weapon('Battleglove, nova', 52500, 13, 'Bludgeoning', '3d10', None)
    SWORD_CANE_MOLECULAR_RIFT = Weapon('Sword cane, molecular rift', 50900, 13, 'Piercing', '3d8', 'Bleed 1d8')
    DAGGER_ZERO_EDGE = Weapon('Dagger, zero-edge', 64400, 14, 'Slashing', '6d4', None)
    DUELING_SWORD_RIPPER = Weapon('Dueling Sword, ripper', 109250, 15, 'Slashing', '7d6', None)
    PEACEMAKER = Weapon('Peacemaker', 185300, 16, 'Bludgeoning', '6d6', 'Knockdown')
    SWORD_CANE_MOLECULAR_RIFT = Weapon('Sword cane, molecular rift', 160000, 16, 'Piercing', '5d8', 'Bleed 2d6')
    BATTLEGLOVE_GRAVITY = Weapon('Battleglove, gravity', 214850, 17, 'Bludgeoning', '5d10', None)
    DAGGER_MOLECULAR_RIFT = Weapon('Dagger, molecular rift', 275000, 17, 'Slashing', '10d4', None)
    DUELING_SWORD_MOLECULAR_RIFT = Weapon('Dueling Sword, molecular rift', 331200, 18, 'Slashing', '10d6', None)
    BATON_ADVANCED = Weapon('Baton, advanced', 540000, 19, 'Bludgeoning', '8d6', None)
    SYRINGE_STICK_STANDARD = Weapon('Syringe stick, standard', 125, 1, 'Piercing', '1d3', None)
    SYRINGE_STICK_SHARP_POINTED = Weapon('Syringe stick, sharp-pointed', 2650, 5, 'Piercing', '1d4', 'Injection DC +2')
    SYRINGE_STICK_HYPER_POINTED = Weapon('Syringe stick, hyper-pointed', 12000, 9, 'Piercing', '2d4', 'Injection DC +2')
    SYRINGE_STICK_ULTRA_POINTED = Weapon('Syringe stick, ultra-pointed', 46000, 13, 'Piercing', '5d4', 'Injection DC +2')
    SYRINGE_STICK_SUPREME_POINTED = Weapon('Syringe stick, supreme-pointed', 225000, 17, 'Piercing', '10d4', 'Injection DC +2')

    SPEAR_TACTICAL = Weapon('Spear, Tactical', 375, 1, 'Piercing', '1d6', None)
    STAFF_BATTLE = Weapon('Staff, battle', 80, 1, 'Bludgeoning', '1d4', 'Knockdown')
    STAFF_CARBON = Weapon('Staff, carbon', 6150, 7, 'Bludgeoning', '1d8', 'Knockdown')
    SPEAR_SENTINEL = Weapon('Spear, sentinel', 10000, 8, 'Piercing', '2d6', None)
    SPEAR_BUZZBLADE = Weapon('Spear, buzzblade', 22650, 11, 'Piercing', '3d6', None)
    SPEAR_ZERO_EDGE = Weapon('Spear, zero-edge', 107350, 15, 'Piercing', '7d6', None)
    STAFF_HARDLIGHT = Weapon('Staff, hardlight', 320800, 18, 'Bludgeoning', '8d8', 'Knockdown')
    SPEAR_GRAVITY = Weapon('Spear, gravity', 552000, 19, 'Piercing', '12d6', None)
    SYRINGE_SPEAR_TACTICAL = Weapon('Syringe spear, tactical', 250, 1, 'Piercing', '1d6', 'Injection DC +2')
    SYRINGE_SPEAR_ADVANCED = Weapon('Syringe spear, advanced', 4250, 6, 'Piercing', '1d8', 'Injection DC +2')
    SYRINGE_SPEAR_ELITE = Weapon('Syringe spear, elite', 25000, 11, 'Piercing', '3d10', 'Injection DC +2')
    SYRINGE_SPEAR_PARAGON = Weapon('Syringe spear, paragon', 165000, 16, 'Piercing', '9d8', 'Injection DC +2')

    STARFIRE_SWORD_TACTICAL = Weapon('Starfire sword, tactical', 6120, 7, 'Fire', '2d4', 'Burn 1d8')
    STARFIRE_SWORD_INFERNO = Weapon('Starfire sword, inferno', 246000, 17, 'Fire', '7d8', 'Burn 4d12')

    PLASMA_SWORD_TACTICAL = Weapon('Plasma sword, tactical', 14550, 9, 'Electricity', '2d8', 'Severe wound')
    PLASMA_SWORD_RED_STAR = Weapon('Plasma sword, red star', 54300, 13, 'Electricity', '4d8', 'Severe wound')
    PLASMA_SWORD_YELLOW_STAR = Weapon('Plasma sword, yellow star', 127000, 15, 'Electricity', '5d8', 'Severe wound')
    PLASMA_SWORD_WHITE_STAR = Weapon('Plasma sword, white star', 415600, 18, 'Electricity', '8d8', 'Severe wound')
    PLASMA_SWORD_BLUE_STAR = Weapon('Plasma sword, blue star', 920250, 20, 'Electricity', '10d8', 'Severe wound')

    SHOCK_TRUNCHEON_STATIC = Weapon('Shock truncheon, static', 9150, 8, 'Electricity', '1d12', 'Arc 1d4')
    SHOCK_TRUNCHEON_AURORA = Weapon('Shock truncheon, aurora', 23000, 11, 'Electricity', '2d12', 'Arc 2d4')
    SHOCK_TRUNCHEON_STORM = Weapon('Shock truncheon, storm', 80200, 16, 'Electricity', '3d12', 'Arc 3d4')
    SHOCK_TRUNCHEON_TEMPEST = Weapon('Shock truncheon, tempest', 545000, 19, 'Electricity', '6d12', 'Arc 6d4')

    PULSE_GAUNTLET_THUNDERSTRIKE = Weapon('Pulse Gauntlet, thunderstrike', 475, 2, 'Bludgeoning', '1d6', 'Knockdown')
    PULSE_GAUNTLET_LFD = Weapon('Pulse Gauntlet, LFD', 7340, 7, 'Bludgeoning', '2d6', 'Knockdown')
    PULSE_GAUNTLET_HFD = Weapon('Pulse Gauntlet, HFD', 31300, 12, 'Bludgeoning', '5d6', 'Knockdown')
    PULSE_GAUNTLET_BANSHEE = Weapon('Pulse Gauntlet, banshee', 148200, 16, 'Bludgeoning', '10d6', 'Knockdown')
    NEEDLER_ESTOC_STANDARD = Weapon('Needler estoc, standard', 175, 2, 'Piercing', '1d6', 'Injection DC +2')
    NEEDLER_ESTOC_SHARP_POINTED = Weapon('Needler estoc, sharp-pointed', 4000, 6, 'Piercing', '1d8', 'Injection DC +2')
    NEEDLER_ESTOC_HYPER_POINTED = Weapon('Needler estoc, hyper-pointed', 17500, 10, 'Piercing', '4d6', 'Injection DC +2')
    NEEDLER_ESTOC_ULTRA_POINTED = Weapon('Needler estoc, ultra-pointed', 67000, 14, 'Piercing', '9d6', 'Injection DC +2')
    NEEDLER_ESTOC_SUPREME_POINTED = Weapon('Needler estoc, supreme-pointed', 342000, 18, 'Piercing', '14d6', 'Injection DC +2')
    NEEDLER_ESTOC_MASTER_POINTED = Weapon('Needler estoc, master-pointed', 750000, 20, 'Piercing', '18d6', 'Injection DC +2')

    HAMMER_ASSAULT = Weapon('Hammer, assault', 95, 1, 'Bludgeoning', '1d6', None)
    HARDLIGHT_HAND_WRAP_DIFFUSE = Weapon('Hardlight hand wrap, diffuse', 3180, 5, 'Bludgeoning', '1d6', None)
    HARDLIGHT_HAND_WRAP_AMBIENT = Weapon('Hardlight hand wrap, ambient', 13100, 9, 'Bludgeoning', '2d8', None)
    HARDLIGHT_HAND_WRAP_NATURAL = Weapon('Hardlight hand wrap, natural', 75000, 14, 'Bludgeoning', '4d10', None)
    HARDLIGHT_HAND_WRAP_FLUORESCENT = Weapon('Hardlight hand wrap, fluorescent', 250000, 17, 'Bludgeoning', '6d10', None)
    HARDLIGHT_HAND_WRAP_INCANDESCENT = Weapon('Hardlight hand wrap, incandescent', 880000, 20, 'Bludgeoning', '11d8', None)
    LONGSWORD = Weapon('Longsword', 375, 1, 'Slashing', '1d8', None)
    STARKNIFE_TACTICAL = Weapon('Starknife, Tactical', 110, 1, 'Piercing', '1d4', None)
    TACLASH_STANDARD = Weapon('Taclash, standard', 240, 1, 'Slashing', '1d4', None)
    INJECTION_GLOVE = Weapon('Injection Glove', 490, 2, 'Piercing', '1d4', 'Injection DC +2')
    XENOLASH_IMMATURE = Weapon('Xenolash, immature', 2430, 4, 'Acid', '2d4', 'Corrode 1d4')
    FANGBLADE = Weapon('Fangblade', 5430, 7, 'Slashing', '1d12', 'Bleed 1d8')
    LONGSWORD_SINTERED = Weapon('Longsword, Sintered', 8420, 7, 'Slashing', '2d8', None)
    STARKNIFE_SINTERED = Weapon('Starknife, sintered', 9810, 8, 'Piercing', '4d4', None)
    LONGSWORD_MICROSERRATED = Weapon('Longsword, microserrated', 12100, 9, 'Slashing', '2d10', 'Bleed 2d6')
    HAMMER_COMET = Weapon('Hammer, comet', 16900, 10, 'Bludgeoning', '4d6', None)
    XENOLASH_MATURE = Weapon('Xenolash, mature', 17000, 10, 'Acid', '5d4', 'Corrode 2d4')
    LONGSWORD_ULTRATHIN = Weapon('Longsword, Ultrathin', 26300, 11, 'Slashing', '4d8', None)
    TACLASH_NUMBING = Weapon('Taclash, numbing', 24800, 11, 'Slashing', '5d4', None)
    STARKNIFE_ACCELERATED = Weapon('Starknife, accelerated', 40400, 12, 'Fire', '4d8', None)
    GRINDBLADE = Weapon('Grindblade', 45700, 13, 'Slashing', '4d10', 'Bleed 2d8')
    LONGSWORD_ZERO_EDGE = Weapon('Longsword, Zero-Edge', 79500, 14, 'Slashing', '7d8', 'Severe wound')
    XENOLASH_BLOOMING = Weapon('Xenolash, blooming', 70000, 14, 'Acid', '9d4', 'Corrode 4d4')
    MONOWHIP = Weapon('Monowhip', 107000, 15, 'Slashing', '10d4', 'Severe wound')
    HAMMER_METEORIC = Weapon('Hammer, meteoric', 164500, 16, 'Bludgeoning', '11d6', None)
    STARKNIFE_LIGHTSPEED = Weapon('Starknife, lightspeed', 183400, 16, 'Fire', '8d8', None)
    LONGSWORD_MOLECULAR_RIFT = Weapon('Longsword, Molecular Rift', 245200, 17, 'Slashing', '10d8', None)
    LONGSWORD_ULTRASERRATED = Weapon('Longsword, Ultraserrated', 368100, 18, 'Slashing', '8d10', 'Bleed 6d6')
    XENOLASH_SEEDED = Weapon('Xenolash, seeded', 409000, 18, 'Acid', '9d4', 'Corrode 6d4')
    HAMMER_GRAVITY_WELL = Weapon('Hammer, gravity well', 551000, 19, 'Bludgeoning', '15d6', None)
    STARKNIFE_DIMENSIONAL_SLICE = Weapon('Starknife, dimensional slice', 602200, 19, 'Piercing', '8d12', None)
    LONGSWORD_DIMENSIONAL_SLICE = Weapon('Longsword, Dimensional Slice', 727300, 20, 'Slashing', '14d8', None)
    
    CRYOPIKE_TACTICAL = Weapon('Cryopike, Tactical', 3360, 5, 'Cold', '1d8', None)
    CRYOPIKE_ADVANCED = Weapon('Cryopike, advanced', 34800, 12, 'Cold', '2d8', 'Staggered')
    CAPTURE_POLE_ENFORCEMENT = Weapon('Capture pole, enforcement-class', 325, 2, 'Piercing', '1d8', 'Injection DC +2')
    CAPTURE_POLE_APPREHENSION = Weapon('Capture pole, apprehension-class', 6600, 7, 'Piercing', '2d8', 'Injection DC +2')
    CAPTURE_POLE_IMPRISONMENT = Weapon('Capture pole, imprisonment-class', 36300, 12, 'Piercing', '6d6', 'Injection DC +2')
    CAPTURE_POLE_DOMINATION = Weapon('Capture pole, domination-class', 256500, 17, 'Piercing', '7d12', 'Injection DC +2')
    CAPTURE_POLE_OVERLORD = Weapon('Capture pole, overlord-class', 855000, 20, 'Piercing', '15d8', 'Injection DC +2')

    FLAME_DOSHKO_EMBER = Weapon('Flame doshko, ember', 750, 2, 'Fire', '1d8', 'Wound')
    FLAME_DOSHKO_BLAZE = Weapon('Flame doshko, blaze', 8500, 8, 'Fire', '2d8', 'Wound')
    FLAME_DOSHKO_INFERNO = Weapon('Flame doshko, inferno', 53200, 13, 'Fire', '5d8', 'Wound')
    FLAME_DOSHKO_SOLAR_FLARE = Weapon('Flame doshko, Solar flare', 595000, 19, 'Fire', '10d8', 'Severe wound')

    PLASMA_DOSHKO_RED_STAR = Weapon('Plasma doshko, red star', 4650, 6, 'Electricity', '1d10', 'Severe wound')
    PLASMA_DOSHKO_YELLOW_STAR = Weapon('Plasma doshko, yellow star', 17000, 10, 'Electricity', '2d10', 'Severe wound')
    PLASMA_DOSHKO_WHITE_STAR = Weapon('Plasma doshko, white star', 126800, 15, 'Electricity', '5d10', 'Severe wound')
    PLASMA_DOSHKO_BLUE_STAR = Weapon('Plasma doshko, blue star', 364100, 18, 'Electricity', '7d10', 'Severe wound')

    DOSHKO_TACTICAL = Weapon('Doshko, Tactical', 240, 1, 'Piercing', '1d12', None)
    PIKE_TACTICAL = Weapon('Pike, Tactical', 475, 2, 'Piercing', '1d8', None)
    CURVE_BLADE_CARBON_STEEL = Weapon('Curve Blade, carbon steel', 2230, 4, 'Slashing', '1d10', 'Bleed 1d6')
    SWOOP_HAMMER_TACTICAL = Weapon('Swoop Hammer, Tactical', 3360, 5, 'Bludgeoning', '1d10', 'Knockdown')
    DEVASTATION_BLADE_WRACK = Weapon('Devastation Blade, wrack', 5500, 7, 'Slashing', '2d8', None)
    DOSHKO_ADVANCED = Weapon('Doshko, advanced', 5300, 7, 'Piercing', '2d12', None)
    STAFF_SENTINEL = Weapon('Staff, sentinel', 6320, 7, 'Bludgeoning', '1d10', None)
    PIKE_ADVANCED = Weapon('Pike, advanced', 12200, 9, 'Piercing', '2d8', 'Bleed 1d8')
    SWOOP_HAMMER_ADVANCED = Weapon('Swoop Hammer, advanced', 14300, 9, 'Bludgeoning', '3d10', 'Knockdown')
    CURVE_BLADE_ULTRATHIN = Weapon('Curve Blade, ultrathin', 18100, 10, 'Slashing', '3d10', 'Bleed 2d6')
    DOSHKO_ULTRATHIN = Weapon('Doshko, ultrathin', 24600, 11, 'Piercing', '4d12', None)
    DEVASTATION_BLADE_RUIN = Weapon('Devastation Blade, ruin', 43900, 13, 'Slashing', '5d8', None)
    STAFF_REPELLER = Weapon('Staff, repeller', 45200, 13, 'Bludgeoning', '3d8', 'Knockdown')
    SWOOP_HAMMER_MACH_I = Weapon('Swoop Hammer, mach I', 44100, 13, 'Bludgeoning', '5d10', 'Knockdown')
    DOSHKO_ZERO_EDGE = Weapon('Doshko, zero-edge', 71500, 14, 'Piercing', '7d12', None)
    PIKE_ELITE = Weapon('Pike, elite', 95700, 15, 'Piercing', '7d8', 'Bleed 3d8')
    CURVE_BLADE_BUZZBLADE = Weapon('Curve Blade, buzzblade', 184300, 16, 'Slashing', '8d10', 'Bleed 5d6')
    DOSHKO_MOLECULAR_RIFT = Weapon('Doshko, molecular rift', 248000, 17, 'Piercing', '10d12', None)
    SWOOP_HAMMER_MACH_II = Weapon('Swoop Hammer, mach II', 273000, 17, 'Bludgeoning', '10d10', 'Knockdown')
    DEVASTATION_BLADE_APOCALYPSE = Weapon('Devastation Blade, apocalypse', 410200, 18, 'Slashing', '12d8', None)
    DOSHKO_DIMENSIONAL_BLADE = Weapon('Doshko, dimensional blade', 546100, 19, 'Piercing', '13d12', None)
    CURVE_BLADE_DIMENSIONAL_SLICE = Weapon('Curve Blade, dimensional slice', 815000, 20, 'Slashing', '12d10', 'Bleed 6d6')
    SWOOP_HAMMER_MACH_III = Weapon('Swoop Hammer, mach III', 905700, 20, 'Bludgeoning', '14d10', 'Knockdown')

class LightArmorConstants(metaclass=ItemMeta):
    DEFREX_HIDE_MATURE = Armor(name='Defrex hide, mature', value=9000, level=8, armor_weight='Light', eac=9, kac=11, dex='+4', ac_penalty=None, speed=None, upgrade_slots=2)
    DEFREX_HIDE_ADVANCED = Armor(name='Defrex hide, advanced', value=33000, level=12, armor_weight='Light', eac=14, kac=16, dex='+5', ac_penalty=None, speed=None, upgrade_slots=3)
    DEFREX_HIDE_ELITE = Armor(name='Defrex hide, elite', value=142000, level=16, armor_weight='Light', eac=19, kac=21, dex='+6', ac_penalty=None, speed=None, upgrade_slots=4)
    ESTEX_SUIT_I = Armor(name='Estex suit I', value=410, level=1, armor_weight='Light', eac=0, kac=1, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=2)
    SECOND_SKIN = Armor(name='Second skin', value=250, level=1, armor_weight='Light', eac=1, kac=2, dex='+5', ac_penalty=None, speed=None, upgrade_slots=1)
    STATIONWEAR_FLIGHT_SUIT = Armor(name='Stationwear, flight suit', value=95, level=1, armor_weight='Light', eac=0, kac=1, dex='+6', ac_penalty=None, speed=None, upgrade_slots=0)
    FREEBOOTER_ARMOR_I = Armor(name='Freebooter armor I', value=750, level=2, armor_weight='Light', eac=2, kac=3, dex='+4', ac_penalty=None, speed=None, upgrade_slots=0)
    KASATHA_MICROCORD_I = Armor(name='Kasatha microcord I', value=460, level=2, armor_weight='Light', eac=1, kac=3, dex='+3', ac_penalty='-1', speed=None, upgrade_slots=0)
    Z_DIFFRACTOR_I = Armor(name='Z Diffractor I', value=650, level=2, armor_weight='Light', eac=2, kac=2, dex='+4', ac_penalty=None, speed=None, upgrade_slots=0)
    CARBON_SKIN_GRAPHITE = Armor(name='Carbon skin, graphite', value=1220, level=3, armor_weight='Light', eac=3, kac=4, dex='+4', ac_penalty='-1', speed=None, upgrade_slots=1)
    HARDENED_RESIN = Armor(name='Hardened Resin', value=1200, level=3, armor_weight='Light', eac=2, kac=3, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=1)
    STATIONWEAR_CASUAL = Armor(name='Stationwear, casual', value=1300, level=3, armor_weight='Light', eac=1, kac=2, dex='+6', ac_penalty=None, speed=None, upgrade_slots=0)
    DEFREX_HIDE = Armor(name='Defrex hide', value=2250, level=4, armor_weight='Light', eac=5, kac=5, dex=4, ac_penalty=None, speed=None, upgrade_slots=1)
    LASHUNTA_TEMPWEAVE_BASIC = Armor(name='Lashunta tempweave, basic', value=1950, level=4, armor_weight='Light', eac=4, kac=4, dex='+5', ac_penalty=None, speed=None, upgrade_slots=1)
    D_SUIT_I = Armor(name='D-suit I', value=2980, level=5, armor_weight='Light', eac=5, kac=6, dex='+5', ac_penalty=None, speed=None, upgrade_slots=1)
    ESTEX_SUIT_II = Armor(name='Estex suit II', value=2700, level=5, armor_weight='Light', eac=4, kac=5, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=3)
    STATIONWEAR_BUSINESS = Armor(name='Stationwear, business', value=2600, level=5, armor_weight='Light', eac=2, kac=3, dex='+6', ac_penalty=None, speed=None, upgrade_slots=0)
    FREEBOOTER_ARMOR_II = Armor(name='Freebooter armor II', value=4720, level=6, armor_weight='Light', eac=6, kac=8, dex='+5', ac_penalty=None, speed=None, upgrade_slots=1)
    KASATHA_MICROCORD_II = Armor(name='Kasatha microcord II', value=3670, level=6, armor_weight='Light', eac=6, kac=8, dex='+4', ac_penalty='-1', speed=None, upgrade_slots=1)
    STATIONWEAR_ELITE = Armor(name='Stationwear, elite', value=4100, level=6, armor_weight='Light', eac=4, kac=5, dex='+7', ac_penalty=None, speed=None, upgrade_slots=0)
    YSOKI_REFRACTOR_SUIT = Armor(name='Ysoki refractor suit', value=4120, level=6, armor_weight='Light', eac=7, kac=7, dex='+5', ac_penalty=None, speed=None, upgrade_slots=2)
    Z_DIFFRACTOR_II = Armor(name='Z Diffractor II', value=4150, level=6, armor_weight='Light', eac=6, kac=6, dex='+6', ac_penalty=None, speed=None, upgrade_slots=1)
    RED_TANG_SPICE_GUILD_TRAVEL_SUIT_SILVER = Armor(name='Red Tang Spice Guild travel suit, silver', value=7250, level=7, armor_weight='Light', eac=6, kac=7, dex='+7', ac_penalty=None, speed=None, upgrade_slots=0)
    D_SUIT_II = Armor(name='D-suit II', value=6900, level=7, armor_weight='Light', eac=8, kac=9, dex='+5', ac_penalty=None, speed=None, upgrade_slots=2)
    ESTEX_SUIT_III = Armor(name='Estex suit III', value=5500, level=7, armor_weight='Light', eac=7, kac=8, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=4)
    KASATHA_MICROCORD_III = Armor(name='Kasatha microcord III', value=9000, level=8, armor_weight='Light', eac=9, kac=11, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=2)
    LASHUNTA_TEMPWEAVE_ADVANCED = Armor(name='Lashunta tempweave, advanced', value=8500, level=8, armor_weight='Light', eac=9, kac=10, dex='+6', ac_penalty=None, speed=None, upgrade_slots=3)
    RED_TANG_SPICE_GUILD_TRAVEL_SUIT_GOLD = Armor(name='Red Tang Spice Guild travel suit, gold', value=12100, level=9, armor_weight='Light', eac=9, kac=10, dex='+8', ac_penalty=None, speed=None, upgrade_slots=0)
    D_SUIT_III = Armor(name='D-suit III', value=13300, level=9, armor_weight='Light', eac=11, kac=12, dex='+6', ac_penalty=None, speed=None, upgrade_slots=3)
    Z_DIFFRACTOR_III = Armor(name='Z Diffractor III', value=12500, level=9, armor_weight='Light', eac=11, kac=11, dex='+7', ac_penalty=None, speed=None, upgrade_slots=2)
    CARBON_SKIN_WHITE_CARBON = Armor(name='Carbon skin, white carbon', value=19650, level=10, armor_weight='Light', eac=12, kac=14, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=3)
    FREEBOOTER_ARMOR_III = Armor(name='Freebooter armor III', value=16900, level=10, armor_weight='Light', eac=12, kac=13, dex='+6', ac_penalty=None, speed=None, upgrade_slots=3)
    KASATHA_MICROCORD_IV = Armor(name='Kasatha microcord IV', value=23800, level=11, armor_weight='Light', eac=13, kac=15, dex='+5', ac_penalty='-1', speed=None, upgrade_slots=3)
    RED_TANG_SPICE_GUILD_TRAVEL_SUIT_PLATINUM = Armor(name='Red Tang Spice Guild travel suit, platinum', value=34600, level=12, armor_weight='Light', eac=12, kac=13, dex='+8', ac_penalty=None, speed=None, upgrade_slots=0)
    HARDLIGHT_SERIES_SQUAD = Armor(name='Hardlight series, squad', value=30750, level=12, armor_weight='Light', eac=15, kac=15, dex='+6', ac_penalty=None, speed=None, upgrade_slots=4)
    D_SUIT_IV = Armor(name='D-suit IV', value=45800, level=13, armor_weight='Light', eac=16, kac=17, dex='+6', ac_penalty=None, speed=None, upgrade_slots=4)
    ESTEX_SUIT_IV = Armor(name='Estex suit IV', value=49250, level=13, armor_weight='Light', eac=15, kac=16, dex='+6', ac_penalty='-1', speed=None, upgrade_slots=6)
    Z_DIFFRACTOR_IV = Armor(name='Z Diffractor IV', value=48500, level=13, armor_weight='Light', eac=15, kac=15, dex='+8', ac_penalty=None, speed=None, upgrade_slots=0)
    ECHELON_FASHION_READY_TO_WEAR = Armor(name='Echelon fashion, ready to wear', value=71300, level=14, armor_weight='Light', eac=15, kac=16, dex='+8', ac_penalty=None, speed=None, upgrade_slots=0)
    FREEBOOTER_ARMOR_IV = Armor(name='Freebooter armor IV', value=60600, level=14, armor_weight='Light', eac=17, kac=18, dex='+6', ac_penalty=None, speed=None, upgrade_slots=4)
    CARBON_SKIN_DIAMOND = Armor(name='Carbon skin, diamond', value=126400, level=15, armor_weight='Light', eac=17, kac=19, dex='+7', ac_penalty='-1', speed=None, upgrade_slots=4)
    HARDLIGHT_SERIES_ELITE = Armor(name='Hardlight series, elite', value=123500, level=15, armor_weight='Light', eac=18, kac=18, dex='+7', ac_penalty=None, speed=None, upgrade_slots=4)
    SWARMSUIT = Armor(name='Swarmsuit', value=95200, level=15, armor_weight='Light', eac=18, kac=19, dex='+6', ac_penalty=None, speed=None, upgrade_slots=4)
    SHOTALASHU_ARMOR = Armor(name='Shotalashu armor', value=149500, level=16, armor_weight='Light', eac=19, kac=20, dex='+7', ac_penalty=None, speed=None, upgrade_slots=5)
    D_SUIT_V = Armor(name='D-suit V', value=244300, level=17, armor_weight='Light', eac=20, kac=21, dex='+7', ac_penalty=None, speed=None, upgrade_slots=5)
    ECHELON_FASHION_BESPOKE = Armor(name='Echelon fashion, bespoke', value=285000, level=17, armor_weight='Light', eac=18, kac=19, dex='+8', ac_penalty=None, speed=None, upgrade_slots=0)
    FREEBOOTER_ARMOR_V = Armor(name='Freebooter armor V', value=367650, level=18, armor_weight='Light', eac=20, kac=21, dex='+8', ac_penalty=None, speed=None, upgrade_slots=5)
    Z_DIFFRACTOR_V = Armor(name='Z Diffractor V', value=340000, level=18, armor_weight='Light', eac=20, kac=20, dex='+9', ac_penalty=None, speed=None, upgrade_slots=4)
    D_SUIT_VI = Armor(name='D-suit VI', value=552000, level=19, armor_weight='Light', eac=21, kac=22, dex='+8', ac_penalty=None, speed=None, upgrade_slots=6)
    CARBON_SKIN_NANOTUBE = Armor(name='Carbon skin, nanotube', value=825000, level=20, armor_weight='Light', eac=21, kac=23, dex='+8', ac_penalty='-1', speed=None, upgrade_slots=6)
    HARDLIGHT_SERIES_SPECIALIST = Armor(name='Hardlight series, specialist', value=928000, level=20, armor_weight='Light', eac=22, kac=22, dex='+8', ac_penalty=None, speed=None, upgrade_slots=6)

class HeavyArmorConstants(metaclass=ItemMeta):
    CEREMONIAL_PLATE_TROOP = Armor(name='Ceremonial plate, troop', value=110, level=1, armor_weight='Light', eac=1, kac=3, dex='+2', ac_penalty='-3', speed='-10 ft.', upgrade_slots=3)
    GOLEMFORGED_PLATING_I = Armor(name='Golemforged plating I', value=250, level=1, armor_weight='Light', eac=2, kac=5, dex='+0', ac_penalty='-3', speed='-10 ft.', upgrade_slots=0)
    LASHUNTA_RINGWEAR_I = Armor(name='Lashunta ringwear I', value=415, level=1, armor_weight='Light', eac=2, kac=4, dex='+2', ac_penalty='-2', speed='-5 ft.', upgrade_slots=0)
    HELLKNIGHT_PLATE_ARMIGER = Armor(name='Hellknight plate, armiger', value=980, level=2, armor_weight='Light', eac=4, kac=5, dex='+2', ac_penalty='-2', speed='-10 ft.', upgrade_slots=2)
    HIDDEN_SOLDIER_ARMOR = Armor(name='Hidden soldier armor', value=465, level=2, armor_weight='Light', eac=3, kac=5, dex='+2', ac_penalty='-2', speed='-5 ft.', upgrade_slots=1)
    IRIDISHELL_BASIC = Armor(name='Iridishell, basic', value=755, level=2, armor_weight='Light', eac=3, kac=6, dex='+2', ac_penalty='-2', speed='-5 ft.', upgrade_slots=0)
    THINPLATE = Armor(name='Thinplate', value=1000, level=2, armor_weight='Light', eac=4, kac=6, dex='+2', ac_penalty='-3', speed='-10 ft.', upgrade_slots=1)
    DEFIANCE_SERIES_SQUAD = Armor(name='Defiance series, squad', value=1220, level=3, armor_weight='Light', eac=5, kac=8, dex='+1', ac_penalty='-4', speed='-10 ft.', upgrade_slots=1)
    GOLEMFORGED_PLATING_II = Armor(name='Golemforged plating II', value=1610, level=3, armor_weight='Light', eac=5, kac=7, dex='+2', ac_penalty='-2', speed='-10 ft.', upgrade_slots=1)
    CEREMONIAL_PLATE_OFFICER = Armor(name='Ceremonial plate, officer', value=2275, level=4, armor_weight='Light', eac=6, kac=8, dex='+2', ac_penalty='-2', speed='-5 ft.', upgrade_slots=1)
    FORMIAN_HIDE_BASIC = Armor(name='Formian hide, basic', value=2400, level=4, armor_weight='Light', eac=7, kac=8, dex='+2', ac_penalty='-3', speed='-5 ft.', upgrade_slots=2)
    HELLKNIGHT_PLATE_LICTOR = Armor(name='Hellknight plate, lictor', value=3300, level=5, armor_weight='Light', eac=9, kac=10, dex='+2', ac_penalty='-2', speed='-10 ft.', upgrade_slots=2)
    LASHUNTA_RINGWEAR_II = Armor(name='Lashunta ringwear II', value=2970, level=5, armor_weight='Light', eac=8, kac=10, dex='+2', ac_penalty='-2', speed='-5 ft.', upgrade_slots=1)
    VESK_OVERPLATE_I = Armor(name='Vesk overplate I', value=3910, level=6, armor_weight='Light', eac=9, kac=11, dex='+3', ac_penalty='-2', speed='-5 ft.', upgrade_slots=1)
    CEREMONIAL_PLATE_COMMANDER = Armor(name='Ceremonial plate, commander', value=7350, level=7, armor_weight='Light', eac=10, kac=12, dex='+2', ac_penalty='-3', speed='-10 ft.', upgrade_slots=5)
    DEFIANCE_SERIES_ELITE = Armor(name='Defiance series, elite', value=6300, level=7, armor_weight='Light', eac=10, kac=13, dex='+2', ac_penalty='-4', speed='-10 ft.', upgrade_slots=2)
    FORMIAN_HIDE_ADVANCED = Armor(name='Formian hide, advanced', value=6100, level=7, armor_weight='Light', eac=10, kac=12, dex='+3', ac_penalty='-3', speed='-5 ft.', upgrade_slots=3)
    GOLEMFORGED_PLATING_III = Armor(name='Golemforged plating III', value=5500, level=7, armor_weight='Light', eac=10, kac=12, dex='+3', ac_penalty='-2', speed='-5 ft.', upgrade_slots=2)
    LASHUNTA_RINGWEAR_III = Armor(name='Lashunta ringwear III', value=8420, level=8, armor_weight='Light', eac=12, kac=14, dex='+3', ac_penalty='-2', speed='-5 ft.', upgrade_slots=3)
    VESK_OVERPLATE_II = Armor(name='Vesk overplate II', value=10250, level=8, armor_weight='Light', eac=13, kac=15, dex='+2', ac_penalty='-3', speed='-10 ft.', upgrade_slots=3)
    HELLKNIGHT_PLATE_MARALICTOR = Armor(name='Hellknight plate, maralictor', value=14500, level=9, armor_weight='Light', eac=16, kac=17, dex='+2', ac_penalty='-2', speed='-10 ft.', upgrade_slots=4)
    IRIDISHELL_ADVANCED = Armor(name='Iridishell, advanced', value=13100, level=9, armor_weight='Light', eac=13, kac=15, dex='+3', ac_penalty=None, speed=None, upgrade_slots=3)
    STARFIRE_ARMOR_PINION = Armor(name='Starfire armor, pinion', value=14200, level=9, armor_weight='Light', eac=14, kac=16, dex='+3', ac_penalty='-2', speed='-5 ft.', upgrade_slots=4)
    DEFIANCE_SERIES_SPECIALIST = Armor(name='Defiance series, specialist', value=16950, level=10, armor_weight='Light', eac=15, kac=18, dex='+2', ac_penalty='-4', speed='-10 ft.', upgrade_slots=3)
    FORMIAN_HIDE_SUPERIOR = Armor(name='Formian hide, superior', value=16500, level=10, armor_weight='Light', eac=15, kac=17, dex='+3', ac_penalty='-4', speed='-5 ft.', upgrade_slots=3)
    GOLEMFORGED_PLATING_IV = Armor(name='Golemforged plating IV', value=24800, level=11, armor_weight='Light', eac=15, kac=17, dex='+3', ac_penalty='-3', speed='-10 ft.', upgrade_slots=6)
    LASHUNTA_RINGWEAR_IV = Armor(name='Lashunta ringwear IV', value=27100, level=11, armor_weight='Light', eac=16, kac=18, dex='+4', ac_penalty='-3', speed='-5 ft.', upgrade_slots=4)
    VESK_OVERPLATE_III = Armor(name='Vesk overplate III', value=23400, level=11, armor_weight='Light', eac=16, kac=18, dex='+3', ac_penalty='-2', speed='-5 ft.', upgrade_slots=4)
    AEGIS_SERIES_SQUAD = Armor(name='Aegis series, squad', value=45200, level=12, armor_weight='Light', eac=17, kac=19, dex='+3', ac_penalty='-5', speed='-10 ft.', upgrade_slots=5)
    IRIDISHELL_SUPERIOR = Armor(name='Iridishell, superior', value=42250, level=12, armor_weight='Light', eac=17, kac=18, dex='+4', ac_penalty=None, speed=None, upgrade_slots=4)
    VESK_MONOLITH_I = Armor(name='Vesk monolith I', value=39650, level=12, armor_weight='Light', eac=16, kac=18, dex='+4', ac_penalty='-2', speed='-5 ft.', upgrade_slots=5)
    STARFIRE_ARMOR_EXIDENT = Armor(name='Starfire armor, exident', value=53600, level=13, armor_weight='Light', eac=18, kac=20, dex='+4', ac_penalty='-2', speed='-5 ft.', upgrade_slots=5)
    GOLEMFORGED_PLATING_V = Armor(name='Golemforged plating V', value=63750, level=14, armor_weight='Light', eac=18, kac=20, dex='+4', ac_penalty='-3', speed='-10 ft.', upgrade_slots=7)
    HELLKNIGHT_PLATE_PARALICTOR = Armor(name='Hellknight plate, paralictor', value=80000, level=14, armor_weight='Light', eac=21, kac=22, dex='+3', ac_penalty='-2', speed='-10 ft.', upgrade_slots=6)
    VESK_OVERPLATE_IV = Armor(name='Vesk overplate IV', value=71850, level=14, armor_weight='Light', eac=19, kac=21, dex='+4', ac_penalty='-2', speed='-5 ft.', upgrade_slots=5)
    ENGINERUNNER = Armor(name='Enginerunner', value=120900, level=15, armor_weight='Light', eac=21, kac=22, dex='+4', ac_penalty=None, speed=None, upgrade_slots=5)
    LASHUNTA_RINGWEAR_V = Armor(name='Lashunta ringwear V', value=94200, level=15, armor_weight='Light', eac=20, kac=22, dex='+4', ac_penalty='-2', speed='-5 ft.', upgrade_slots=5)
    STEELBONES = Armor(name='Steelbones', value=145500, level=16, armor_weight='Light', eac=21, kac=23, dex='+4', ac_penalty='-3', speed='-5 ft.', upgrade_slots=6)
    VESK_MONOLITH_II = Armor(name='Vesk monolith II', value=163400, level=16, armor_weight='Light', eac=22, kac=24, dex='+4', ac_penalty='-3', speed='-5 ft.', upgrade_slots=6)
    AEGIS_SERIES_ELITE = Armor(name='Aegis series, elite', value=209000, level=17, armor_weight='Light', eac=23, kac=27, dex='+3', ac_penalty='-5', speed='-10 ft.', upgrade_slots=6)
    VESK_OVERPLATE_V = Armor(name='Vesk overplate V', value=415800, level=18, armor_weight='Light', eac=24, kac=26, dex='+4', ac_penalty='-3', speed='-5 ft.', upgrade_slots=7)
    VITRUM_PLATE = Armor(name='Vitrum plate', value=365650, level=18, armor_weight='Light', eac=23, kac=24, dex='+5', ac_penalty=None, speed=None, upgrade_slots=4)
    VOIDSHIELD_ARMOR = Armor(name='Voidshield armor', value=610250, level=19, armor_weight='Light', eac=25, kac=26, dex='+5', ac_penalty='-3', speed='-5 ft.', upgrade_slots=7)
    AEGIS_SERIES_SPECIALIST = Armor(name='Aegis series, specialist', value=932000, level=20, armor_weight='Light', eac=25, kac=28, dex='+4', ac_penalty='-4', speed='-10 ft.', upgrade_slots=7)
    VESK_MONOLITH_III = Armor(name='Vesk monolith III', value=827250, level=20, armor_weight='Light', eac=26, kac=27, dex='+5', ac_penalty='-2', speed='-5 ft.', upgrade_slots=7)
